import type { PlanningRepository } from '../../application/planning/planning-service'
import type { CoachDatabase } from '../database/connection'
import type { AcademicOverview } from '../../shared/contracts/planning-contract'
import { academicEventPhase } from '../../application/planning/academic-time'
import type { ExistingWeeklyItem, WeeklyPlanningTopic } from '../../application/planning/weekly-planner'

export class DrizzlePlanningRepository implements PlanningRepository {
  constructor(private readonly database: CoachDatabase) {}
  createDeadline(input: { id: string; workspaceId: string; title: string; dueAt: number; estimatedMinutes: number; masteryPercent: number | null; createdAt: number }): void { this.database.sqlite.prepare('INSERT INTO study_deadlines (id, workspace_id, title, due_at, estimated_minutes, mastery_percent, completed, created_at) VALUES (?, ?, ?, ?, ?, ?, 0, ?)').run(input.id, input.workspaceId, input.title, input.dueAt, input.estimatedMinutes, input.masteryPercent, input.createdAt) }
  addRoutineNote(input: { id: string; content: string; createdAt: number }): void { this.database.sqlite.prepare('INSERT INTO routine_notes (id, content, created_at) VALUES (?, ?, ?)').run(input.id, input.content, input.createdAt) }
  listRoutineNotes(): string[] { return (this.database.sqlite.prepare('SELECT content FROM routine_notes ORDER BY created_at DESC LIMIT 20').all() as Array<{ content: string }>).map((item) => item.content) }
  getWorkspaceName(workspaceId: string): string { return (this.database.sqlite.prepare('SELECT name FROM workspaces WHERE id = ?').get(workspaceId) as { name: string } | undefined)?.name ?? 'Workspace' }
  getCanonicalPlanningTimezone(fallback: string): string { return (this.database.sqlite.prepare('SELECT timezone FROM weekly_plans ORDER BY generated_at, rowid LIMIT 1').get() as { timezone: string } | undefined)?.timezone ?? fallback }
  listWorkspaces(): Array<{ id: string; name: string; objective: string }> { return this.database.sqlite.prepare("SELECT id, name, objective FROM workspaces WHERE status = 'active'").all() as Array<{ id: string; name: string; objective: string }> }
  registerAcademicEvent(input: { id: string; deadlineId: string; workspaceId: string; type: 'exam' | 'assignment' | 'deadline'; title: string; dueAt: number; estimatedMinutes: number; masteryPercent: number | null; now: number }): void { this.database.sqlite.transaction(() => { this.database.sqlite.prepare('INSERT INTO academic_events (id, workspace_id, type, title, due_at, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)').run(input.id, input.workspaceId, input.type, input.title, input.dueAt, input.now, input.now); this.createDeadline({ id: input.deadlineId, workspaceId: input.workspaceId, title: input.title, dueAt: input.dueAt, estimatedMinutes: input.estimatedMinutes, masteryPercent: input.masteryPercent, createdAt: input.now }) })() }
  updateLatestAcademicEvent(workspaceId: string, type: 'exam' | 'assignment' | 'deadline', dueAt: number, now: number): boolean { const changed = this.database.sqlite.prepare('UPDATE academic_events SET due_at = ?, updated_at = ? WHERE id = (SELECT id FROM academic_events WHERE workspace_id = ? AND type = ? ORDER BY due_at DESC LIMIT 1)').run(dueAt, now, workspaceId, type).changes > 0; if (changed) this.database.sqlite.prepare('UPDATE study_deadlines SET due_at = ? WHERE id = (SELECT id FROM study_deadlines WHERE workspace_id = ? AND completed = 0 ORDER BY due_at DESC LIMIT 1)').run(dueAt, workspaceId); return changed }
  setAvailability(weekday: number, minutes: number, now: number): void { this.database.sqlite.prepare('INSERT INTO academic_availability (weekday, minutes, updated_at) VALUES (?, ?, ?) ON CONFLICT(weekday) DO UPDATE SET minutes=excluded.minutes, updated_at=excluded.updated_at').run(weekday, minutes, now) }
  setTodayBudget(dateKey: string, timezone: string, minutes: number, now: number): void { this.database.sqlite.prepare('INSERT INTO daily_planning_budgets (date_key,timezone,minutes,updated_at) VALUES (?,?,?,?) ON CONFLICT(date_key,timezone) DO UPDATE SET minutes=excluded.minutes,updated_at=excluded.updated_at').run(dateKey, timezone, minutes, now) }
  listTodayBudgets(weekStart: string, timezone: string): Array<{ dateKey: string; minutes: number }> { return this.database.sqlite.prepare("SELECT date_key AS dateKey,minutes FROM daily_planning_budgets WHERE timezone=? AND date_key>=? AND date_key<=date(?, '+6 days')").all(timezone, weekStart, weekStart) as Array<{ dateKey: string; minutes: number }> }
  transaction<T>(operation: () => T): T { return this.database.sqlite.transaction(operation)() }
  setWeeklyPlanItemCompletion(workspaceId: string, itemId: string, completed: boolean, now: number): boolean { return this.database.sqlite.transaction(() => { const row = this.database.sqlite.prepare('SELECT status,duration_minutes AS durationMinutes FROM weekly_plan_items WHERE id=? AND workspace_id=?').get(itemId, workspaceId) as { status: string; durationMinutes: number } | undefined; if (!row || (row.status === 'completed') === completed) return false; this.database.sqlite.prepare('UPDATE weekly_plan_items SET status=?,updated_at=? WHERE id=? AND workspace_id=?').run(completed ? 'completed' : 'pending', now, itemId, workspaceId); this.database.sqlite.prepare('UPDATE study_plan_items SET status=?,updated_at=? WHERE id=? AND workspace_id=?').run(completed ? 'completed' : 'pending', now, itemId, workspaceId); this.database.sqlite.prepare('INSERT INTO plan_item_completion_history (id,item_id,workspace_id,completed,duration_minutes,created_at) VALUES (?,?,?,?,?,?)').run(crypto.randomUUID(), itemId, workspaceId, Number(completed), row.durationMinutes, now); return true })() }
  getAcademicOverview(now: number): AcademicOverview { const events = (this.database.sqlite.prepare('SELECT e.id, e.workspace_id AS workspaceId, w.name AS workspaceName, e.type, e.title, e.due_at AS dueAt FROM academic_events e JOIN workspaces w ON w.id=e.workspace_id ORDER BY e.due_at').all() as Array<Omit<AcademicOverview['events'][number], 'phase'>>).map((event) => ({ ...event, phase: academicEventPhase(event.dueAt, now) })); const availability = this.database.sqlite.prepare('SELECT weekday, minutes FROM academic_availability ORDER BY weekday').all() as unknown as AcademicOverview['availability']; const workspaces = this.database.sqlite.prepare(`SELECT w.id AS workspaceId, w.name AS workspaceName, (SELECT topic_id FROM study_progress_events e WHERE e.workspace_id=w.id AND e.type='CHECKPOINT_ANSWERED' AND e.correct=0 ORDER BY e.created_at DESC LIMIT 1) AS difficulty, COALESCE((SELECT COUNT(*) FROM study_progress_events e WHERE e.workspace_id=w.id AND e.type='TOPIC_COMPLETED'),0) AS completedTopics, COALESCE((SELECT SUM(json_array_length(m.topics_json)) FROM roadmap_modules m JOIN roadmaps r ON r.id=m.roadmap_id WHERE r.workspace_id=w.id AND r.status='accepted'),0) AS totalTopics FROM workspaces w WHERE w.status='active' ORDER BY w.name`).all() as AcademicOverview['workspaces']; return { events, availability, workspaces, routine: this.listRoutineNotes() } }
  listPriorityInputs(): Array<{ workspaceId: string; title: string; dueAt: number; estimatedMinutes: number; masteryPercent: number | null; recentFocusSeconds: number }> { return this.database.sqlite.prepare(`SELECT source.workspaceId,source.title,source.dueAt,source.estimatedMinutes,source.masteryPercent,COALESCE(SUM(CASE WHEN s.ended_at>=? THEN s.focus_seconds ELSE 0 END),0) AS recentFocusSeconds FROM (SELECT d.id,d.workspace_id AS workspaceId,d.title,d.due_at AS dueAt,d.estimated_minutes AS estimatedMinutes,d.mastery_percent AS masteryPercent FROM study_deadlines d WHERE d.completed=0 UNION ALL SELECT a.id,a.workspace_id,a.title,a.ends_at,CASE a.kind WHEN 'event' THEN 240 ELSE 180 END,NULL FROM academic_life_items a WHERE a.status='active' AND a.replaced_by_id IS NULL AND a.workspace_id IS NOT NULL AND a.kind IN ('event','commitment') AND a.ends_at>=? AND (a.expires_at IS NULL OR a.expires_at>?) AND NOT EXISTS (SELECT 1 FROM study_deadlines d WHERE d.workspace_id=a.workspace_id AND d.title=a.title AND d.due_at=a.ends_at)) source JOIN workspaces w ON w.id=source.workspaceId LEFT JOIN study_sessions s ON s.workspace_id=source.workspaceId WHERE w.status='active' GROUP BY source.id`).all(this.nowMinusWeek(), Date.now(), Date.now()) as Array<{ workspaceId: string; title: string; dueAt: number; estimatedMinutes: number; masteryPercent: number | null; recentFocusSeconds: number }> }
  findWeeklyPlan(weekStart: string, timezone: string): { id: string; revision: number; generatedAt: number; items: ExistingWeeklyItem[] } | null { const plan = this.database.sqlite.prepare('SELECT id,revision,generated_at AS generatedAt FROM weekly_plans WHERE week_start=? AND timezone=?').get(weekStart, timezone) as { id: string; revision: number; generatedAt: number } | undefined; if (!plan) return null; const items = this.database.sqlite.prepare('SELECT id,workspace_id AS workspaceId,source_key AS sourceKey,date_key AS dateKey,title,duration_minutes AS durationMinutes,position,status,module_id AS moduleId,topic_id AS topicId,activity_type AS activityType,scheduled_start_minutes AS scheduledStartMinutes,reason FROM weekly_plan_items WHERE plan_id=? ORDER BY date_key,position').all(plan.id) as ExistingWeeklyItem[]; return { ...plan, items } }
  listWeeklyAvailability(now: number): Array<{ weekday: number; minutes: number }> { const rows = this.database.sqlite.prepare("SELECT weekday,minutes,workspace_id AS workspaceId,updated_at AS updatedAt FROM academic_life_items WHERE kind='availability' AND status='active' AND replaced_by_id IS NULL AND (expires_at IS NULL OR expires_at>?) ORDER BY updated_at DESC").all(now) as Array<{ weekday: number; minutes: number; workspaceId: string | null; updatedAt: number }>; const explicit = this.database.sqlite.prepare('SELECT weekday,minutes,updated_at AS updatedAt FROM academic_availability').all() as Array<{ weekday: number; minutes: number; updatedAt: number }>; const latest = new Map<number, { minutes: number; updatedAt: number }>(); for (const item of explicit) latest.set(item.weekday, item); for (const row of rows) if (row.workspaceId === null && row.updatedAt > (latest.get(row.weekday)?.updatedAt ?? -1)) latest.set(row.weekday, row); return [...latest].map(([weekday, item]) => ({ weekday, minutes: item.minutes })) }
  listWeeklyPlanningTopics(now: number): WeeklyPlanningTopic[] { const rows = this.database.sqlite.prepare(`SELECT w.id AS workspaceId,w.name AS workspaceName,m.id AS moduleId,m.position AS modulePosition,m.topics_json AS topicsJson,p.topic_statuses_json AS statusesJson,deadline.dueAt,deadline.deadlineTitle FROM workspaces w JOIN roadmaps r ON r.workspace_id=w.id AND r.status='accepted' JOIN roadmap_modules m ON m.roadmap_id=r.id LEFT JOIN study_progress p ON p.workspace_id=w.id LEFT JOIN (SELECT workspaceId,dueAt,deadlineTitle FROM (SELECT workspace_id AS workspaceId,due_at AS dueAt,title AS deadlineTitle FROM study_deadlines WHERE completed=0 AND due_at>=? UNION ALL SELECT workspace_id,ends_at,title FROM academic_life_items WHERE status='active' AND replaced_by_id IS NULL AND workspace_id IS NOT NULL AND kind IN ('event','commitment') AND ends_at>=? AND (expires_at IS NULL OR expires_at>=?)) candidates GROUP BY workspaceId HAVING dueAt=MIN(dueAt)) deadline ON deadline.workspaceId=w.id WHERE w.status='active' ORDER BY w.id,m.position`).all(now, now, now) as Array<{ workspaceId: string; workspaceName: string; moduleId: string; modulePosition: number; topicsJson: string; statusesJson: string | null; dueAt: number | null; deadlineTitle: string | null }>; const result: WeeklyPlanningTopic[] = []; for (const row of rows) { const statuses = row.statusesJson ? JSON.parse(row.statusesJson) as Record<string, WeeklyPlanningTopic['progress']> : {}; for (const topic of JSON.parse(row.topicsJson) as string[]) { const topicId = `${row.moduleId}:${topic}`; const state = this.database.sqlite.prepare('SELECT evidence_count AS evidenceCount,mastery_estimate AS masteryEstimate,confidence,needs_review AS needsReview,difficulty_level AS difficultyLevel FROM topic_learning_states WHERE workspace_id=? AND topic_id=?').get(row.workspaceId, topicId) as { evidenceCount: number; masteryEstimate: number | null; confidence: WeeklyPlanningTopic['confidence']; needsReview: number; difficultyLevel: WeeklyPlanningTopic['difficultyLevel'] } | undefined; result.push({ workspaceId: row.workspaceId, workspaceName: row.workspaceName, moduleId: row.moduleId, modulePosition: row.modulePosition, topicId, topic, progress: statuses[topicId] ?? 'NOT_STARTED', evidenceCount: state?.evidenceCount ?? 0, masteryEstimate: state?.masteryEstimate ?? null, confidence: state?.confidence ?? 'low', needsReview: Boolean(state?.needsReview), difficultyLevel: state?.difficultyLevel ?? 'low', dueAt: row.dueAt, deadlineTitle: row.deadlineTitle }) } } return result }
  saveWeeklyPlan(input: { id: string; weekStart: string; timezone: string; revision: number; generatedAt: number; items: ExistingWeeklyItem[] }): void { this.database.sqlite.transaction(() => { this.database.sqlite.prepare('INSERT INTO weekly_plans (id,week_start,timezone,revision,generated_at,updated_at) VALUES (?,?,?,?,?,?) ON CONFLICT(week_start,timezone) DO UPDATE SET revision=excluded.revision,generated_at=excluded.generated_at,updated_at=excluded.updated_at').run(input.id, input.weekStart, input.timezone, input.revision, input.generatedAt, input.generatedAt); const plan = this.database.sqlite.prepare('SELECT id FROM weekly_plans WHERE week_start=? AND timezone=?').get(input.weekStart, input.timezone) as { id: string }; this.database.sqlite.prepare("DELETE FROM weekly_plan_items WHERE plan_id=? AND status='pending'").run(plan.id); const insert = this.database.sqlite.prepare('INSERT OR REPLACE INTO weekly_plan_items (id,plan_id,workspace_id,source_key,date_key,title,duration_minutes,position,status,module_id,topic_id,activity_type,scheduled_start_minutes,reason,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)'); for (const item of input.items) insert.run(item.id, plan.id, item.workspaceId, item.sourceKey, item.dateKey, item.title, item.durationMinutes, item.position, item.status, item.moduleId, item.topicId, item.activityType, item.scheduledStartMinutes, item.reason, input.generatedAt, input.generatedAt) })() }
  listLegacyDailyItems(dateKey: string): ExistingWeeklyItem[] { return (this.database.sqlite.prepare("SELECT p.id,p.workspace_id AS workspaceId,(p.workspace_id || ':' || COALESCE(p.topic_id,p.id) || ':' || COALESCE(p.activity_type,'review')) AS sourceKey,? AS dateKey,p.title,p.duration_minutes AS durationMinutes,p.position,CASE p.status WHEN 'active' THEN 'in_progress' ELSE p.status END AS status,p.module_id AS moduleId,p.topic_id AS topicId,CASE WHEN p.activity_type IN ('introduction','review','exercise') THEN p.activity_type ELSE 'review' END AS activityType,COALESCE(p.scheduled_start_minutes,1080) AS scheduledStartMinutes,'Migrado do plano diário anterior.' AS reason FROM study_plan_items p JOIN workspace_study_states s ON s.active_session_id=p.session_id WHERE p.session_id=s.active_session_id ORDER BY p.workspace_id,p.position").all(dateKey) as ExistingWeeklyItem[]).filter((item, index, all) => all.findIndex((candidate) => candidate.sourceKey === item.sourceKey) === index) }
  private nowMinusWeek(): number { return Date.now() - 7 * 86_400_000 }
}
