import type { PlanningRepository } from '../../application/planning/planning-service'
import type { CoachDatabase } from '../database/connection'
import type { AcademicOverview } from '../../shared/contracts/planning-contract'
import { academicEventPhase } from '../../application/planning/academic-time'

export class DrizzlePlanningRepository implements PlanningRepository {
  constructor(private readonly database: CoachDatabase) {}
  createDeadline(input: { id: string; workspaceId: string; title: string; dueAt: number; estimatedMinutes: number; masteryPercent: number | null; createdAt: number }): void { this.database.sqlite.prepare('INSERT INTO study_deadlines (id, workspace_id, title, due_at, estimated_minutes, mastery_percent, completed, created_at) VALUES (?, ?, ?, ?, ?, ?, 0, ?)').run(input.id, input.workspaceId, input.title, input.dueAt, input.estimatedMinutes, input.masteryPercent, input.createdAt) }
  addRoutineNote(input: { id: string; content: string; createdAt: number }): void { this.database.sqlite.prepare('INSERT INTO routine_notes (id, content, created_at) VALUES (?, ?, ?)').run(input.id, input.content, input.createdAt) }
  listRoutineNotes(): string[] { return (this.database.sqlite.prepare('SELECT content FROM routine_notes ORDER BY created_at DESC LIMIT 20').all() as Array<{ content: string }>).map((item) => item.content) }
  getWorkspaceName(workspaceId: string): string { return (this.database.sqlite.prepare('SELECT name FROM workspaces WHERE id = ?').get(workspaceId) as { name: string } | undefined)?.name ?? 'Workspace' }
  listWorkspaces(): Array<{ id: string; name: string; objective: string }> { return this.database.sqlite.prepare("SELECT id, name, objective FROM workspaces WHERE status = 'active'").all() as Array<{ id: string; name: string; objective: string }> }
  registerAcademicEvent(input: { id: string; deadlineId: string; workspaceId: string; type: 'exam' | 'assignment' | 'deadline'; title: string; dueAt: number; estimatedMinutes: number; masteryPercent: number | null; now: number }): void { this.database.sqlite.transaction(() => { this.database.sqlite.prepare('INSERT INTO academic_events (id, workspace_id, type, title, due_at, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)').run(input.id, input.workspaceId, input.type, input.title, input.dueAt, input.now, input.now); this.createDeadline({ id: input.deadlineId, workspaceId: input.workspaceId, title: input.title, dueAt: input.dueAt, estimatedMinutes: input.estimatedMinutes, masteryPercent: input.masteryPercent, createdAt: input.now }) })() }
  updateLatestAcademicEvent(workspaceId: string, type: 'exam' | 'assignment' | 'deadline', dueAt: number, now: number): boolean { const changed = this.database.sqlite.prepare('UPDATE academic_events SET due_at = ?, updated_at = ? WHERE id = (SELECT id FROM academic_events WHERE workspace_id = ? AND type = ? ORDER BY due_at DESC LIMIT 1)').run(dueAt, now, workspaceId, type).changes > 0; if (changed) this.database.sqlite.prepare('UPDATE study_deadlines SET due_at = ? WHERE id = (SELECT id FROM study_deadlines WHERE workspace_id = ? AND completed = 0 ORDER BY due_at DESC LIMIT 1)').run(dueAt, workspaceId); return changed }
  setAvailability(weekday: number, minutes: number, now: number): void { this.database.sqlite.prepare('INSERT INTO academic_availability (weekday, minutes, updated_at) VALUES (?, ?, ?) ON CONFLICT(weekday) DO UPDATE SET minutes=excluded.minutes, updated_at=excluded.updated_at').run(weekday, minutes, now) }
  getAcademicOverview(now: number): AcademicOverview { const events = (this.database.sqlite.prepare('SELECT e.id, e.workspace_id AS workspaceId, w.name AS workspaceName, e.type, e.title, e.due_at AS dueAt FROM academic_events e JOIN workspaces w ON w.id=e.workspace_id ORDER BY e.due_at').all() as Array<Omit<AcademicOverview['events'][number], 'phase'>>).map((event) => ({ ...event, phase: academicEventPhase(event.dueAt, now) })); const availability = this.database.sqlite.prepare('SELECT weekday, minutes FROM academic_availability ORDER BY weekday').all() as unknown as AcademicOverview['availability']; const workspaces = this.database.sqlite.prepare(`SELECT w.id AS workspaceId, w.name AS workspaceName, (SELECT topic_id FROM study_progress_events e WHERE e.workspace_id=w.id AND e.type='CHECKPOINT_ANSWERED' AND e.correct=0 ORDER BY e.created_at DESC LIMIT 1) AS difficulty, COALESCE((SELECT COUNT(*) FROM study_progress_events e WHERE e.workspace_id=w.id AND e.type='TOPIC_COMPLETED'),0) AS completedTopics, COALESCE((SELECT SUM(json_array_length(m.topics_json)) FROM roadmap_modules m JOIN roadmaps r ON r.id=m.roadmap_id WHERE r.workspace_id=w.id AND r.status='accepted'),0) AS totalTopics FROM workspaces w WHERE w.status='active' ORDER BY w.name`).all() as AcademicOverview['workspaces']; return { events, availability, workspaces, routine: this.listRoutineNotes() } }
  listPriorityInputs(): Array<{ workspaceId: string; title: string; dueAt: number; estimatedMinutes: number; masteryPercent: number | null; recentFocusSeconds: number }> { return this.database.sqlite.prepare(`SELECT d.workspace_id AS workspaceId, d.title, d.due_at AS dueAt, d.estimated_minutes AS estimatedMinutes, d.mastery_percent AS masteryPercent, COALESCE(SUM(CASE WHEN s.ended_at >= ? THEN s.focus_seconds ELSE 0 END),0) AS recentFocusSeconds FROM study_deadlines d JOIN workspaces w ON w.id = d.workspace_id LEFT JOIN study_sessions s ON s.workspace_id = d.workspace_id WHERE d.completed = 0 AND w.status = 'active' GROUP BY d.id`).all(this.nowMinusWeek()) as Array<{ workspaceId: string; title: string; dueAt: number; estimatedMinutes: number; masteryPercent: number | null; recentFocusSeconds: number }> }
  private nowMinusWeek(): number { return Date.now() - 7 * 86_400_000 }
}
