import type { RoadmapRepository } from '../../application/roadmaps/roadmap-service'
import type { Roadmap, RoadmapModule } from '../../shared/contracts/roadmap-contract'
import type { CoachDatabase } from '../database/connection'

export class DrizzleRoadmapRepository implements RoadmapRepository {
  constructor(private readonly database: CoachDatabase) {}
  findCurrent(workspaceId: string): Roadmap | null { const row = this.database.sqlite.prepare("SELECT id FROM roadmaps WHERE workspace_id = ? AND status != 'archived' ORDER BY version DESC LIMIT 1").get(workspaceId) as { id: string } | undefined; return row ? this.require(row.id) : null }
  nextVersion(workspaceId: string): number { return ((this.database.sqlite.prepare('SELECT MAX(version) AS version FROM roadmaps WHERE workspace_id = ?').get(workspaceId) as { version: number | null }).version ?? 0) + 1 }
  create(roadmap: Roadmap): Roadmap { this.database.sqlite.transaction(() => { this.database.sqlite.prepare("UPDATE roadmaps SET status = 'archived', updated_at = ? WHERE workspace_id = ? AND status = 'proposed'").run(roadmap.updatedAt, roadmap.workspaceId); this.database.sqlite.prepare('INSERT INTO roadmaps (id, workspace_id, title, status, generation_kind, version, provider_id, model_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(roadmap.id, roadmap.workspaceId, roadmap.title, roadmap.status, roadmap.generationKind, roadmap.version, roadmap.providerId, roadmap.modelId, roadmap.createdAt, roadmap.updatedAt); const insert = this.database.sqlite.prepare('INSERT INTO roadmap_modules (id, roadmap_id, title, objective, estimated_minutes, position, status, topics_json, outcomes_json, practice, completion_criteria_json, resources_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'); for (const module of roadmap.modules) insert.run(module.id, roadmap.id, module.title, module.objective, module.estimatedMinutes, module.position, module.status, JSON.stringify(module.topics), JSON.stringify(module.outcomes), module.practice, JSON.stringify(module.completionCriteria), JSON.stringify(module.resources)) })(); return this.require(roadmap.id) }
  accept(workspaceId: string, roadmapId: string, now: number): Roadmap { this.database.sqlite.transaction(() => { this.database.sqlite.prepare("UPDATE roadmaps SET status = 'archived', updated_at = ? WHERE workspace_id = ? AND status = 'accepted'").run(now, workspaceId); const result = this.database.sqlite.prepare("UPDATE roadmaps SET status = 'accepted', updated_at = ? WHERE id = ? AND workspace_id = ? AND status = 'proposed'").run(now, roadmapId, workspaceId); if (result.changes !== 1) throw new Error('Roadmap proposal not found'); this.database.sqlite.prepare("UPDATE roadmap_modules SET status = CASE WHEN position = 1 THEN 'active' ELSE status END WHERE roadmap_id = ?").run(roadmapId) })(); return this.require(roadmapId) }
  private require(id: string): Roadmap { const row = this.database.sqlite.prepare('SELECT id, workspace_id AS workspaceId, title, status, generation_kind AS generationKind, version, provider_id AS providerId, model_id AS modelId, created_at AS createdAt, updated_at AS updatedAt FROM roadmaps WHERE id = ?').get(id) as Omit<Roadmap, 'modules'> | undefined; if (!row) throw new Error('Roadmap not found'); const raw = this.database.sqlite.prepare('SELECT id, title, objective, estimated_minutes AS estimatedMinutes, position, status, topics_json AS topicsJson, outcomes_json AS outcomesJson, practice, completion_criteria_json AS completionCriteriaJson, resources_json AS resourcesJson FROM roadmap_modules WHERE roadmap_id = ? ORDER BY position').all(id) as Array<Omit<RoadmapModule, 'topics' | 'outcomes' | 'completionCriteria' | 'resources'> & { topicsJson: string; outcomesJson: string; completionCriteriaJson: string; resourcesJson: string }>; return { ...row, modules: raw.map(({ topicsJson, outcomesJson, completionCriteriaJson, resourcesJson, ...module }) => ({ ...module, topics: JSON.parse(topicsJson) as string[], outcomes: JSON.parse(outcomesJson) as string[], completionCriteria: JSON.parse(completionCriteriaJson) as string[], resources: JSON.parse(resourcesJson) as RoadmapModule['resources'] })) } }
}
