import type { RoadmapRepository } from '../../application/roadmaps/roadmap-service'
import { roadmapModuleProposalSchema, roadmapResourceSchema, type LearningPathState, type Roadmap, type RoadmapModule, type RoadmapRebuildImpact, type RoadmapRebuildPreview } from '../../shared/contracts/roadmap-contract'
import type { CoachDatabase } from '../database/connection'

export class DrizzleRoadmapRepository implements RoadmapRepository {
  constructor(private readonly database: CoachDatabase) {}
  findCurrent(workspaceId: string): Roadmap | null { const row = this.database.sqlite.prepare("SELECT id FROM roadmaps WHERE workspace_id = ? AND status = 'accepted' ORDER BY version DESC LIMIT 1").get(workspaceId) as { id: string } | undefined; return row ? this.require(row.id) : null }
  nextVersion(workspaceId: string): number { return ((this.database.sqlite.prepare('SELECT MAX(version) AS version FROM roadmaps WHERE workspace_id = ?').get(workspaceId) as { version: number | null }).version ?? 0) + 1 }
  activate(roadmap: Roadmap): Roadmap { if (!roadmap.modules.length || roadmap.modules.some((module) => !module.topics.length)) throw new Error('Roadmap must contain modules with topics'); this.database.sqlite.transaction(() => { this.insert({ ...roadmap, status: 'accepted' }); this.database.sqlite.prepare("UPDATE roadmaps SET status = 'archived', updated_at = ? WHERE workspace_id = ? AND status = 'accepted' AND id <> ?").run(roadmap.updatedAt, roadmap.workspaceId, roadmap.id); this.database.sqlite.prepare("INSERT INTO workspace_learning_path_state (workspace_id,status,active_roadmap_id,last_attempt_at,retry_after,last_error_code,updated_at) VALUES (?,'ready',?,?,NULL,NULL,?) ON CONFLICT(workspace_id) DO UPDATE SET status='ready',active_roadmap_id=excluded.active_roadmap_id,last_attempt_at=excluded.last_attempt_at,retry_after=NULL,last_error_code=NULL,updated_at=excluded.updated_at").run(roadmap.workspaceId, roadmap.id, roadmap.updatedAt, roadmap.updatedAt) })(); return this.require(roadmap.id) }
  create(roadmap: Roadmap): Roadmap { this.insert(roadmap); return this.require(roadmap.id) }
  accept(workspaceId: string, roadmapId: string, now: number): Roadmap { const proposal = this.require(roadmapId); if (proposal.workspaceId !== workspaceId || proposal.status !== 'proposed') throw new Error('Roadmap proposal not found'); if (!proposal.modules.length || proposal.modules.some((module) => !module.topics.length)) throw new Error('Roadmap must contain modules with topics'); this.database.sqlite.transaction(() => { this.database.sqlite.prepare("UPDATE roadmaps SET status = 'archived', updated_at = ? WHERE workspace_id = ? AND status = 'accepted'").run(now, workspaceId); const result = this.database.sqlite.prepare("UPDATE roadmaps SET status = 'accepted', updated_at = ? WHERE id = ? AND workspace_id = ? AND status = 'proposed'").run(now, roadmapId, workspaceId); if (result.changes !== 1) throw new Error('Roadmap proposal not found'); this.database.sqlite.prepare("UPDATE roadmap_modules SET status = CASE WHEN position = 1 THEN 'active' ELSE status END WHERE roadmap_id = ?").run(roadmapId); this.database.sqlite.prepare("INSERT INTO workspace_learning_path_state (workspace_id,status,active_roadmap_id,last_attempt_at,retry_after,last_error_code,updated_at) VALUES (?,'ready',?,?,NULL,NULL,?) ON CONFLICT(workspace_id) DO UPDATE SET status='ready',active_roadmap_id=excluded.active_roadmap_id,retry_after=NULL,last_error_code=NULL,updated_at=excluded.updated_at").run(workspaceId, roadmapId, now, now) })(); return this.require(roadmapId) }
  progressedTopicIds(workspaceId: string): string[] { const ids = new Set<string>(); const progress = this.database.sqlite.prepare('SELECT topic_statuses_json AS value FROM study_progress WHERE workspace_id = ?').get(workspaceId) as { value: string } | undefined; if (progress) try { for (const [id, status] of Object.entries(JSON.parse(progress.value) as Record<string, string>)) if (status !== 'NOT_STARTED') ids.add(id) } catch {} for (const row of this.database.sqlite.prepare('SELECT topic_id AS id FROM topic_learning_states WHERE workspace_id = ? AND evidence_count > 0').all(workspaceId) as Array<{ id: string }>) ids.add(row.id); return [...ids] }
  saveRebuildPreview(preview: RoadmapRebuildPreview): RoadmapRebuildPreview { this.database.sqlite.transaction(() => { this.database.sqlite.prepare("UPDATE roadmap_rebuild_previews SET status = 'stale', resolved_at = ? WHERE workspace_id = ? AND status = 'pending'").run(preview.createdAt, preview.workspaceId); this.database.sqlite.prepare('INSERT INTO roadmap_rebuild_previews (id, workspace_id, current_roadmap_id, proposal_json, material_ids_json, impact_json, status, applied_roadmap_id, created_at, resolved_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(preview.id, preview.workspaceId, preview.currentRoadmapId, JSON.stringify({ title: preview.title, modules: preview.modules }), JSON.stringify(preview.materialIds), JSON.stringify(preview.impact), preview.status, preview.appliedRoadmapId, preview.createdAt, preview.resolvedAt) })(); return preview }
  findLatestRebuildPreview(workspaceId: string): RoadmapRebuildPreview | null { const row = this.database.sqlite.prepare("SELECT id FROM roadmap_rebuild_previews WHERE workspace_id = ? AND status = 'pending' ORDER BY created_at DESC, rowid DESC LIMIT 1").get(workspaceId) as { id: string } | undefined; return row ? this.findRebuildPreview(workspaceId, row.id) : null }
  findRebuildPreview(workspaceId: string, previewId: string): RoadmapRebuildPreview | null { const row = this.database.sqlite.prepare('SELECT id, workspace_id AS workspaceId, current_roadmap_id AS currentRoadmapId, proposal_json AS proposalJson, material_ids_json AS materialIdsJson, impact_json AS impactJson, status, applied_roadmap_id AS appliedRoadmapId, created_at AS createdAt, resolved_at AS resolvedAt FROM roadmap_rebuild_previews WHERE id = ? AND workspace_id = ?').get(previewId, workspaceId) as { id: string; workspaceId: string; currentRoadmapId: string; proposalJson: string; materialIdsJson: string; impactJson: string; status: RoadmapRebuildPreview['status']; appliedRoadmapId: string | null; createdAt: number; resolvedAt: number | null } | undefined; if (!row) return null; const proposal = JSON.parse(row.proposalJson) as { title: string; modules: RoadmapModule[] }; return { id: row.id, workspaceId: row.workspaceId, currentRoadmapId: row.currentRoadmapId, title: proposal.title, modules: proposal.modules.map((module) => ({ ...module, ...roadmapModuleProposalSchema.parse(module) })), materialIds: JSON.parse(row.materialIdsJson) as string[], impact: JSON.parse(row.impactJson) as RoadmapRebuildImpact, status: row.status, appliedRoadmapId: row.appliedRoadmapId, createdAt: row.createdAt, resolvedAt: row.resolvedAt } }
  applyRebuildPreview(preview: RoadmapRebuildPreview, now: number): Roadmap {
    if (preview.status === 'applied' && preview.appliedRoadmapId) return this.require(preview.appliedRoadmapId)
    if (preview.status !== 'pending') throw new Error('Roadmap rebuild preview is no longer applicable')
    const current = this.findCurrent(preview.workspaceId)
    if (!current || current.id !== preview.currentRoadmapId) { this.database.sqlite.prepare("UPDATE roadmap_rebuild_previews SET status = 'stale', resolved_at = ? WHERE id = ? AND status = 'pending'").run(now, preview.id); throw new Error('Roadmap changed after preview; create a new preview') }
    const roadmap: Roadmap = { id: crypto.randomUUID(), workspaceId: preview.workspaceId, title: preview.title, status: 'accepted', generationKind: 'ai_generated', version: this.nextVersion(preview.workspaceId), providerId: current.providerId, modelId: current.modelId, modules: preview.modules, createdAt: now, updatedAt: now }
    this.database.sqlite.transaction(() => {
      this.activate(roadmap)
      const progress = this.database.sqlite.prepare('SELECT current_module_id AS moduleId, current_topic_id AS topicId, topic_statuses_json AS statuses, lesson_positions_json AS positions, checkpoint_states_json AS checkpoints FROM study_progress WHERE workspace_id = ?').get(preview.workspaceId) as { moduleId: string; topicId: string; statuses: string; positions: string; checkpoints: string } | undefined
      if (progress) {
        const valid = new Set(roadmap.modules.flatMap((module) => module.topics.map((topic) => `${module.id}:${topic}`)))
        const statuses = Object.fromEntries(Object.entries(JSON.parse(progress.statuses) as Record<string, string>).filter(([id]) => valid.has(id)))
        const keepCurrent = valid.has(progress.topicId)
        const first = roadmap.modules.find((module) => module.status !== 'locked') ?? roadmap.modules[0]!
        const topicId = keepCurrent ? progress.topicId : `${first.id}:${first.topics[0]}`
        const moduleId = keepCurrent ? progress.moduleId : first.id
        const positions = Object.fromEntries(Object.entries(JSON.parse(progress.positions) as Record<string, unknown>).filter(([id]) => valid.has(id)))
        const checkpoints = {}
        this.database.sqlite.prepare('UPDATE study_progress SET roadmap_id = ?, current_module_id = ?, current_topic_id = ?, current_lesson_id = ?, current_checkpoint_id = NULL, topic_statuses_json = ?, lesson_positions_json = ?, checkpoint_states_json = ?, updated_at = ? WHERE workspace_id = ?').run(roadmap.id, moduleId, topicId, `${topicId}:lesson`, JSON.stringify(statuses), JSON.stringify(positions), JSON.stringify(checkpoints), now, preview.workspaceId)
      }
      const resolved = this.database.sqlite.prepare("UPDATE roadmap_rebuild_previews SET status = 'applied', applied_roadmap_id = ?, resolved_at = ? WHERE id = ? AND workspace_id = ? AND status = 'pending'").run(roadmap.id, now, preview.id, preview.workspaceId)
      if (resolved.changes !== 1) throw new Error('Roadmap rebuild preview application conflict')
    })()
    return this.require(roadmap.id)
  }
  getLearningPathState(workspaceId: string): LearningPathState | null { return (this.database.sqlite.prepare('SELECT workspace_id AS workspaceId,status,active_roadmap_id AS activeRoadmapId,last_attempt_at AS lastAttemptAt,retry_after AS retryAfter,last_error_code AS lastErrorCode,updated_at AS updatedAt FROM workspace_learning_path_state WHERE workspace_id = ?').get(workspaceId) as LearningPathState | undefined) ?? null }
  setLearningPathState(state: LearningPathState): LearningPathState { this.database.sqlite.prepare('INSERT INTO workspace_learning_path_state (workspace_id,status,active_roadmap_id,last_attempt_at,retry_after,last_error_code,updated_at) VALUES (?,?,?,?,?,?,?) ON CONFLICT(workspace_id) DO UPDATE SET status=excluded.status,active_roadmap_id=excluded.active_roadmap_id,last_attempt_at=excluded.last_attempt_at,retry_after=excluded.retry_after,last_error_code=excluded.last_error_code,updated_at=excluded.updated_at').run(state.workspaceId, state.status, state.activeRoadmapId, state.lastAttemptAt, state.retryAfter, state.lastErrorCode, state.updatedAt); return this.getLearningPathState(state.workspaceId)! }
  recoverInterrupted(workspaceId: string, now: number, staleBefore: number, retryAfter: number): LearningPathState | null { const state = this.getLearningPathState(workspaceId); if (state?.status !== 'generating' || state.updatedAt > staleBefore) return state; return this.setLearningPathState({ ...state, status: 'failed_retryable', retryAfter, lastErrorCode: 'INTERRUPTED', updatedAt: now }) }
  tryStartGeneration(workspaceId: string, activeRoadmapId: string | null, now: number, staleBefore: number): boolean { const result = this.database.sqlite.prepare("INSERT INTO workspace_learning_path_state (workspace_id,status,active_roadmap_id,last_attempt_at,retry_after,last_error_code,updated_at) VALUES (?,'generating',?,?,NULL,NULL,?) ON CONFLICT(workspace_id) DO UPDATE SET status='generating',active_roadmap_id=excluded.active_roadmap_id,last_attempt_at=excluded.last_attempt_at,retry_after=NULL,last_error_code=NULL,updated_at=excluded.updated_at WHERE workspace_learning_path_state.status <> 'generating' OR workspace_learning_path_state.updated_at <= ?").run(workspaceId, activeRoadmapId, now, now, staleBefore); return result.changes === 1 }
  listWaitingForProvider(): string[] { return (this.database.sqlite.prepare("SELECT workspace_id AS workspaceId FROM workspace_learning_path_state WHERE status = 'waiting_for_provider'").all() as Array<{ workspaceId: string }>).map((row) => row.workspaceId) }
  private insert(roadmap: Roadmap): void { this.database.sqlite.prepare('INSERT INTO roadmaps (id, workspace_id, title, status, generation_kind, version, provider_id, model_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(roadmap.id, roadmap.workspaceId, roadmap.title, roadmap.status, roadmap.generationKind, roadmap.version, roadmap.providerId, roadmap.modelId, roadmap.createdAt, roadmap.updatedAt); const insert = this.database.sqlite.prepare('INSERT INTO roadmap_modules (id, roadmap_id, title, objective, estimated_minutes, position, status, topics_json, outcomes_json, practice, completion_criteria_json, resources_json) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'); for (const module of roadmap.modules) insert.run(module.id, roadmap.id, module.title, module.objective, module.estimatedMinutes, module.position, module.status, JSON.stringify(module.topics), JSON.stringify(module.outcomes), module.practice, JSON.stringify(module.completionCriteria), JSON.stringify(module.resources)) }
  private require(id: string): Roadmap { const row = this.database.sqlite.prepare('SELECT id, workspace_id AS workspaceId, title, status, generation_kind AS generationKind, version, provider_id AS providerId, model_id AS modelId, created_at AS createdAt, updated_at AS updatedAt FROM roadmaps WHERE id = ?').get(id) as Omit<Roadmap, 'modules'> | undefined; if (!row) throw new Error('Roadmap not found'); const raw = this.database.sqlite.prepare('SELECT id, title, objective, estimated_minutes AS estimatedMinutes, position, status, topics_json AS topicsJson, outcomes_json AS outcomesJson, practice, completion_criteria_json AS completionCriteriaJson, resources_json AS resourcesJson FROM roadmap_modules WHERE roadmap_id = ? ORDER BY position').all(id) as Array<Omit<RoadmapModule, 'topics' | 'outcomes' | 'completionCriteria' | 'resources'> & { topicsJson: string; outcomesJson: string; completionCriteriaJson: string; resourcesJson: string }>; return { ...row, modules: raw.map(({ topicsJson, outcomesJson, completionCriteriaJson, resourcesJson, ...module }) => ({ ...module, topics: JSON.parse(topicsJson) as string[], outcomes: JSON.parse(outcomesJson) as string[], completionCriteria: JSON.parse(completionCriteriaJson) as string[], resources: (JSON.parse(resourcesJson) as unknown[]).map((resource) => roadmapResourceSchema.parse(resource)) })) } }
}
