import type { WorkspaceProvisioningRepository } from '../../application/workspaces/workspace-provisioning-service'
import type { WorkspaceProvisioningState } from '../../shared/contracts/workspace-contract'
import type { CoachDatabase } from '../database/connection'

type Row = Omit<WorkspaceProvisioningState, 'materialIds' | 'readinessState' | 'backgroundPending' | 'legacyState'> & { materialIdsJson: string; readinessState: 'provisioning' | 'usable' | 'fully_provisioned' | null; backgroundPending: number; legacyState: 'legacy_accessible' | null }
const select = `SELECT p.workspace_id AS workspaceId,p.status,p.stage,p.material_ids_json AS materialIdsJson,p.attempt_count AS attemptCount,p.created_at AS createdAt,p.started_at AS startedAt,p.stage_updated_at AS stageUpdatedAt,p.completed_at AS completedAt,p.retry_after AS retryAfter,p.error_code AS errorCode,p.error_message AS errorMessage,r.state AS readinessState,r.legacy_state AS legacyState,COALESCE((SELECT COUNT(*) FROM content_jobs j WHERE j.workspace_id=p.workspace_id AND j.revision=r.revision AND j.status IN ('pending','queued','generating')),0) AS backgroundPending FROM workspace_provisioning p LEFT JOIN workspace_content_revisions r ON r.workspace_id=p.workspace_id`
function map(row: Row): WorkspaceProvisioningState { const { materialIdsJson, readinessState, ...rest } = row; return { ...rest, materialIds: JSON.parse(materialIdsJson) as string[], readinessState: readinessState?.toUpperCase() as WorkspaceProvisioningState['readinessState'] ?? 'PROVISIONING' } }

export class SqliteWorkspaceProvisioningRepository implements WorkspaceProvisioningRepository {
  constructor(private readonly database: CoachDatabase) {}
  find(workspaceId: string): WorkspaceProvisioningState | null { const row = this.database.sqlite.prepare(`${select} WHERE p.workspace_id = ?`).get(workspaceId) as Row | undefined; return row ? map(row) : null }
  save(state: WorkspaceProvisioningState): WorkspaceProvisioningState { this.database.sqlite.prepare('INSERT INTO workspace_provisioning (workspace_id,status,stage,material_ids_json,attempt_count,created_at,started_at,stage_updated_at,completed_at,retry_after,error_code,error_message) VALUES (?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(workspace_id) DO UPDATE SET status=excluded.status,stage=excluded.stage,material_ids_json=excluded.material_ids_json,attempt_count=excluded.attempt_count,started_at=excluded.started_at,stage_updated_at=excluded.stage_updated_at,completed_at=excluded.completed_at,retry_after=excluded.retry_after,error_code=excluded.error_code,error_message=excluded.error_message').run(state.workspaceId, state.status, state.stage, JSON.stringify(state.materialIds), state.attemptCount, state.createdAt, state.startedAt, state.stageUpdatedAt, state.completedAt, state.retryAfter, state.errorCode, state.errorMessage); return this.find(state.workspaceId)! }
  listResumable(now: number): string[] { return (this.database.sqlite.prepare("SELECT workspace_id AS workspaceId FROM workspace_provisioning WHERE status IN ('queued','running','failed_retryable','waiting_for_provider') AND (retry_after IS NULL OR retry_after <= ?)").all(now) as Array<{ workspaceId: string }>).map((row) => row.workspaceId) }
  removeDraft(workspaceId: string): boolean { return this.database.sqlite.transaction(() => { const state = this.find(workspaceId); if (!state || state.status !== 'draft') return false; return this.database.sqlite.prepare('DELETE FROM workspaces WHERE id = ?').run(workspaceId).changes === 1 })() }
}
