import type { AcademicSubjectContextRepository } from '../../application/workspaces/academic-subject-context'
import type { AcademicSubjectContext, AcademicSubjectDeclaration } from '../../shared/contracts/academic-subject-context-contract'
import type { CoachDatabase } from '../database/connection'

type Row = { subject: string; declaredLevel: AcademicSubjectContext['declaredLevel']; declaredKnowledgeJson: string; declaredDifficultiesJson: string; goalsJson: string; sourceEvidenceJson: string; observedStrengthsJson: string; observedDifficultiesJson: string; misconceptionsJson: string; masteredConceptsJson: string; reviewConceptsJson: string; lastConsolidatedAt: number | null; createdAt: number; updatedAt: number }
const columns = 'subject, declared_level AS declaredLevel, declared_knowledge_json AS declaredKnowledgeJson, declared_difficulties_json AS declaredDifficultiesJson, goals_json AS goalsJson, source_evidence_json AS sourceEvidenceJson, observed_strengths_json AS observedStrengthsJson, observed_difficulties_json AS observedDifficultiesJson, misconceptions_json AS misconceptionsJson, mastered_concepts_json AS masteredConceptsJson, review_concepts_json AS reviewConceptsJson, last_consolidated_at AS lastConsolidatedAt, created_at AS createdAt, updated_at AS updatedAt'
function map(row: Row): AcademicSubjectContext { return { subject: row.subject, declaredLevel: row.declaredLevel, declaredKnowledge: JSON.parse(row.declaredKnowledgeJson), declaredDifficulties: JSON.parse(row.declaredDifficultiesJson), goals: JSON.parse(row.goalsJson), sourceEvidence: JSON.parse(row.sourceEvidenceJson), observedStrengths: JSON.parse(row.observedStrengthsJson), observedDifficulties: JSON.parse(row.observedDifficultiesJson), misconceptions: JSON.parse(row.misconceptionsJson), masteredConcepts: JSON.parse(row.masteredConceptsJson), reviewConcepts: JSON.parse(row.reviewConceptsJson), lastConsolidatedAt: row.lastConsolidatedAt, createdAt: row.createdAt, updatedAt: row.updatedAt } }

export class SqliteAcademicSubjectContextRepository implements AcademicSubjectContextRepository {
  constructor(private readonly database: CoachDatabase) {}
  find(subject: string): AcademicSubjectContext | null { const row = this.database.sqlite.prepare(`SELECT ${columns} FROM academic_subject_contexts WHERE subject = ?`).get(subject) as Row | undefined; return row ? map(row) : null }
  list(): AcademicSubjectContext[] { return (this.database.sqlite.prepare(`SELECT ${columns} FROM academic_subject_contexts ORDER BY updated_at DESC`).all() as Row[]).map(map) }
  upsert(input: AcademicSubjectDeclaration, now: number): AcademicSubjectContext {
    this.database.sqlite.prepare('INSERT INTO academic_subject_contexts (subject, declared_level, declared_knowledge_json, declared_difficulties_json, goals_json, source_evidence_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(subject) DO UPDATE SET declared_level=excluded.declared_level, declared_knowledge_json=excluded.declared_knowledge_json, declared_difficulties_json=excluded.declared_difficulties_json, goals_json=excluded.goals_json, source_evidence_json=excluded.source_evidence_json, updated_at=excluded.updated_at').run(input.subject, input.declaredLevel ?? null, JSON.stringify(input.declaredKnowledge), JSON.stringify(input.declaredDifficulties), JSON.stringify(input.goals), JSON.stringify(input.sourceEvidence), now, now)
    return this.find(input.subject)!
  }
  replace(input: AcademicSubjectDeclaration, now: number): AcademicSubjectContext { const current = this.find(input.subject); this.database.sqlite.prepare('INSERT INTO academic_subject_contexts (subject, declared_level, declared_knowledge_json, declared_difficulties_json, goals_json, source_evidence_json, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(subject) DO UPDATE SET declared_level = excluded.declared_level, declared_knowledge_json = excluded.declared_knowledge_json, declared_difficulties_json = excluded.declared_difficulties_json, goals_json = excluded.goals_json, source_evidence_json = excluded.source_evidence_json, updated_at = excluded.updated_at').run(input.subject, input.declaredLevel ?? null, JSON.stringify(input.declaredKnowledge), JSON.stringify(input.declaredDifficulties), JSON.stringify(input.goals), JSON.stringify(input.sourceEvidence), current?.createdAt ?? now, now); return this.find(input.subject)! }
}
