import { studyLessonContentSchema, type PersistedStudyLesson } from '../../shared/contracts/study-lesson-contract'
import type { StudyLessonRepository } from '../../application/study-lessons/study-lesson-service'
import type { CoachDatabase } from '../database/connection'

type LessonRow = { id: string; generationKind: PersistedStudyLesson['generationKind']; workspaceId: string; roadmapId: string; moduleId: string; topicId: string; contentJson: string; providerId: string | null; modelId: string | null; createdAt: number }
function map(row: LessonRow): PersistedStudyLesson { return { ...studyLessonContentSchema.parse(JSON.parse(row.contentJson)), id: row.id, generationKind: row.generationKind, workspaceId: row.workspaceId, roadmapId: row.roadmapId, moduleId: row.moduleId, topicId: row.topicId, providerId: row.providerId, modelId: row.modelId, createdAt: row.createdAt } }
export class SqliteStudyLessonRepository implements StudyLessonRepository {
  constructor(private readonly database: CoachDatabase) {}
  find(roadmapId: string, topicId: string): PersistedStudyLesson | null { const row = this.database.sqlite.prepare('SELECT id, generation_kind AS generationKind, workspace_id AS workspaceId, roadmap_id AS roadmapId, module_id AS moduleId, topic_id AS topicId, content_json AS contentJson, provider_id AS providerId, model_id AS modelId, created_at AS createdAt FROM study_lessons WHERE roadmap_id = ? AND topic_id = ?').get(roadmapId, topicId) as LessonRow | undefined; return row ? map(row) : null }
  create(lesson: PersistedStudyLesson): PersistedStudyLesson { this.database.sqlite.prepare('INSERT OR IGNORE INTO study_lessons (id, workspace_id, roadmap_id, module_id, topic_id, generation_kind, content_json, provider_id, model_id, created_at, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)').run(lesson.id, lesson.workspaceId, lesson.roadmapId, lesson.moduleId, lesson.topicId, lesson.generationKind, JSON.stringify({ title: lesson.title, level: lesson.level, objective: lesson.objective, blocks: lesson.blocks }), lesson.providerId, lesson.modelId, lesson.createdAt, lesson.createdAt); return this.find(lesson.roadmapId, lesson.topicId) ?? lesson }
  replace(lesson: PersistedStudyLesson): PersistedStudyLesson { this.database.sqlite.prepare('DELETE FROM study_lessons WHERE roadmap_id = ? AND topic_id = ?').run(lesson.roadmapId, lesson.topicId); return this.create(lesson) }
}
