import type { ExerciseRepository, PrivateExercise } from '../../application/exercises/exercise-service'
import { applyLearningEvidence, emptyTopicLearningState, type TopicLearningState } from '../../application/study-progress/topic-learning'
import { exerciseExecutionSchema, exerciseSetSchema, exerciseSummarySchema, publicExerciseContextSchema, publicExerciseTestSchema, type ExerciseExecution, type ExerciseSet, type PublicExerciseContext } from '../../shared/contracts/exercise-contract'
import type { CoachDatabase } from '../database/connection'
import { EXERCISE_DATA_INVALID, validExerciseData } from '../database/exercise-data-repair'
import type { LearningEvidenceRecorder } from '../../shared/contracts/learning-evidence-contract'

type SetRow = { id: string; workspaceId: string; roadmapId: string; moduleId: string; topicId: string; lessonId: string; status: ExerciseSet['status']; retryAfter: number | null; lastErrorCode: string | null; updatedAt: number }
type ExerciseRow = { id: string; setId: string; workspaceId: string; topicId: string; position: number; kind: PrivateExercise['kind']; difficulty: PrivateExercise['difficulty']; title: string; statement: string; inputDescription: string; outputDescription: string; language: PrivateExercise['language']; starterCode: string; predictionPrompt: string | null; codeToObserve: string | null; requiredForTopicCompletion: number; publicTestsJson: string; privateTestsJson: string; referenceSolution: string | null; expectedPrediction: string | null; hint: string }
type ProgressRow = { exerciseId: string; status: 'not_started' | 'in_progress' | 'passed'; currentCode: string; attempts: number; lastRunJson: string | null; lastSubmissionJson: string | null; passedTests: number; totalTests: number; helpUsed: number; firstTrySuccess: number; helpCount: number; passedAt: number | null; updatedAt: number }
const setColumns = 'id, workspace_id AS workspaceId, roadmap_id AS roadmapId, module_id AS moduleId, topic_id AS topicId, lesson_id AS lessonId, status, retry_after AS retryAfter, last_error_code AS lastErrorCode, updated_at AS updatedAt'
const exerciseColumns = 'e.id, e.set_id AS setId, s.workspace_id AS workspaceId, s.topic_id AS topicId, e.position, e.kind, e.difficulty, e.title, e.statement, e.input_description AS inputDescription, e.output_description AS outputDescription, e.language, e.starter_code AS starterCode, e.prediction_prompt AS predictionPrompt, e.code_to_observe AS codeToObserve, e.required_for_topic_completion AS requiredForTopicCompletion, e.public_tests_json AS publicTestsJson, e.private_tests_json AS privateTestsJson, e.reference_solution AS referenceSolution, e.expected_prediction AS expectedPrediction, e.hint'

function privateExercise(row: ExerciseRow): PrivateExercise { return { id: row.id, setId: row.setId, workspaceId: row.workspaceId, topicId: row.topicId, position: row.position, kind: row.kind, difficulty: row.difficulty, title: row.title, statement: row.statement, inputDescription: row.inputDescription, outputDescription: row.outputDescription, language: row.language, starterCode: row.starterCode, predictionPrompt: row.predictionPrompt, codeToObserve: row.codeToObserve, requiredForTopicCompletion: Boolean(row.requiredForTopicCompletion), publicTests: publicExerciseTestSchema.array().parse(JSON.parse(row.publicTestsJson)), hiddenTests: publicExerciseTestSchema.array().parse(JSON.parse(row.privateTestsJson)), referenceSolution: row.referenceSolution, expectedPrediction: row.expectedPrediction, hint: row.hint } }
function summary(value: string | null) { return value ? exerciseSummarySchema.parse(JSON.parse(value)) : null }
function aggregate(value: string | null) { const result=summary(value); if(!result)return null; const {compileDiagnostics:_compileDiagnostics,...safe}=result; return safe }
function publicExercise(row: ExerciseRow): ExerciseSet['exercises'][number] { const { hiddenTests: _hiddenTests, referenceSolution: _referenceSolution, expectedPrediction: _expectedPrediction, hint: _hint, setId: _setId, workspaceId: _workspaceId, topicId: _topicId, ...safe } = privateExercise(row); return safe }
function readLearningState(database: CoachDatabase, workspaceId: string, topicId: string, now: number): TopicLearningState { const row = database.sqlite.prepare('SELECT workspace_id AS workspaceId, topic_id AS topicId, evidence_count AS evidenceCount, assessments, correct_first_try AS correctFirstTry, correct_after_help AS correctAfterHelp, incorrect, hints_used AS hintsUsed, reinforcement_events AS reinforcementEvents, exercises_completed AS exercisesCompleted, lessons_completed AS lessonsCompleted, difficulty_level AS difficultyLevel, mastery_estimate AS masteryEstimate, confidence, needs_review AS needsReview, last_practiced_at AS lastPracticedAt, last_assessed_at AS lastAssessedAt, reasons_json AS reasonsJson, updated_at AS updatedAt FROM topic_learning_states WHERE workspace_id = ? AND topic_id = ?').get(workspaceId, topicId) as (Omit<TopicLearningState, 'reasons'> & { reasonsJson: string }) | undefined; return row ? { ...row, needsReview: Boolean(row.needsReview), reasons: JSON.parse(row.reasonsJson) as string[] } : emptyTopicLearningState(workspaceId, topicId, now) }
function writeLearningState(database: CoachDatabase, state: TopicLearningState): void { database.sqlite.prepare(`INSERT INTO topic_learning_states (workspace_id, topic_id, evidence_count, assessments, correct_first_try, correct_after_help, incorrect, hints_used, reinforcement_events, exercises_completed, lessons_completed, difficulty_level, mastery_estimate, confidence, needs_review, last_practiced_at, last_assessed_at, reasons_json, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT(workspace_id, topic_id) DO UPDATE SET evidence_count=excluded.evidence_count,assessments=excluded.assessments,correct_first_try=excluded.correct_first_try,correct_after_help=excluded.correct_after_help,incorrect=excluded.incorrect,hints_used=excluded.hints_used,reinforcement_events=excluded.reinforcement_events,exercises_completed=excluded.exercises_completed,lessons_completed=excluded.lessons_completed,difficulty_level=excluded.difficulty_level,mastery_estimate=excluded.mastery_estimate,confidence=excluded.confidence,needs_review=excluded.needs_review,last_practiced_at=excluded.last_practiced_at,last_assessed_at=excluded.last_assessed_at,reasons_json=excluded.reasons_json,updated_at=excluded.updated_at`).run(state.workspaceId, state.topicId, state.evidenceCount, state.assessments, state.correctFirstTry, state.correctAfterHelp, state.incorrect, state.hintsUsed, state.reinforcementEvents, state.exercisesCompleted, state.lessonsCompleted, state.difficultyLevel, state.masteryEstimate, state.confidence, Number(state.needsReview), state.lastPracticedAt, state.lastAssessedAt, JSON.stringify(state.reasons), state.updatedAt) }

export class SqliteExerciseRepository implements ExerciseRepository {
  constructor(private readonly database: CoachDatabase, private readonly now = Date.now, private readonly evidenceRecorder?: LearningEvidenceRecorder) {}
  findSet(workspaceId: string, topicId: string): ExerciseSet | null {
    let row = this.database.sqlite.prepare(`SELECT ${setColumns} FROM exercise_sets WHERE workspace_id = ? AND topic_id = ?`).get(workspaceId, topicId) as SetRow | undefined
    if (!row) return null
    const allRows = this.database.sqlite.prepare(`SELECT ${exerciseColumns} FROM exercises e JOIN exercise_sets s ON s.id=e.set_id WHERE e.set_id = ? ORDER BY e.position`).all(row.id) as ExerciseRow[]
    const validRows = allRows.filter((item) => { try { return validExerciseData(item) && Boolean(publicExercise(item)) } catch { return false } })
    const rows = this.database.sqlite.prepare('SELECT exercise_id AS exerciseId, status, current_code AS currentCode, attempts, last_run_json AS lastRunJson, last_submission_json AS lastSubmissionJson, passed_tests AS passedTests, total_tests AS totalTests, help_used AS helpUsed, first_try_success AS firstTrySuccess, help_count AS helpCount, passed_at AS passedAt, updated_at AS updatedAt FROM exercise_progress WHERE workspace_id = ? AND exercise_id IN (SELECT id FROM exercises WHERE set_id = ?) ORDER BY exercise_id').all(workspaceId, row.id) as ProgressRow[]
    const validIds = new Set(validRows.map((item) => item.id))
    const progress = rows.flatMap(({ lastRunJson, lastSubmissionJson, ...item }) => {
      if (!validIds.has(item.exerciseId)) return []
      try { return [{ ...item, lastRun: summary(lastRunJson), lastSubmission: summary(lastSubmissionJson), helpUsed: Boolean(item.helpUsed), firstTrySuccess: Boolean(item.firstTrySuccess) }] } catch { return [] }
    })
    const corrupt = validRows.length !== allRows.length || progress.length !== rows.filter((item) => validIds.has(item.exerciseId)).length
    if (corrupt && row.status === 'ready') {
      const now = this.now()
      const retryAfter = now + 5 * 60_000
      this.database.sqlite.prepare("UPDATE exercise_sets SET status='failed_retryable',retry_after=?,last_error_code=?,updated_at=? WHERE id=? AND status='ready'").run(retryAfter, EXERCISE_DATA_INVALID, now, row.id)
      row = { ...row, status: 'failed_retryable', retryAfter, lastErrorCode: EXERCISE_DATA_INVALID, updatedAt: now }
    }
    const exercises = validRows.map(publicExercise)
    return exerciseSetSchema.parse({ ...row, exercises, progress })
  }
  findPrivateExercise(workspaceId: string, exerciseId: string): PrivateExercise | null { const row = this.database.sqlite.prepare(`SELECT ${exerciseColumns} FROM exercises e JOIN exercise_sets s ON s.id=e.set_id WHERE e.id = ? AND s.workspace_id = ? AND s.status = 'ready'`).get(exerciseId, workspaceId) as ExerciseRow | undefined; return row ? privateExercise(row) : null }
  findPublicContext(workspaceId: string, exerciseId: string): PublicExerciseContext | null { const row = this.database.sqlite.prepare(`SELECT e.id AS exerciseId,s.roadmap_id AS roadmapId,s.module_id AS moduleId,s.topic_id AS topicId,e.kind,e.title,e.statement,e.language,p.current_code AS currentCode,p.last_run_json AS lastRunJson,p.last_submission_json AS lastSubmissionJson,p.passed_tests AS passedTests,p.total_tests AS totalTests,p.attempts AS attemptCount,p.help_used AS helpUsed,p.status AS progressStatus FROM exercises e JOIN exercise_sets s ON s.id=e.set_id JOIN exercise_progress p ON p.exercise_id=e.id AND p.workspace_id=s.workspace_id WHERE e.id=? AND s.workspace_id=? AND s.status='ready'`).get(exerciseId,workspaceId) as (Omit<PublicExerciseContext,'lastRun'|'lastSubmission'|'helpUsed'> & {lastRunJson:string|null;lastSubmissionJson:string|null;helpUsed:number})|undefined; if(!row)return null; const {lastRunJson,lastSubmissionJson,helpUsed,...context}=row; return publicExerciseContextSchema.parse({ ...context, lastRun:aggregate(lastRunJson), lastSubmission:aggregate(lastSubmissionJson), helpUsed:Boolean(helpUsed) }) }
  saveDraft(workspaceId: string, exerciseId: string, code: string, now: number): void { const changed=this.database.sqlite.prepare("UPDATE exercise_progress SET current_code=?,status=CASE WHEN status='passed' THEN status ELSE 'in_progress' END,updated_at=? WHERE workspace_id=? AND exercise_id=? AND EXISTS (SELECT 1 FROM exercises e JOIN exercise_sets s ON s.id=e.set_id WHERE e.id=exercise_progress.exercise_id AND s.workspace_id=exercise_progress.workspace_id AND s.status='ready')").run(code,now,workspaceId,exerciseId).changes; if(!changed)throw new Error('Exercise not found') }
  markGenerating(input: { id: string; workspaceId: string; roadmapId: string; moduleId: string; topicId: string; lessonId: string; now: number }): void { this.database.sqlite.prepare(`INSERT INTO exercise_sets (id,workspace_id,roadmap_id,module_id,topic_id,lesson_id,status,generation_attempts,created_at,updated_at) VALUES (?,?,?,?,?,?,'generating',1,?,?) ON CONFLICT(workspace_id,topic_id) DO UPDATE SET roadmap_id=excluded.roadmap_id,module_id=excluded.module_id,lesson_id=excluded.lesson_id,status='generating',generation_attempts=exercise_sets.generation_attempts+1,retry_after=NULL,last_error_code=CASE WHEN exercise_sets.last_error_code=? THEN exercise_sets.last_error_code ELSE NULL END,updated_at=excluded.updated_at`).run(input.id, input.workspaceId, input.roadmapId, input.moduleId, input.topicId, input.lessonId, input.now, input.now, EXERCISE_DATA_INVALID) }
  markGenerationFailure(workspaceId: string, topicId: string, status: 'waiting_for_provider' | 'failed_retryable', code: string, retryAfter: number, now: number): ExerciseSet { this.database.sqlite.prepare('UPDATE exercise_sets SET status=?,retry_after=?,last_error_code=CASE WHEN last_error_code=? THEN last_error_code ELSE ? END,updated_at=? WHERE workspace_id=? AND topic_id=?').run(status, retryAfter, EXERCISE_DATA_INVALID, code, now, workspaceId, topicId); return this.findSet(workspaceId, topicId)! }
  saveGenerated(input: { setId: string; workspaceId: string; topicId: string; providerId: string; modelId: string; exercises: PrivateExercise[]; now: number }): ExerciseSet { return this.database.sqlite.transaction(() => {
    const state = this.database.sqlite.prepare('SELECT last_error_code AS lastErrorCode FROM exercise_sets WHERE id=?').get(input.setId) as { lastErrorCode: string | null } | undefined
    const existing = this.database.sqlite.prepare(`SELECT ${exerciseColumns} FROM exercises e JOIN exercise_sets s ON s.id=e.set_id WHERE e.set_id=? ORDER BY e.position`).all(input.setId) as ExerciseRow[]
    const selectiveRepair = state?.lastErrorCode === EXERCISE_DATA_INVALID
    const validByPosition = new Map(selectiveRepair ? existing.filter(validExerciseData).map((item) => [item.position, item] as const) : [])
    if (!selectiveRepair) this.database.sqlite.prepare('DELETE FROM exercises WHERE set_id=?').run(input.setId)
    const insert = this.database.sqlite.prepare('INSERT INTO exercises (id,set_id,position,kind,difficulty,title,statement,input_description,output_description,language,starter_code,prediction_prompt,code_to_observe,required_for_topic_completion,public_tests_json,private_tests_json,reference_solution,expected_prediction,hint,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')
    const replace = this.database.sqlite.prepare('UPDATE exercises SET kind=?,difficulty=?,title=?,statement=?,input_description=?,output_description=?,language=?,starter_code=?,prediction_prompt=?,code_to_observe=?,required_for_topic_completion=?,public_tests_json=?,private_tests_json=?,reference_solution=?,expected_prediction=?,hint=? WHERE id=?')
    for (const exercise of input.exercises) {
      const valid = validByPosition.get(exercise.position)
      if (valid) continue
      const old = selectiveRepair ? existing.find((item) => item.position === exercise.position) : undefined
      if (old) replace.run(exercise.kind,exercise.difficulty,exercise.title,exercise.statement,exercise.inputDescription,exercise.outputDescription,exercise.language,exercise.starterCode,exercise.predictionPrompt,exercise.codeToObserve,Number(exercise.requiredForTopicCompletion),JSON.stringify(exercise.publicTests),JSON.stringify(exercise.hiddenTests),exercise.referenceSolution,exercise.expectedPrediction,exercise.hint,old.id)
      else { insert.run(exercise.id,input.setId,exercise.position,exercise.kind,exercise.difficulty,exercise.title,exercise.statement,exercise.inputDescription,exercise.outputDescription,exercise.language,exercise.starterCode,exercise.predictionPrompt,exercise.codeToObserve,Number(exercise.requiredForTopicCompletion),JSON.stringify(exercise.publicTests),JSON.stringify(exercise.hiddenTests),exercise.referenceSolution,exercise.expectedPrediction,exercise.hint,input.now); this.database.sqlite.prepare("INSERT INTO exercise_progress (workspace_id,exercise_id,status,current_code,attempts,help_count,updated_at) VALUES (?,?,'not_started',?,0,0,?)").run(input.workspaceId,exercise.id,exercise.starterCode,input.now) }
    }
    this.database.sqlite.prepare("UPDATE exercise_sets SET status='ready',provider_id=?,model_id=?,retry_after=NULL,last_error_code=NULL,updated_at=? WHERE id=?").run(input.providerId,input.modelId,input.now,input.setId)
    return this.findSet(input.workspaceId,input.topicId)!
  })() }
  saveRun(workspaceId: string, exerciseId: string, code: string, execution: ExerciseExecution, now: number): void { const result = { status: execution.status, passedTests: execution.passedTests, totalTests: execution.totalTests, message: execution.message, compileDiagnostics: execution.compileDiagnostics }; this.database.sqlite.prepare("UPDATE exercise_progress SET current_code=?,last_run_json=?,status=CASE WHEN status='passed' THEN status ELSE 'in_progress' END,updated_at=? WHERE workspace_id=? AND exercise_id=?").run(code,JSON.stringify(result),now,workspaceId,exerciseId) }
  findAttempt(workspaceId: string, idempotencyKey: string, exerciseId: string, sourceRevision: string): ExerciseExecution | null { const row = this.database.sqlite.prepare('SELECT exercise_id AS exerciseId,source_revision AS sourceRevision,public_result_json AS publicResultJson FROM exercise_attempts WHERE workspace_id=? AND idempotency_key=?').get(workspaceId,idempotencyKey) as { exerciseId: string; sourceRevision: string; publicResultJson: string } | undefined; if (row && (row.exerciseId !== exerciseId || row.sourceRevision !== sourceRevision)) throw new Error('Idempotency key was already used for a different submission'); return row ? exerciseExecutionSchema.parse(JSON.parse(row.publicResultJson)) : null }
  saveSubmission(input: { workspaceId: string; exercise: PrivateExercise; code: string; prediction: string | null; idempotencyKey: string; sourceRevision: string; execution: ExerciseExecution; privateCases: unknown[]; now: number }): ExerciseExecution {
    return this.database.sqlite.transaction(() => {
      const replay = this.findAttempt(input.workspaceId, input.idempotencyKey, input.exercise.id, input.sourceRevision)
      if (replay) return replay
      this.database.sqlite.prepare('INSERT INTO exercise_attempts (id,workspace_id,exercise_id,idempotency_key,source_revision,code,prediction,status,public_result_json,private_result_json,duration_ms,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)').run(input.execution.attemptId, input.workspaceId, input.exercise.id, input.idempotencyKey, input.sourceRevision, input.code, input.prediction, input.execution.status, JSON.stringify(input.execution), JSON.stringify(input.privateCases), input.execution.durationMs, input.now)
      const before = this.database.sqlite.prepare('SELECT status,attempts,help_used AS helpUsed FROM exercise_progress WHERE workspace_id=? AND exercise_id=?').get(input.workspaceId, input.exercise.id) as { status: string; attempts: number; helpUsed: number } | undefined
      const result = { status: input.execution.status, passedTests: input.execution.passedTests, totalTests: input.execution.totalTests, message: input.execution.message, compileDiagnostics: input.execution.compileDiagnostics }
      const firstTry = Boolean(input.execution.passed && before?.attempts === 0 && !before.helpUsed)
      this.database.sqlite.prepare("UPDATE exercise_progress SET current_code=?,attempts=attempts+1,last_submission_json=?,passed_tests=?,total_tests=?,first_try_success=CASE WHEN ? THEN 1 ELSE first_try_success END,status=CASE WHEN ? THEN 'passed' ELSE CASE WHEN status='passed' THEN status ELSE 'in_progress' END END,passed_at=CASE WHEN ? THEN COALESCE(passed_at,?) ELSE passed_at END,updated_at=? WHERE workspace_id=? AND exercise_id=?").run(input.code, JSON.stringify(result), input.execution.passedTests, input.execution.totalTests, Number(firstTry), Number(input.execution.passed), Number(input.execution.passed), input.now, input.now, input.workspaceId, input.exercise.id)
      writeLearningState(this.database, applyLearningEvidence(readLearningState(this.database, input.workspaceId, input.exercise.topicId, input.now), { type: input.execution.passed ? 'EXERCISE_PASSED' : 'EXERCISE_FAILED', attempt: (before?.attempts ?? 0) + 1, hintUsed: Boolean(before?.helpUsed), occurredAt: input.now }))
      this.evidenceRecorder?.record({ workspaceId: input.workspaceId, environment: 'exercise', sourceRef: input.exercise.id, sourceRevision: input.sourceRevision, firstSeenAt: null, idempotencyKey: input.idempotencyKey, occurredAt: input.now, outcome: input.execution.passed ? 'correct' : 'incorrect', correct: input.execution.passed, independent: !before?.helpUsed, topicId: input.exercise.topicId, mappingProvenance: 'legacy_backfill', mappingConfidence: 0, difficulty: input.exercise.difficulty, prerequisiteConceptIds: [], reasoningQuality: 'not_assessed', events: [{ type: input.execution.passed ? 'answer_correct' : 'answer_incorrect', strength: input.execution.passed && !before?.helpUsed ? 'strong' : input.execution.passed ? 'weak' : 'moderate', ordinal: 0, metadata: { passedTests: input.execution.passedTests, totalTests: input.execution.totalTests } }] })
      return input.execution
    })()
  }
  requestHelp(workspaceId: string, exerciseId: string, requestId: string, type: 'hint_requested' | 'coach_help_requested' | 'worked_example_shown' | 'solution_revealed', now: number): { helpCount: number; hint: string } {
    return this.database.sqlite.transaction(() => {
      const exercise = this.findPrivateExercise(workspaceId, exerciseId)
      if (!exercise) throw new Error('Exercise not found')
      const insertedHelp = this.database.sqlite.prepare('INSERT OR IGNORE INTO exercise_help_events (request_id,workspace_id,exercise_id,type,created_at) VALUES (?,?,?,?,?)').run(requestId, workspaceId, exerciseId, type, now)
      if (!insertedHelp.changes) {
        const current = this.database.sqlite.prepare('SELECT help_count AS helpCount FROM exercise_progress WHERE workspace_id=? AND exercise_id=?').get(workspaceId, exerciseId) as { helpCount: number }
        return { helpCount: current.helpCount, hint: exercise.hint }
      }
      this.database.sqlite.prepare("UPDATE exercise_progress SET help_count=help_count+1,help_used=1,status=CASE WHEN status='passed' THEN status ELSE 'in_progress' END,updated_at=? WHERE workspace_id=? AND exercise_id=?").run(now, workspaceId, exerciseId)
      const row = this.database.sqlite.prepare('SELECT help_count AS helpCount FROM exercise_progress WHERE workspace_id=? AND exercise_id=?').get(workspaceId, exerciseId) as { helpCount: number }
      writeLearningState(this.database, applyLearningEvidence(readLearningState(this.database, workspaceId, exercise.topicId, now), { type: 'HELP_USED', occurredAt: now }))
      this.evidenceRecorder?.record({ workspaceId, environment: 'exercise', sourceRef: exercise.id, sourceRevision: `help:${row.helpCount}`, firstSeenAt: null, idempotencyKey: requestId, occurredAt: now, outcome: 'observed', correct: null, independent: false, topicId: exercise.topicId, mappingProvenance: 'legacy_backfill', mappingConfidence: 0, difficulty: exercise.difficulty, prerequisiteConceptIds: [], reasoningQuality: 'not_assessed', events: [{ type, strength: 'none', ordinal: 0, metadata: { helpCount: row.helpCount } }] })
      return { helpCount: row.helpCount, hint: exercise.hint }
    })()
  }
  setContentRevision(setId: string, revision: number, inputHash: string): void { this.database.sqlite.prepare('UPDATE exercise_sets SET content_revision=?,input_hash=? WHERE id=?').run(revision, inputHash, setId) }
}
