import { createHash } from 'node:crypto'
import { z } from 'zod'
import type { AIProvider, AIResponse } from '../ai/ai-provider'
import type { AIProviderManager } from '../ai/ai-provider-manager'
import { extractJsonDocument } from '../ai/structured-json'
import type { ToolchainManager } from '../../main/code-execution/toolchain-manager'
import type { WorkspaceProject, ProjectLanguage } from '../../shared/contracts/project-contract'
import { exerciseDifficultySchema, exerciseKindSchema, publicExerciseContextSchema, publicExerciseTestSchema, type ExerciseExecution, type ExerciseSet, type PublicExerciseContext } from '../../shared/contracts/exercise-contract'
import type { CodeExecutionResult } from '../../shared/contracts/code-execution-contract'
import type { Roadmap } from '../../shared/contracts/roadmap-contract'
import type { Workspace } from '../../shared/contracts/workspace-contract'

const generatedTestSchema = publicExerciseTestSchema.omit({ id: true })
const generatedExerciseSchema = z.object({ kind: exerciseKindSchema, difficulty: exerciseDifficultySchema, title: z.string().trim().min(1).max(180), statement: z.string().trim().min(1).max(5000), inputDescription: z.string().trim().max(2000), outputDescription: z.string().trim().max(2000), language: z.enum(['python', 'c', 'java']), starterCode: z.string().max(20_000), predictionPrompt: z.string().trim().min(1).max(1000).nullable(), codeToObserve: z.string().min(1).max(20_000).nullable(), requiredForTopicCompletion: z.boolean(), publicTests: z.array(generatedTestSchema).max(5), hiddenTests: z.array(generatedTestSchema).max(8), referenceSolution: z.string().max(20_000).nullable(), expectedPrediction: z.string().max(20_000).nullable(), hint: z.string().min(1).max(1000) }).strict().superRefine((value, context) => {
  if (value.kind === 'PREDICT_OUTPUT') {
    if (!value.predictionPrompt || !value.codeToObserve || value.expectedPrediction === null) context.addIssue({ code: 'custom', message: 'PREDICT_OUTPUT requires predictionPrompt, codeToObserve and expectedPrediction' })
    if (value.starterCode || value.publicTests.length || value.hiddenTests.length || value.referenceSolution !== null) context.addIssue({ code: 'custom', message: 'PREDICT_OUTPUT cannot contain editable code, tests or a reference solution' })
    return
  }
  if (!value.starterCode || !value.referenceSolution || value.publicTests.length < 1 || value.hiddenTests.length < 3 || value.expectedPrediction !== null || value.predictionPrompt !== null || value.codeToObserve !== null) context.addIssue({ code: 'custom', message: 'Code exercise fields are inconsistent' })
  if (value.kind === 'FIX_CODE' && (value.starterCode === value.referenceSolution || !/\b(?:defeito|erro|bug|falha|corrij|consert)/i.test(value.statement))) context.addIssue({ code: 'custom', message: 'FIX_CODE must contain a distinct defect and describe it' })
  if (value.kind === 'COMPLETE_CODE' && !/(?:TODO|PREENCHA|COMPLETE|___|\.\.\.)/i.test(value.starterCode)) context.addIssue({ code: 'custom', message: 'COMPLETE_CODE must contain an explicit TODO marker' })
})
const generatedSetSchema = z.object({ exercises: z.array(generatedExerciseSchema).min(4).max(7) }).strict().superRefine((value, context) => {
  for (const kind of exerciseKindSchema.options) if (!value.exercises.some((exercise) => exercise.kind === kind)) context.addIssue({ code: 'custom', message: `Generated set must include ${kind}` })
})
export type PrivateExercise = ExerciseSet['exercises'][number] & { hiddenTests: Array<{ id: string; input: string; expectedOutput: string }>; referenceSolution: string | null; expectedPrediction: string | null; hint: string; setId: string; workspaceId: string; topicId: string }
type PrivateCaseResult = { testId: string; visibility: 'public' | 'hidden'; passed: boolean; actualOutput: string | null; expectedOutput: string; input: string; status: ExerciseExecution['status'] }
export interface ExerciseRepository {
  findSet(workspaceId: string, topicId: string): ExerciseSet | null
  findPrivateExercise(workspaceId: string, exerciseId: string): PrivateExercise | null
  findPublicContext(workspaceId: string, exerciseId: string): PublicExerciseContext | null
  saveDraft(workspaceId: string, exerciseId: string, code: string, now: number): void
  markGenerating(input: { id: string; workspaceId: string; roadmapId: string; moduleId: string; topicId: string; lessonId: string; now: number }): void
  markGenerationFailure(workspaceId: string, topicId: string, status: 'waiting_for_provider' | 'failed_retryable', code: string, retryAfter: number, now: number): ExerciseSet
  saveGenerated(input: { setId: string; workspaceId: string; topicId: string; providerId: string; modelId: string; exercises: PrivateExercise[]; now: number }): ExerciseSet
  saveRun(workspaceId: string, exerciseId: string, code: string, execution: ExerciseExecution, now: number): void
  findAttempt(workspaceId: string, idempotencyKey: string, exerciseId: string, sourceRevision: string): ExerciseExecution | null
  saveSubmission(input: { workspaceId: string; exercise: PrivateExercise; code: string; prediction: string | null; idempotencyKey: string; sourceRevision: string; execution: ExerciseExecution; privateCases: PrivateCaseResult[]; now: number }): ExerciseExecution
  requestHelp(workspaceId: string, exerciseId: string, now: number): { helpCount: number; hint: string }
}

const normalize = (value: string) => value.replace(/\r\n/g, '\n').trimEnd()
const safeDiagnostics = (result: CodeExecutionResult): string[] => result.phase === 'compile' ? (result.diagnostics ?? []).slice(0, 20).map((item) => `${item.severity}: linha ${item.line}, coluna ${item.column}: ${item.message}`.slice(0, 1000)) : []
const executionMessage = (status: ExerciseExecution['status'], passedTests: number, totalTests: number): string => status === 'passed' ? `Solução aprovada em ${totalTests} testes.` : status === 'compile_error' ? 'O código não compilou. Revise os diagnósticos seguros.' : status === 'runtime_error' ? 'O programa terminou com erro de execução.' : status === 'timed_out' ? 'O programa excedeu o tempo permitido.' : status === 'executed' ? 'Execução livre concluída. Envie a solução para avaliá-la.' : `${passedTests} de ${totalTests} testes passaram.`
function project(workspaceId: string, exercise: Pick<PrivateExercise, 'title' | 'language'>, code: string): WorkspaceProject { const path = exercise.language === 'python' ? 'main.py' : exercise.language === 'c' ? 'main.c' : 'Main.java'; return { id: crypto.randomUUID(), workspaceId, name: exercise.title, language: exercise.language, entryFilePath: path, files: [{ id: crypto.randomUUID(), path, content: code, revision: 0, updatedAt: Date.now() }], activeFileId: '', openFileIds: [], updatedAt: Date.now() } }

export class ExerciseService {
  private readonly generating = new Map<string, Promise<ExerciseSet>>()
  private readonly submitting = new Map<string, { exerciseId: string; sourceRevision: string; task: Promise<ExerciseExecution> }>()
  private readonly submitQueues = new Map<string, Promise<unknown>>()
  constructor(private readonly repository: ExerciseRepository, private readonly providers: AIProviderManager, private readonly toolchains: ToolchainManager, private readonly getWorkspace: (id: string) => Promise<Workspace | null>, private readonly getRoadmap: (workspaceId: string) => Roadmap | null, private readonly now = Date.now, private readonly createId = () => crypto.randomUUID()) {}

  getSet(input: { workspaceId: string; topicId: string }): ExerciseSet | null { return this.repository.findSet(input.workspaceId, input.topicId) }
  getPublicContext(input: { workspaceId: string; exerciseId: string }): PublicExerciseContext | null { const context = this.repository.findPublicContext(input.workspaceId, input.exerciseId); return context ? publicExerciseContextSchema.parse(context) : null }
  saveDraft(input: { workspaceId: string; exerciseId: string; code: string }): void { this.repository.saveDraft(input.workspaceId, input.exerciseId, input.code, this.now()) }
  ensureSet(input: { workspaceId: string; roadmapId: string; moduleId: string; topicId: string; lessonId: string }): Promise<ExerciseSet> { const key = `${input.workspaceId}:${input.topicId}`; const current = this.generating.get(key); if (current) return current; const task = this.ensureOnce(input).finally(() => this.generating.delete(key)); this.generating.set(key, task); return task }
  private async ensureOnce(input: { workspaceId: string; roadmapId: string; moduleId: string; topicId: string; lessonId: string }): Promise<ExerciseSet> {
    const cached = this.repository.findSet(input.workspaceId, input.topicId)
    const sameContext = cached?.roadmapId === input.roadmapId && cached.moduleId === input.moduleId && cached.lessonId === input.lessonId
    if (sameContext && (cached.status === 'ready' || (cached.retryAfter !== null && cached.retryAfter > this.now()))) return cached
    const workspace = await this.getWorkspace(input.workspaceId); const roadmap = this.getRoadmap(input.workspaceId); const module = roadmap?.modules.find((item) => item.id === input.moduleId); const topic = module?.topics.find((item) => `${module.id}:${item}` === input.topicId)
    if (!workspace || !roadmap || roadmap.id !== input.roadmapId || !module || !topic) throw new Error('Exercise topic not found in current roadmap')
    const setId = cached?.id ?? this.createId(); this.repository.markGenerating({ id: setId, ...input, now: this.now() })
    const available = this.toolchains.getStatuses().filter((item) => item.available).map((item) => item.language)
    if (!available.length) return this.repository.markGenerationFailure(input.workspaceId, input.topicId, 'failed_retryable', 'TOOLCHAIN_UNAVAILABLE', this.now() + 30_000, this.now())
    const provider = this.providers.route('lesson')
    if (!provider) return this.repository.markGenerationFailure(input.workspaceId, input.topicId, 'waiting_for_provider', 'PROVIDER_UNAVAILABLE', this.now() + 300_000, this.now())
    try {
      let response = await this.generate(provider, { workspace, roadmap, module, topic, topicId: input.topicId, available })
      let values: PrivateExercise[]
      try { values = this.parseGenerated(response.content, setId, input.workspaceId, input.topicId); await this.selfValidate(input.workspaceId, values, available) }
       catch (error) { response = await provider.sendMessage({ messages: [{ role: 'system', content: 'Faça uma única correção do conjunto e retorne somente JSON no formato original. Mantenha 4 a 7 exercícios e inclua os quatro kinds. Para PREDICT_OUTPUT use codeToObserve, predictionPrompt e expectedPrediction, sem testes nem referência. Para os demais, use testes e referência; FIX_CODE deve conter e descrever defeito, COMPLETE_CODE deve conter TODO. Inclua ao menos um obrigatório. Não explique.' }, { role: 'user', content: JSON.stringify({ error: error instanceof Error ? error.message : 'invalid', invalidResponse: response.content }) }], maxOutputTokens: 7000, signal: AbortSignal.timeout(300_000) }); values = this.parseGenerated(response.content, setId, input.workspaceId, input.topicId); await this.selfValidate(input.workspaceId, values, available) }
      return this.repository.saveGenerated({ setId, workspaceId: input.workspaceId, topicId: input.topicId, providerId: response.providerId, modelId: response.modelId, exercises: values, now: this.now() })
    } catch { return this.repository.markGenerationFailure(input.workspaceId, input.topicId, 'failed_retryable', 'EXERCISE_GENERATION_INVALID', this.now() + 30_000, this.now()) }
  }
  private parseGenerated(content: string, setId: string, workspaceId: string, topicId: string): PrivateExercise[] { const parsed = generatedSetSchema.parse(extractJsonDocument(content)); const values = parsed.exercises.map((item, position) => ({ id: this.createId(), setId, workspaceId, topicId, position: position + 1, ...item, publicTests: item.publicTests.map((test, index) => ({ id: `public-${index + 1}`, ...test })), hiddenTests: item.hiddenTests.map((test, index) => ({ id: `hidden-${index + 1}`, ...test })) })); if (!values.some((item) => item.requiredForTopicCompletion)) throw new Error('EXERCISE_REQUIRED_MISSING'); return values }
  private generate(provider: AIProvider, context: Record<string, unknown>): Promise<AIResponse> { return provider.sendMessage({ messages: [{ role: 'system', content: 'Gere 4 a 7 exercícios específicos para o tópico e inclua TODOS os quatro kinds pelo menos uma vez. Retorne somente JSON {exercises:[...]}. Campos comuns: kind, difficulty, title, statement, inputDescription, outputDescription, language dentre available, requiredForTopicCompletion e hint. PROGRAMMING_PROBLEM usa starterCode normal, 1-5 publicTests, 3-8 hiddenTests e referenceSolution. FIX_CODE segue os mesmos campos, mas starterCode deve conter defeito real, ser diferente da referência e statement deve descrever o erro/defeito a corrigir. COMPLETE_CODE segue os mesmos campos, mas starterCode deve conter marcador TODO explícito. PREDICT_OUTPUT usa starterCode vazio, predictionPrompt, codeToObserve e expectedPrediction privados, arrays de testes vazios e referenceSolution null; o aluno prevê exatamente a saída determinística do código mostrado. Para os outros kinds, predictionPrompt/codeToObserve/expectedPrediction são null. Inclua ao menos um obrigatório. Nunca coloque testes ocultos, expectedPrediction ou solução no enunciado. Java usa public class Main. Exercícios de código leem stdin e escrevem somente a resposta em stdout.' }, { role: 'user', content: JSON.stringify(context) }], maxOutputTokens: 7000, signal: AbortSignal.timeout(300_000) }) }
  private async selfValidate(workspaceId: string, exercises: PrivateExercise[], available: ProjectLanguage[]): Promise<void> { for (const exercise of exercises) { if (!available.includes(exercise.language)) throw new Error('EXERCISE_TOOLCHAIN_INVALID'); if (exercise.kind === 'PREDICT_OUTPUT') { const result = await this.toolchains.execute(project(workspaceId, exercise, exercise.codeToObserve!), undefined, ''); if (result.exitCode !== 0 || result.timedOut || normalize(result.stdout) !== normalize(exercise.expectedPrediction!)) throw new Error('EXERCISE_PREDICTION_FAILED'); continue } for (const test of [...exercise.publicTests, ...exercise.hiddenTests]) { const result = await this.toolchains.execute(project(workspaceId, exercise, exercise.referenceSolution!), undefined, test.input); if (result.exitCode !== 0 || result.timedOut || normalize(result.stdout) !== normalize(test.expectedOutput)) throw new Error('EXERCISE_REFERENCE_FAILED') } } }
  async run(input: { workspaceId: string; exerciseId: string; code: string; stdin: string }): Promise<ExerciseExecution> { const exercise = this.requireExercise(input.workspaceId, input.exerciseId); const source = exercise.kind === 'PREDICT_OUTPUT' ? exercise.codeToObserve! : input.code; if (!source.trim()) throw new Error('Code is required'); const started = this.now(); const result = await this.toolchains.execute(project(input.workspaceId, exercise, source), undefined, input.stdin); const status = result.timedOut ? 'timed_out' : result.phase === 'compile' && result.exitCode !== 0 ? 'compile_error' : result.exitCode !== 0 ? 'runtime_error' : 'executed'; const createdAt = this.now(); const execution: ExerciseExecution = { mode: 'run', exerciseId: exercise.id, attemptId: null, status, passed: false, passedTests: 0, totalTests: 0, message: executionMessage(status, 0, 0), compileDiagnostics: safeDiagnostics(result), cases: [], stdout: result.stdout.slice(0, 8000), stderr: status === 'compile_error' ? '' : result.stderr.slice(0, 8000), durationMs: createdAt - started, createdAt }; this.repository.saveRun(input.workspaceId, input.exerciseId, exercise.kind === 'PREDICT_OUTPUT' ? '' : input.code, execution, createdAt); return execution }
  submit(input: { workspaceId: string; exerciseId: string; code: string; prediction: string | null; idempotencyKey: string }): Promise<ExerciseExecution> { const idempotency = `${input.workspaceId}:${input.idempotencyKey}`; const sourceRevision = createHash('sha256').update(`${input.code}\0${input.prediction ?? ''}`).digest('hex').slice(0, 16); const persisted = this.repository.findAttempt(input.workspaceId, input.idempotencyKey, input.exerciseId, sourceRevision); if (persisted) return Promise.resolve(persisted); const active = this.submitting.get(idempotency); if (active) { if (active.exerciseId !== input.exerciseId || active.sourceRevision !== sourceRevision) return Promise.reject(new Error('Idempotency key is already in use for a different submission')); return active.task } const queueKey = `${input.workspaceId}:${input.exerciseId}`; const previous = this.submitQueues.get(queueKey) ?? Promise.resolve(); const task = previous.catch(() => undefined).then(() => this.submitOnce(input, sourceRevision)).finally(() => { this.submitting.delete(idempotency); if (this.submitQueues.get(queueKey) === task) this.submitQueues.delete(queueKey) }); this.submitting.set(idempotency, { exerciseId: input.exerciseId, sourceRevision, task }); this.submitQueues.set(queueKey, task); return task }
  private async submitOnce(input: { workspaceId: string; exerciseId: string; code: string; prediction: string | null; idempotencyKey: string }, sourceRevision: string): Promise<ExerciseExecution> { const replay = this.repository.findAttempt(input.workspaceId, input.idempotencyKey, input.exerciseId, sourceRevision); if (replay) return replay; const exercise = this.requireExercise(input.workspaceId, input.exerciseId); const started = this.now(); const privateCases: PrivateCaseResult[] = []; let terminal: ExerciseExecution['status'] = 'passed'; let compileDiagnostics: string[] = []
    if (exercise.kind === 'PREDICT_OUTPUT') { if (!input.prediction?.trim()) throw new Error('Prediction is required'); terminal = normalize(input.prediction) === normalize(exercise.expectedPrediction!) ? 'passed' : 'failed' }
    else { if (!input.code.trim()) throw new Error('Code is required'); for (const test of [...exercise.publicTests, ...exercise.hiddenTests]) { const result = await this.toolchains.execute(project(input.workspaceId, exercise, input.code), undefined, test.input); const passed = result.exitCode === 0 && !result.timedOut && normalize(result.stdout) === normalize(test.expectedOutput); const status: ExerciseExecution['status'] = passed ? 'passed' : result.timedOut ? 'timed_out' : result.phase === 'compile' ? 'compile_error' : result.exitCode !== 0 ? 'runtime_error' : 'failed'; if (!passed && terminal === 'passed') terminal = status; if (status === 'compile_error' && compileDiagnostics.length === 0) compileDiagnostics = safeDiagnostics(result); const visibility = test.id.startsWith('public-') ? 'public' as const : 'hidden' as const; privateCases.push({ testId: test.id, visibility, passed, actualOutput: result.stdout.slice(0, 8000), expectedOutput: test.expectedOutput, input: test.input, status }) } }
    const now = this.now(); const passedTests = privateCases.filter((item) => item.passed).length; const totalTests = privateCases.length; const message = terminal === 'passed' ? 'Solução aprovada.' : terminal === 'failed' ? 'A resposta ainda não foi aprovada.' : executionMessage(terminal, passedTests, totalTests); const execution: ExerciseExecution = { mode: 'submit', exerciseId: exercise.id, attemptId: this.createId(), status: terminal, passed: terminal === 'passed', passedTests, totalTests, message, compileDiagnostics, cases: [], stdout: '', stderr: '', durationMs: now - started, createdAt: now }; return this.repository.saveSubmission({ workspaceId: input.workspaceId, exercise, code: input.code, prediction: input.prediction, idempotencyKey: input.idempotencyKey, sourceRevision, execution, privateCases, now }) }
  requestHelp(input: { workspaceId: string; exerciseId: string }): { exerciseId: string; helpCount: number; hint: string } { const exercise = this.requireExercise(input.workspaceId, input.exerciseId); const result = this.repository.requestHelp(input.workspaceId, input.exerciseId, this.now()); return { exerciseId: exercise.id, ...result } }
  private requireExercise(workspaceId: string, exerciseId: string): PrivateExercise { const exercise = this.repository.findPrivateExercise(workspaceId, exerciseId); if (!exercise) throw new Error('Exercise not found'); const status = this.toolchains.getStatuses().find((item) => item.language === exercise.language); if (!status?.available) throw new Error(`Ambiente ${exercise.language} não disponível neste computador`); return exercise }
}
