import { z } from 'zod'
import { workspaceIdSchema } from './workspace-contract'

const trustedRoadmapHosts = ['roadmap.sh', 'developer.mozilla.org', 'docs.oracle.com', 'docs.python.org', 'openjfx.io', 'en.cppreference.com', 'gcc.gnu.org', 'www.gnu.org', 'learn.microsoft.com', 'freecodecamp.org', 'khanacademy.org']
const webRoadmapResourceSchema = z.object({ kind: z.literal('web').default('web'), title: z.string().trim().min(1).max(160), url: z.url().max(1000).refine((value) => { const url = new URL(value); return url.protocol === 'https:' && trustedRoadmapHosts.some((host) => url.hostname === host || url.hostname.endsWith(`.${host}`)) }, 'Fonte não permitida'), type: z.enum(['roadmap', 'documentation', 'course', 'article', 'video']) }).strict()
const materialRoadmapResourceSchema = z.object({ kind: z.literal('material'), title: z.string().trim().min(1).max(160), type: z.literal('material'), materialId: z.uuid(), pageNumber: z.number().int().min(1).max(500), role: z.enum(['base', 'priority', 'reference']), excerptHash: z.string().regex(/^[a-f0-9]{64}$/) }).strict()
export const roadmapResourceSchema = z.preprocess((value) => value && typeof value === 'object' && !('kind' in value) ? { kind: 'web', ...value } : value, z.discriminatedUnion('kind', [webRoadmapResourceSchema, materialRoadmapResourceSchema]))
export const roadmapModuleProposalSchema = z.object({ title: z.string().trim().min(1).max(160), objective: z.string().trim().min(1).max(500), estimatedMinutes: z.number().int().min(10).max(2400), topics: z.array(z.string().trim().min(1).max(240)).min(1).max(12), outcomes: z.array(z.string().trim().min(1).max(240)).min(1).max(8), practice: z.string().trim().min(1).max(600), completionCriteria: z.array(z.string().trim().min(1).max(240)).min(1).max(6), resources: z.array(roadmapResourceSchema).max(6) }).strict()
export const roadmapProposalSchema = z.object({ title: z.string().trim().min(1).max(160), modules: z.array(roadmapModuleProposalSchema).min(1).max(16) }).strict()
export const generatedRoadmapModuleSchema = roadmapModuleProposalSchema.omit({ resources: true }).extend({ sourceIds: z.array(z.string().trim().min(1).max(100)).max(6) }).strict()
export const generatedRoadmapProposalSchema = z.object({ title: z.string().trim().min(1).max(160), modules: z.array(generatedRoadmapModuleSchema).min(1).max(16) }).strict()
export const workspaceRoadmapInputSchema = z.object({ workspaceId: workspaceIdSchema, instruction: z.string().trim().min(1).max(2000).optional() }).strict()
export const acceptRoadmapInputSchema = z.object({ workspaceId: workspaceIdSchema, roadmapId: z.uuid() }).strict()
export const previewRoadmapRebuildInputSchema = z.object({ workspaceId: workspaceIdSchema, materialIds: z.array(z.uuid()).min(1).max(20), instruction: z.string().trim().min(1).max(2000).optional() }).strict()
export const applyRoadmapRebuildInputSchema = z.object({ workspaceId: workspaceIdSchema, previewId: z.uuid(), acknowledgeUnsafeChanges: z.boolean().default(false) }).strict()
export const getRoadmapRebuildPreviewInputSchema = z.object({ workspaceId: workspaceIdSchema }).strict()

export const roadmapModuleSchema = roadmapModuleProposalSchema.extend({ id: z.string().min(1).max(200), position: z.number().int().positive(), status: z.enum(['locked', 'available', 'active', 'completed']) }).strict()
export const roadmapSchema = z.object({ id: z.string().min(1).max(200), workspaceId: workspaceIdSchema, title: z.string().trim().min(1).max(160), status: z.enum(['proposed', 'accepted', 'archived']), generationKind: z.enum(['ai_generated', 'provisional_fallback']), version: z.number().int().positive(), providerId: z.string().nullable(), modelId: z.string().nullable(), modules: z.array(roadmapModuleSchema).min(1).max(16), createdAt: z.number().int().nonnegative(), updatedAt: z.number().int().nonnegative() }).strict()
export const roadmapRebuildImpactSchema = z.object({ preservedModuleIds: z.array(z.string()), preservedTopicIds: z.array(z.string()), addedTopics: z.array(z.string()), removedTopics: z.array(z.string()), unsafeProgressTopicIds: z.array(z.string()), requiresAcknowledgement: z.boolean() }).strict()
export const roadmapRebuildPreviewSchema = z.object({ id: z.string().min(1).max(200), workspaceId: workspaceIdSchema, currentRoadmapId: z.string().min(1).max(200), title: z.string().trim().min(1).max(160), modules: z.array(roadmapModuleSchema).min(1).max(16), materialIds: z.array(z.uuid()).min(1).max(20), impact: roadmapRebuildImpactSchema, status: z.enum(['pending', 'applied', 'stale']), appliedRoadmapId: z.string().nullable(), createdAt: z.number().int().nonnegative(), resolvedAt: z.number().int().nonnegative().nullable() }).strict()

export type RoadmapResource = z.infer<typeof roadmapResourceSchema>
export type CurriculumSourceType = 'documentation' | 'reference' | 'outline' | 'student_material' | 'educational'
export interface CurriculumSource { readonly id: string; readonly title: string; readonly url: string; readonly type: CurriculumSourceType; readonly authority: string; readonly retrieved: boolean; readonly retrievedAt: number | null; readonly excerpt: string | null }
export type LearningPathStatus = 'idle' | 'generating' | 'ready' | 'waiting_for_provider' | 'failed_retryable'
export interface LearningPathState { readonly workspaceId: string; readonly status: LearningPathStatus; readonly activeRoadmapId: string | null; readonly lastAttemptAt: number | null; readonly retryAfter: number | null; readonly lastErrorCode: string | null; readonly updatedAt: number }
export interface RoadmapModule { readonly id: string; readonly title: string; readonly objective: string; readonly estimatedMinutes: number; readonly position: number; readonly status: 'locked' | 'available' | 'active' | 'completed'; readonly topics: string[]; readonly outcomes: string[]; readonly practice: string; readonly completionCriteria: string[]; readonly resources: RoadmapResource[] }
export interface Roadmap { readonly id: string; readonly workspaceId: string; readonly title: string; readonly status: 'proposed' | 'accepted' | 'archived'; readonly generationKind: 'ai_generated' | 'provisional_fallback'; readonly version: number; readonly providerId: string | null; readonly modelId: string | null; readonly modules: RoadmapModule[]; readonly createdAt: number; readonly updatedAt: number }
export interface RoadmapRebuildImpact { readonly preservedModuleIds: string[]; readonly preservedTopicIds: string[]; readonly addedTopics: string[]; readonly removedTopics: string[]; readonly unsafeProgressTopicIds: string[]; readonly requiresAcknowledgement: boolean }
export type RoadmapRebuildPreviewStatus = 'pending' | 'applied' | 'stale'
export interface RoadmapRebuildPreview { readonly id: string; readonly workspaceId: string; readonly currentRoadmapId: string; readonly title: string; readonly modules: RoadmapModule[]; readonly materialIds: string[]; readonly impact: RoadmapRebuildImpact; readonly status: RoadmapRebuildPreviewStatus; readonly appliedRoadmapId: string | null; readonly createdAt: number; readonly resolvedAt: number | null }
export interface RoadmapApi { get(workspaceId: string): Promise<Roadmap | null>; getLearningPathState(workspaceId: string): Promise<LearningPathState>; generate(workspaceId: string, instruction?: string): Promise<Roadmap>; getRebuildPreview(input: z.infer<typeof getRoadmapRebuildPreviewInputSchema>): Promise<RoadmapRebuildPreview | null>; previewRebuild(input: z.infer<typeof previewRoadmapRebuildInputSchema>): Promise<RoadmapRebuildPreview>; applyRebuild(input: z.infer<typeof applyRoadmapRebuildInputSchema>): Promise<Roadmap>; accept(input: z.infer<typeof acceptRoadmapInputSchema>): Promise<Roadmap> }
