export const STUDY_WORKSPACE_CHANNELS = {
  getState: 'study-workspace:get-state',
  saveDocument: 'study-workspace:save-document',
  saveNotes: 'study-workspace:save-notes',
  updateContextSharing: 'study-workspace:update-context-sharing',
  togglePlanItem: 'study-workspace:toggle-plan-item',
  recalculatePlan: 'study-workspace:recalculate-plan',
  refreshLivePlan: 'study-workspace:refresh-live-plan',
  activatePlanItem: 'study-workspace:activate-plan-item',
  updateTimer: 'study-workspace:update-timer',
  setTimerDuration: 'study-workspace:set-timer-duration',
  flushDrafts: 'study-workspace:flush-drafts',
  completeSession: 'study-workspace:complete-session',
  listSessionHistory: 'study-workspace:list-session-history',
} as const
