import { z } from 'zod'
import type { AcademicSubjectContext, AcademicSubjectDeclaration, DeclaredAcademicLevel } from './academic-subject-context-contract'
export const fundamentalsAnswerSchema = z.enum(['yes', 'no', 'unknown'])
export const implementationLanguageSchema = z.enum(['python', 'c', 'java', 'javascript', 'typescript', 'other'])
export const workspaceTopicAnalysisStatusSchema = z.enum(['VALID', 'NEEDS_CONFIRMATION', 'NEEDS_CLARIFICATION', 'INVALID'])
export type WorkspaceTopicAnalysisStatus = z.infer<typeof workspaceTopicAnalysisStatusSchema>
export const workspaceInterpretationConfirmationSchema = z.object({ analysisToken: z.string().trim().min(1).max(200), revision: z.number().int().positive(), canonicalSubject: z.string().trim().min(1).max(80), canonicalFocus: z.string().trim().min(1).max(160) }).strict()
export const analyzeWorkspaceTopicInputSchema = z.object({ topic: z.string().trim().min(1).max(120), diagnosticAnswer: z.string().trim().max(1000).optional(), confirmation: workspaceInterpretationConfirmationSchema.optional(), fundamentals: fundamentalsAnswerSchema.optional(), implementationLanguage: implementationLanguageSchema.optional() }).strict()
export interface WorkspaceRelatedContext { readonly subject: string; readonly relation: 'implementation_language' | 'prerequisite'; readonly explanation: string; readonly context: AcademicSubjectContext | null }
export interface WorkspaceTopicAnalysis { readonly analysisToken: string; readonly revision: number; readonly status: WorkspaceTopicAnalysisStatus; readonly explanation: string; readonly topic: string; readonly canonicalSubject: string; readonly canonicalFocus: string; readonly canonicalContext: string; readonly objective: string; readonly needsDiagnostic: boolean; readonly needsFundamentals: boolean; readonly isProgramming: boolean; readonly fundamentals: z.infer<typeof fundamentalsAnswerSchema> | null; readonly implementationLanguage: z.infer<typeof implementationLanguageSchema> | null; readonly needsImplementationLanguage: boolean; readonly question: string | null; readonly questionOptional: boolean; readonly contextSource: 'academic-context' | 'workspace-context' | 'general-memory' | 'diagnostic' | 'fallback' | 'none'; readonly declaredLevel: DeclaredAcademicLevel | null; readonly declaredKnowledge: readonly string[]; readonly declaredDifficulties: readonly string[]; readonly declarations: readonly string[]; readonly evidence: readonly string[]; readonly goals: readonly string[]; readonly relatedContexts: readonly WorkspaceRelatedContext[]; readonly localKnowledgeProjection: string }
export interface WorkspaceOnboardingApi { analyze(input: z.infer<typeof analyzeWorkspaceTopicInputSchema>): Promise<WorkspaceTopicAnalysis>; replaceAcademicContext(input: AcademicSubjectDeclaration): Promise<AcademicSubjectContext> }
