import { cpSync, mkdtempSync, readFileSync, rmSync, unlinkSync, writeFileSync } from 'node:fs'
import { join, resolve } from 'node:path'
import { tmpdir } from 'node:os'
import { afterEach, describe, expect, it } from 'vitest'
import { openCoachDatabase } from '../../src/main/database/connection'
import { PlannerActionService } from '../../src/application/planning/planner-action-service'
import { PlanningService } from '../../src/application/planning/planning-service'
import { DrizzlePlannerActionRepository } from '../../src/main/repositories/drizzle-planner-action-repository'
import { DrizzlePlanningRepository } from '../../src/main/repositories/drizzle-planning-repository'

const migrationsFolder = resolve('drizzle/migrations')
const roots: string[] = []
function temporary(name: string): string { const root = mkdtempSync(join(tmpdir(), `coach-${name}-`)); roots.push(root); return root }
afterEach(() => { while (roots.length) rmSync(roots.pop()!, { recursive: true, force: true }) })

function seedPlan(databasePath: string) {
  const database = openCoachDatabase({ databasePath, migrationsFolder })
  const now = Date.parse('2026-09-10T12:00:00Z'); const workspaceId = crypto.randomUUID(); const planId = crypto.randomUUID(); const itemId = crypto.randomUUID(); const sessionId = crypto.randomUUID()
  database.sqlite.prepare("INSERT INTO workspaces (id,name,objective,status,confirmed_at,created_at,updated_at) VALUES (?,?,?,'active',?,?,?)").run(workspaceId, 'Java', 'Java', now, now, now)
  database.sqlite.prepare("INSERT INTO planning_settings (id,timezone,updated_at) VALUES ('current','UTC',?)").run(now)
  database.sqlite.prepare('INSERT INTO weekly_plans (id,week_start,timezone,revision,generated_at,updated_at) VALUES (?,?,?,?,?,?)').run(planId, '2026-09-07', 'UTC', 1, now, now)
  database.sqlite.prepare("INSERT INTO weekly_plan_items (id,plan_id,workspace_id,source_key,date_key,title,duration_minutes,position,status,activity_type,scheduled_start_minutes,reason,created_at,updated_at) VALUES (?,?,?,?,?,?,60,1,'pending','exercise',600,'test',?,?)").run(itemId, planId, workspaceId, 'java', '2026-09-10', 'Java', now, now)
  database.sqlite.prepare("INSERT INTO study_sessions (id,workspace_id,status,started_at,focus_seconds) VALUES (?,?,'active',?,0)").run(sessionId, workspaceId, now)
  database.sqlite.prepare("INSERT INTO study_plan_items (id,workspace_id,session_id,title,duration_minutes,position,status,activity_type,created_at,updated_at) VALUES (?,?,?,?,60,1,'pending','exercise',?,?)").run(itemId, workspaceId, sessionId, 'Java', now, now)
  return { database, now, workspaceId, itemId }
}

describe('planner action migration and exactly-once application', () => {
  it('upgrades a latest pre-0056 database, preserves rows and accepts the new type', () => {
    const root = temporary('migration'); const preMigrations = join(root, 'migrations'); cpSync(migrationsFolder, preMigrations, { recursive: true }); unlinkSync(join(preMigrations, '0056_planner_workspace_load_action.sql'))
    const journalPath = join(preMigrations, 'meta/_journal.json'); const journal = JSON.parse(readFileSync(journalPath, 'utf8')); journal.entries = journal.entries.filter((entry: { idx: number }) => entry.idx < 56); writeFileSync(journalPath, JSON.stringify(journal))
    const databasePath = join(root, 'coach.db'); let database = openCoachDatabase({ databasePath, migrationsFolder: preMigrations }); const existingId = crypto.randomUUID(); database.sqlite.prepare("INSERT INTO planner_actions (id,origin_message_id,label,context_version,idempotency_key,type,status,payload_json,created_at) VALUES (?,?,?,?,?,'plan.recalculate','proposed','{\"timezone\":\"UTC\"}',?)").run(existingId, crypto.randomUUID(), 'Existing', 1, crypto.randomUUID(), Date.now()); database.close()
    database = openCoachDatabase({ databasePath, migrationsFolder }); expect(database.sqlite.prepare('SELECT label FROM planner_actions WHERE id=?').get(existingId)).toEqual({ label: 'Existing' }); const repository = new DrizzlePlannerActionRepository(database); expect(() => repository.create({ id: crypto.randomUUID(), originMessageId: crypto.randomUUID(), label: '+4h', contextVersion: 1, type: 'plan.workspace-day-load.adjust', status: 'proposed', payload: { workspaceId: crypto.randomUUID(), dateKey: '2026-09-10', timezone: 'UTC', deltaMinutes: 240 }, result: null, createdAt: Date.now(), resolvedAt: null }, crypto.randomUUID())).not.toThrow(); expect(database.sqlite.pragma('foreign_key_check')).toEqual([]); database.close()
  })

  it('rolls back a failure after delta, recovers applying, and returns terminal actions idempotently', async () => {
    const { database, now, workspaceId, itemId } = seedPlan(join(temporary('atomic'), 'coach.db')); const repository = new DrizzlePlannerActionRepository(database); const actionId = crypto.randomUUID(); repository.create({ id: actionId, originMessageId: crypto.randomUUID(), label: '+1h', contextVersion: 1, type: 'plan.workspace-day-load.adjust', status: 'proposed', payload: { workspaceId, dateKey: '2026-09-10', timezone: 'UTC', deltaMinutes: 60 }, result: null, createdAt: now, resolvedAt: null }, crypto.randomUUID()); const planning = new PlanningService(new DrizzlePlanningRepository(database), () => now + 1); let failAfterDelta = true
    const service = new PlannerActionService({ repository, createWorkspace: async () => ({ id: 'w', name: 'W' }), createProject: async () => {}, createDeadline: () => {}, addRoutine: () => {}, adjustWorkspaceDayLoad: (input) => { const result = planning.adjustWorkspaceDayLoad(input); if (failAfterDelta) throw new Error('simulated response crash'); return result }, now: () => now + 1 })
    await expect(service.resolve(actionId, 'apply')).rejects.toThrow('simulated response crash'); expect(repository.find(actionId)?.status).toBe('proposed'); expect(database.sqlite.prepare('SELECT duration_minutes AS minutes FROM weekly_plan_items WHERE id=?').get(itemId)).toEqual({ minutes: 60 }); failAfterDelta = false; database.sqlite.prepare("UPDATE planner_actions SET status='applying' WHERE id=?").run(actionId); const applied = await service.resolve(actionId, 'apply'); expect(applied.status).toBe('applied'); expect(applied.result).toMatchObject({ revision: 2 }); expect(database.sqlite.prepare('SELECT duration_minutes AS minutes FROM weekly_plan_items WHERE id=?').get(itemId)).toEqual({ minutes: 120 }); expect(await service.resolve(actionId, 'apply')).toEqual(applied); expect(await service.resolve(actionId, 'reject')).toEqual(applied); expect(database.sqlite.prepare('SELECT duration_minutes AS minutes FROM weekly_plan_items WHERE id=?').get(itemId)).toEqual({ minutes: 120 }); database.close()
  })

  for (const type of ['plan.recalculate', 'plan.item-completion.set', 'plan.weekday-availability.set', 'plan.today-budget.set'] as const) it(`atomically rolls back and retries ${type} exactly once`, async () => {
    const { database, now, workspaceId, itemId } = seedPlan(join(temporary(type.replaceAll('.', '-')), 'coach.db')); const repository = new DrizzlePlannerActionRepository(database); const actionId = crypto.randomUUID(); const payload = type === 'plan.recalculate' ? { timezone: 'UTC' } : type === 'plan.item-completion.set' ? { workspaceId, itemId, completed: true } : type === 'plan.weekday-availability.set' ? { weekday: 4, minutes: 300, timezone: 'UTC' } : { dateKey: '2026-09-10', timezone: 'UTC', minutes: 300 }; repository.create({ id: actionId, originMessageId: crypto.randomUUID(), label: type, contextVersion: 1, type, status: 'proposed', payload, result: null, createdAt: now, resolvedAt: null }, crypto.randomUUID()); const planning = new PlanningService(new DrizzlePlanningRepository(database), () => now + 1); let fail = true; let calls = 0
    const afterDomain = <T>(operation: () => T) => { calls += 1; const result = operation(); if (fail) throw new Error('simulated response crash'); return result }
    const service = new PlannerActionService({ repository, createWorkspace: async () => ({ id: 'w', name: 'W' }), createProject: async () => {}, createDeadline: () => {}, addRoutine: () => {}, recalculatePlan: (timezone) => afterDomain(() => planning.replanWeek(timezone)), setPlanItemCompletion: (scope, id, completed) => afterDomain(() => planning.setPlanItemCompletion({ workspaceId: scope, itemId: id, completed })), setWeekdayAvailability: (input) => afterDomain(() => planning.setWeekdayAvailability(input)), setTodayBudget: (input) => afterDomain(() => planning.setTodayBudget(input)), now: () => now + 1 })
    const beforePlan = database.sqlite.prepare('SELECT revision FROM weekly_plans').get(); const beforeItem = database.sqlite.prepare('SELECT status FROM weekly_plan_items WHERE id=?').get(itemId); const beforeAvailability = database.sqlite.prepare('SELECT minutes FROM academic_availability WHERE weekday=4').get(); const beforeBudget = database.sqlite.prepare("SELECT minutes FROM daily_planning_budgets WHERE date_key='2026-09-10' AND timezone='UTC'").get()
    await expect(service.resolve(actionId, 'apply')).rejects.toThrow('simulated response crash'); expect(repository.find(actionId)?.status).toBe('proposed'); expect(database.sqlite.prepare('SELECT revision FROM weekly_plans').get()).toEqual(beforePlan); expect(database.sqlite.prepare('SELECT status FROM weekly_plan_items WHERE id=?').get(itemId)).toEqual(beforeItem); expect(database.sqlite.prepare('SELECT minutes FROM academic_availability WHERE weekday=4').get()).toEqual(beforeAvailability); expect(database.sqlite.prepare("SELECT minutes FROM daily_planning_budgets WHERE date_key='2026-09-10' AND timezone='UTC'").get()).toEqual(beforeBudget)
    fail = false; database.sqlite.prepare("UPDATE planner_actions SET status='applying' WHERE id=?").run(actionId); const applied = await service.resolve(actionId, 'apply'); expect(applied.status).toBe('applied'); const callsAfterApply = calls; expect(await service.resolve(actionId, 'apply')).toEqual(applied); expect(await service.resolve(actionId, 'reject')).toEqual(applied); expect(calls).toBe(callsAfterApply); if (type === 'plan.item-completion.set') { expect(database.sqlite.prepare('SELECT status FROM weekly_plan_items WHERE id=?').get(itemId)).toEqual({ status: 'completed' }); expect(database.sqlite.prepare('SELECT COUNT(*) AS count FROM plan_item_completion_history WHERE item_id=?').get(itemId)).toEqual({ count: 1 }) } if (type === 'plan.weekday-availability.set') expect(database.sqlite.prepare('SELECT minutes FROM academic_availability WHERE weekday=4').get()).toEqual({ minutes: 300 }); if (type === 'plan.today-budget.set') expect(database.sqlite.prepare("SELECT minutes FROM daily_planning_budgets WHERE date_key='2026-09-10' AND timezone='UTC'").get()).toEqual({ minutes: 300 }); database.close()
  })
})
