import { useEffect, useState } from 'react'
import { CheckCircle2, Map, RefreshCw } from 'lucide-react'
import type { Roadmap } from '../../shared/contracts/roadmap-contract'

export function RoadmapPanel({ workspaceId, onError }: { workspaceId: string; onError(message: string): void }) {
  const [roadmap, setRoadmap] = useState<Roadmap | null>(null)
  const [busy, setBusy] = useState(false)
  useEffect(() => { void window.coach.roadmap.get(workspaceId).then(setRoadmap).catch(() => onError('Não foi possível carregar o roadmap.')) }, [workspaceId])
  function generate(): void { setBusy(true); void window.coach.roadmap.generate(workspaceId).then(setRoadmap).catch(() => onError('Não foi possível gerar o roadmap.')).finally(() => setBusy(false)) }
  if (!roadmap) return <div className="mt-7 rounded-2xl border border-dashed border-coach-line p-4"><Map className="text-coach-green" size={20} /><p className="mt-3 text-sm font-black">Roadmap personalizado</p><p className="mt-1 text-xs leading-5 text-coach-muted">Gere módulos a partir do objetivo deste Workspace.</p><button disabled={busy} onClick={generate} className="mt-3 rounded-lg bg-coach-ink px-3 py-2 text-xs font-black text-white">{busy ? 'Gerando…' : 'Gerar roadmap'}</button></div>
  return <div className="mt-7"><div className="flex items-center justify-between"><div><p className="text-xs font-black uppercase tracking-wider text-coach-green">Roadmap v{roadmap.version}</p><h3 className="mt-1 font-display text-lg font-black">{roadmap.title}</h3></div><button disabled={busy} onClick={generate} title="Gerar nova proposta"><RefreshCw size={15} /></button></div><div className="mt-4 space-y-2">{roadmap.modules.map((module) => <div key={module.id} className={`rounded-xl border p-3 ${module.status === 'active' ? 'border-coach-green bg-coach-green/5' : 'border-coach-line bg-white/50'}`}><div className="flex gap-2"><CheckCircle2 size={15} className={module.status === 'active' ? 'text-coach-green' : 'text-coach-muted'} /><div><strong className="block text-xs">{module.position}. {module.title}</strong><span className="text-[10px] text-coach-muted">{module.estimatedMinutes} min · {module.status}</span></div></div></div>)}</div>{roadmap.status === 'proposed' && <button disabled={busy} onClick={() => { setBusy(true); void window.coach.roadmap.accept({ workspaceId, roadmapId: roadmap.id }).then(setRoadmap).catch(() => onError('Não foi possível aceitar o roadmap.')).finally(() => setBusy(false)) }} className="mt-4 w-full rounded-lg bg-coach-orange px-3 py-2 text-xs font-black text-white">Aceitar proposta</button>}</div>
}
