import { createCipheriv, createDecipheriv, createHash, randomBytes, randomUUID, timingSafeEqual } from 'node:crypto';
import type { AuthBoundary, AuthTokens } from '../auth/types.js';
import type { Database } from '../database/client.js';
import type { TenantContext } from '../database/tenant-transaction.js';

const hash = (value: string) => createHash('sha256').update(value).digest('hex');
export class RefreshBroker {
  private readonly key: Buffer;
  constructor(private readonly database: Database, private readonly auth: AuthBoundary, secret: string, private readonly ttlSeconds: number, private readonly leaseSeconds = 30, private readonly providerTimeoutMs = 20_000, private readonly heartbeatMs = 5_000) { this.key=createHash('sha256').update(secret).digest(); }

  async reserve(context: TenantContext, requestId: string, refreshToken: string, recoverySecret: string): Promise<{ capability: string; expiresAt: string }> {
    const generated=randomBytes(32).toString('base64url'); const expiresAt=new Date(Date.now()+this.ttlSeconds*1000);
    return this.database.begin(async (tx) => { await tx`delete from auth_refresh_reservations where expires_at<=now()`; const [existing]=await tx<{refresh_identity_hash:string;recovery_secret_hash:string;user_id:string;tenant_id:string;app_session_id:string;encrypted_capability:string;expires_at:Date}[]>`select refresh_identity_hash,recovery_secret_hash,user_id,tenant_id,app_session_id,encrypted_capability,expires_at from auth_refresh_reservations where request_id=${requestId}::uuid for update`; if(existing){if(existing.refresh_identity_hash!==hash(refreshToken)||existing.recovery_secret_hash!==hash(recoverySecret)||existing.user_id!==context.userId||existing.tenant_id!==context.tenantId||existing.app_session_id!==context.sessionId)throw new Error('refresh_reservation_reused');return{capability:this.decryptText(existing.encrypted_capability),expiresAt:existing.expires_at.toISOString()};} await tx`insert into auth_refresh_reservations(request_id,refresh_identity_hash,recovery_secret_hash,capability_hash,encrypted_capability,tenant_id,user_id,app_session_id,expires_at) values(${requestId}::uuid,${hash(refreshToken)},${hash(recoverySecret)},${hash(generated)},${this.encryptText(generated)},${context.tenantId}::uuid,${context.userId}::uuid,${context.sessionId}::uuid,${expiresAt})`; return{capability:generated,expiresAt:expiresAt.toISOString()}; });
  }
  async recoverReservation(requestId:string,refreshToken:string,recoverySecret:string){const [row]=await this.database<{refresh_identity_hash:string;recovery_secret_hash:string;encrypted_capability:string;expires_at:Date;revoked_at:Date|null}[]>`select r.refresh_identity_hash,r.recovery_secret_hash,r.encrypted_capability,r.expires_at,s.revoked_at from auth_refresh_reservations r join app_sessions s on s.id=r.app_session_id where r.request_id=${requestId}::uuid`;if(!row||row.revoked_at||row.expires_at.getTime()<=Date.now()||!equalHash(row.refresh_identity_hash,hash(refreshToken))||!equalHash(row.recovery_secret_hash,hash(recoverySecret)))throw new Error('invalid_refresh_recovery_proof');return{capability:this.decryptText(row.encrypted_capability),expiresAt:row.expires_at.toISOString()};}

  async execute(requestId:string, refreshToken:string, capability:string):Promise<AuthTokens>{
    const owner=randomUUID(); const identity=hash(refreshToken); const capabilityHash=hash(capability);
    for(let attempt=0;attempt<30;attempt+=1){
      const claimed=await this.claim(requestId,identity,capabilityHash,owner);
      if(claimed.result) return claimed.result;
      if(claimed.owner){ const controller=new AbortController(); const timeout=setTimeout(()=>controller.abort(new Error('refresh_provider_timeout')),this.providerTimeoutMs); const heartbeat=setInterval(()=>void this.heartbeat(requestId,owner).catch(()=>controller.abort(new Error('refresh_lease_lost'))),this.heartbeatMs); try { const tokens=await this.auth.refresh(refreshToken,controller.signal); await this.complete(requestId,identity,capabilityHash,owner,tokens); return tokens; } catch(error){ await this.release(requestId,owner); throw error; } finally {clearTimeout(timeout);clearInterval(heartbeat);} }
      await new Promise((resolve)=>setTimeout(resolve,50));
    }
    throw new Error('refresh_operation_busy');
  }

  private async claim(requestId:string,identity:string,capabilityHash:string,owner:string):Promise<{owner:boolean;result?:AuthTokens}>{
    return this.database.begin(async(tx)=>{ const [row]=await tx<{capability_hash:string;refresh_identity_hash:string;state:string;lease_expires_at:Date|null;encrypted_result:string|null;expires_at:Date;revoked_at:Date|null}[]>`select r.capability_hash,r.refresh_identity_hash,r.state,r.lease_expires_at,r.encrypted_result,r.expires_at,s.revoked_at from auth_refresh_reservations r join app_sessions s on s.id=r.app_session_id where r.request_id=${requestId}::uuid for update`; if(!row||row.revoked_at||row.expires_at.getTime()<=Date.now()||row.refresh_identity_hash!==identity||!equalHash(row.capability_hash,capabilityHash)) throw new Error('invalid_refresh_capability'); if(row.state==='completed'&&row.encrypted_result) return {owner:false,result:this.decrypt(row.encrypted_result)}; if(row.state==='processing'&&row.lease_expires_at&&row.lease_expires_at.getTime()>Date.now()) return {owner:false}; await tx`update auth_refresh_reservations set state='processing',lease_owner=${owner}::uuid,lease_expires_at=now()+(${this.leaseSeconds}::text||' seconds')::interval where request_id=${requestId}::uuid`; return {owner:true}; });
  }
  private async complete(requestId:string,identity:string,capabilityHash:string,owner:string,tokens:AuthTokens){const result=await this.database`update auth_refresh_reservations set state='completed',encrypted_result=${this.encrypt(tokens)},completed_at=now(),lease_owner=null,lease_expires_at=null where request_id=${requestId}::uuid and refresh_identity_hash=${identity} and capability_hash=${capabilityHash} and lease_owner=${owner}::uuid and expires_at>now()`;if(result.count!==1)throw new Error('refresh_lease_lost');}
  private async release(requestId:string,owner:string){await this.database`update auth_refresh_reservations set state='reserved',lease_owner=null,lease_expires_at=null where request_id=${requestId}::uuid and lease_owner=${owner}::uuid`;}
  private async heartbeat(requestId:string,owner:string){const result=await this.database`update auth_refresh_reservations set lease_expires_at=now()+(${this.leaseSeconds}::text||' seconds')::interval where request_id=${requestId}::uuid and state='processing' and lease_owner=${owner}::uuid and expires_at>now()`;if(result.count!==1)throw new Error('refresh_lease_lost');}
  private encrypt(tokens:AuthTokens){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',this.key,iv);const body=Buffer.concat([cipher.update(JSON.stringify(tokens)),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString('base64url');}
  private decrypt(value:string){const raw=Buffer.from(value,'base64url');const decipher=createDecipheriv('aes-256-gcm',this.key,raw.subarray(0,12));decipher.setAuthTag(raw.subarray(12,28));return JSON.parse(Buffer.concat([decipher.update(raw.subarray(28)),decipher.final()]).toString('utf8')) as AuthTokens;}
  private encryptText(value:string){const iv=randomBytes(12);const cipher=createCipheriv('aes-256-gcm',this.key,iv);const body=Buffer.concat([cipher.update(value),cipher.final()]);return Buffer.concat([iv,cipher.getAuthTag(),body]).toString('base64url');}
  private decryptText(value:string){const raw=Buffer.from(value,'base64url');const decipher=createDecipheriv('aes-256-gcm',this.key,raw.subarray(0,12));decipher.setAuthTag(raw.subarray(12,28));return Buffer.concat([decipher.update(raw.subarray(28)),decipher.final()]).toString('utf8');}
}
function equalHash(left:string,right:string){const a=Buffer.from(left,'hex');const b=Buffer.from(right,'hex');return a.length===b.length&&timingSafeEqual(a,b);}
