import { sql } from 'drizzle-orm'
import { check, index, integer, real, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core'
import { workspaces } from './workspaces'
import { exercises } from './exercises'

export const concepts = sqliteTable('concepts', {
  id: text('id').primaryKey(), workspaceId: text('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), stableKey: text('stable_key'), canonicalName: text('canonical_name').notNull(), domain: text('domain').notNull(), parentConceptId: text('parent_concept_id'), metadataJson: text('metadata_json').notNull().default('{}'), createdAt: integer('created_at').notNull(), updatedAt: integer('updated_at').notNull(),
}, (table) => [uniqueIndex('concepts_workspace_domain_name_unique').on(table.workspaceId, table.domain, table.canonicalName), uniqueIndex('concepts_workspace_domain_key_unique').on(table.workspaceId, table.domain, table.stableKey), index('concepts_parent_idx').on(table.parentConceptId)])

export const conceptAliases = sqliteTable('concept_aliases', {
  id: text('id').primaryKey(), conceptId: text('concept_id').notNull().references(() => concepts.id, { onDelete: 'cascade' }), alias: text('alias').notNull(), normalizedAlias: text('normalized_alias').notNull(), provenance: text('provenance').notNull(), createdAt: integer('created_at').notNull(),
}, (table) => [uniqueIndex('concept_aliases_concept_normalized_unique').on(table.conceptId, table.normalizedAlias)])

export const topicConcepts = sqliteTable('topic_concepts', {
  id: text('id').primaryKey(), workspaceId: text('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), roadmapId: text('roadmap_id').notNull(), moduleId: text('module_id').notNull(), topicId: text('topic_id').notNull(), conceptId: text('concept_id').references(() => concepts.id, { onDelete: 'set null' }), provenance: text('provenance').notNull(), confidence: real('confidence').notNull(), mappingStatus: text('mapping_status').notNull(), createdAt: integer('created_at').notNull(), updatedAt: integer('updated_at').notNull(),
}, (table) => [uniqueIndex('topic_concepts_topic_concept_unique').on(table.workspaceId, table.topicId, table.conceptId), index('topic_concepts_concept_idx').on(table.conceptId), check('topic_concepts_confidence_check', sql`${table.confidence} >= 0 and ${table.confidence} <= 1`), check('topic_concepts_status_check', sql`${table.mappingStatus} in ('mapped','unknown','rejected')`)])

export const assessmentIntents = sqliteTable('assessment_intents', {
  id: text('id').primaryKey(), workspaceId: text('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), conceptId: text('concept_id').notNull().references(() => concepts.id, { onDelete: 'cascade' }), stableKey: text('stable_key'), kind: text('kind').notNull(), objective: text('objective').notNull(), evidenceType: text('evidence_type'), difficulty: text('difficulty'), prerequisiteConceptIdsJson: text('prerequisite_concept_ids_json').notNull().default('[]'), createdAt: integer('created_at').notNull(), updatedAt: integer('updated_at').notNull(),
}, (table) => [uniqueIndex('assessment_intents_identity_unique').on(table.workspaceId, table.conceptId, table.kind, table.objective)])

export const assessmentVariants = sqliteTable('assessment_variants', {
  id: text('id').primaryKey(), workspaceId: text('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), intentId: text('intent_id').notNull().references(() => assessmentIntents.id, { onDelete: 'cascade' }), environment: text('environment').notNull(), sourceRef: text('source_ref').notNull(), sourceRevision: text('source_revision').notNull(), difficulty: text('difficulty').notNull(), prerequisiteConceptIdsJson: text('prerequisite_concept_ids_json').notNull().default('[]'), publicMetadataJson: text('public_metadata_json').notNull().default('{}'), publicPayloadJson: text('public_payload_json').notNull().default('{}'), evaluatorJson: text('evaluator_json').notNull().default('{}'), createdAt: integer('created_at').notNull(), updatedAt: integer('updated_at').notNull(),
}, (table) => [uniqueIndex('assessment_variants_source_unique').on(table.workspaceId, table.intentId, table.environment, table.sourceRef, table.sourceRevision), check('assessment_variants_difficulty_check', sql`${table.difficulty} in ('introductory','standard','challenge')`)])

export const learningAttempts = sqliteTable('learning_attempts', {
  id: text('id').primaryKey(), workspaceId: text('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), conceptId: text('concept_id').references(() => concepts.id, { onDelete: 'set null' }), assessmentIntentId: text('assessment_intent_id').references(() => assessmentIntents.id, { onDelete: 'set null' }), assessmentVariantId: text('assessment_variant_id').references(() => assessmentVariants.id, { onDelete: 'set null' }), environment: text('environment').notNull(), sourceRef: text('source_ref').notNull(), sourceRevision: text('source_revision').notNull(), firstSeenAt: integer('first_seen_at'), idempotencyKey: text('idempotency_key').notNull(), payloadHash: text('payload_hash').notNull(), outcome: text('outcome').notNull(), correct: integer('correct', { mode: 'boolean' }), independent: integer('independent', { mode: 'boolean' }).notNull(), reasoningQuality: text('reasoning_quality').notNull(), occurredAt: integer('occurred_at').notNull(), createdAt: integer('created_at').notNull(),
}, (table) => [uniqueIndex('learning_attempts_workspace_environment_key_unique').on(table.workspaceId, table.environment, table.idempotencyKey), index('learning_attempts_concept_time_idx').on(table.conceptId, table.occurredAt, table.id), check('learning_attempts_environment_check', sql`${table.environment} in ('checkpoint','exercise','study_interactive','practice','review')`)])

export const learningEvidence = sqliteTable('learning_evidence', {
  id: text('id').primaryKey(), attemptId: text('attempt_id').notNull().references(() => learningAttempts.id, { onDelete: 'cascade' }), conceptId: text('concept_id').references(() => concepts.id, { onDelete: 'set null' }), type: text('type').notNull(), strength: text('strength').notNull(), ordinal: integer('ordinal').notNull(), metadataJson: text('metadata_json').notNull().default('{}'), occurredAt: integer('occurred_at').notNull(), createdAt: integer('created_at').notNull(),
}, (table) => [uniqueIndex('learning_evidence_attempt_type_ordinal_unique').on(table.attemptId, table.type, table.ordinal), index('learning_evidence_concept_time_idx').on(table.conceptId, table.occurredAt, table.id), check('learning_evidence_strength_check', sql`${table.strength} in ('none','weak','moderate','strong')`)])

export const conceptMemories = sqliteTable('concept_memories', {
  workspaceId: text('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), conceptId: text('concept_id').notNull().references(() => concepts.id, { onDelete: 'cascade' }), performance: text('performance').notNull(), evidenceQuantity: text('evidence_quantity').notNull(), independence: text('independence').notNull(), diversity: text('diversity').notNull(), recency: text('recency').notNull(), retention: text('retention').notNull(), confidence: text('confidence').notNull(), successfulRetrievals: integer('successful_retrievals').notNull().default(0), independentSuccesses: integer('independent_successes').notNull().default(0), errorCount: integer('error_count').notNull().default(0), helpEvents: integer('help_events').notNull().default(0), environmentCount: integer('environment_count').notNull().default(0), intervalDays: integer('interval_days').notNull().default(1), lastEvidenceAt: integer('last_evidence_at'), nextReviewAt: integer('next_review_at'), updatedAt: integer('updated_at').notNull(),
}, (table) => [uniqueIndex('concept_memories_workspace_concept_unique').on(table.workspaceId, table.conceptId), index('concept_memories_next_review_idx').on(table.workspaceId, table.nextReviewAt)])

export const exerciseHelpEvents = sqliteTable('exercise_help_events', {
  requestId: text('request_id').primaryKey(), workspaceId: text('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), exerciseId: text('exercise_id').notNull().references(() => exercises.id, { onDelete: 'cascade' }), type: text('type').notNull(), createdAt: integer('created_at').notNull(),
}, (table) => [index('exercise_help_events_exercise_created_idx').on(table.workspaceId, table.exerciseId, table.createdAt), check('exercise_help_events_type_check', sql`${table.type} in ('hint_requested','coach_help_requested','worked_example_shown','solution_revealed')`)])

export const reviewSessions = sqliteTable('review_sessions', {
  id: text('id').primaryKey(), workspaceId: text('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), targetSize: integer('target_size').notNull().default(8), status: text('status').notNull(), startedAt: integer('started_at').notNull(), completedAt: integer('completed_at'), updatedAt: integer('updated_at').notNull(),
}, (table) => [index('review_sessions_workspace_updated_idx').on(table.workspaceId, table.updatedAt), check('review_sessions_target_check', sql`${table.targetSize} between 4 and 12`), check('review_sessions_status_check', sql`${table.status} in ('active','completed','preparation')`)])

export const reviewItems = sqliteTable('review_items', {
  id: text('id').primaryKey(), sessionId: text('session_id').notNull().references(() => reviewSessions.id, { onDelete: 'cascade' }), position: integer('position').notNull(), conceptId: text('concept_id').notNull().references(() => concepts.id, { onDelete: 'restrict' }), assessmentIntentId: text('assessment_intent_id').notNull().references(() => assessmentIntents.id, { onDelete: 'restrict' }), assessmentVariantId: text('assessment_variant_id').notNull().references(() => assessmentVariants.id, { onDelete: 'restrict' }), sourceTopicId: text('source_topic_id'), sourceExerciseId: text('source_exercise_id').references(() => exercises.id, { onDelete: 'set null' }), selectionReason: text('selection_reason').notNull(), status: text('status').notNull().default('pending'), attempts: integer('attempts').notNull().default(0), helpCount: integer('help_count').notNull().default(0), result: text('result'), answerJson: text('answer_json'), memoryBeforeJson: text('memory_before_json'), memoryAfterJson: text('memory_after_json'), learningAttemptId: text('learning_attempt_id').references(() => learningAttempts.id, { onDelete: 'set null' }), firstSeenAt: integer('first_seen_at').notNull(), answeredAt: integer('answered_at'), createdAt: integer('created_at').notNull(), updatedAt: integer('updated_at').notNull(),
}, (table) => [uniqueIndex('review_items_session_position_unique').on(table.sessionId, table.position), uniqueIndex('review_items_session_variant_unique').on(table.sessionId, table.assessmentVariantId), index('review_items_concept_answered_idx').on(table.conceptId, table.answeredAt)])
