import { sql } from 'drizzle-orm'
import { check, index, integer, sqliteTable, text, uniqueIndex } from 'drizzle-orm/sqlite-core'
import { workspaces } from './workspaces'

export const exerciseSets = sqliteTable('exercise_sets', {
  id: text('id').primaryKey(), workspaceId: text('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), roadmapId: text('roadmap_id').notNull(), moduleId: text('module_id').notNull(), topicId: text('topic_id').notNull(), lessonId: text('lesson_id').notNull(), contentRevision: integer('content_revision').notNull().default(1), inputHash: text('input_hash').notNull().default('legacy-unavailable'), status: text('status', { enum: ['generating', 'ready', 'waiting_for_provider', 'failed_retryable'] }).notNull(), providerId: text('provider_id'), modelId: text('model_id'), generationAttempts: integer('generation_attempts').notNull().default(0), retryAfter: integer('retry_after'), lastErrorCode: text('last_error_code'), createdAt: integer('created_at').notNull(), updatedAt: integer('updated_at').notNull(),
}, (table) => [uniqueIndex('exercise_sets_workspace_topic_unique').on(table.workspaceId, table.topicId), index('exercise_sets_status_retry_idx').on(table.status, table.retryAfter), check('exercise_sets_status_check', sql`${table.status} in ('generating','ready','waiting_for_provider','failed_retryable')`)])

export const exercises = sqliteTable('exercises', {
  id: text('id').primaryKey(), setId: text('set_id').notNull().references(() => exerciseSets.id, { onDelete: 'cascade' }), position: integer('position').notNull(), kind: text('kind', { enum: ['PROGRAMMING_PROBLEM', 'FIX_CODE', 'COMPLETE_CODE', 'PREDICT_OUTPUT'] }).notNull(), difficulty: text('difficulty', { enum: ['introductory', 'standard', 'challenge'] }).notNull(), title: text('title').notNull(), statement: text('statement').notNull(), inputDescription: text('input_description').notNull(), outputDescription: text('output_description').notNull(), language: text('language', { enum: ['python', 'c', 'java'] }).notNull(), starterCode: text('starter_code').notNull(), predictionPrompt: text('prediction_prompt'), codeToObserve: text('code_to_observe'), requiredForTopicCompletion: integer('required_for_topic_completion', { mode: 'boolean' }).notNull().default(false), publicTestsJson: text('public_tests_json').notNull(), privateTestsJson: text('private_tests_json').notNull(), referenceSolution: text('reference_solution'), expectedPrediction: text('expected_prediction'), hint: text('hint').notNull(), createdAt: integer('created_at').notNull(),
}, (table) => [uniqueIndex('exercises_set_position_unique').on(table.setId, table.position), index('exercises_set_idx').on(table.setId), check('exercises_kind_check', sql`${table.kind} in ('PROGRAMMING_PROBLEM','FIX_CODE','COMPLETE_CODE','PREDICT_OUTPUT')`), check('exercises_difficulty_check', sql`${table.difficulty} in ('introductory','standard','challenge')`)])

export const exerciseProgress = sqliteTable('exercise_progress', {
  workspaceId: text('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), exerciseId: text('exercise_id').notNull().references(() => exercises.id, { onDelete: 'cascade' }), status: text('status', { enum: ['not_started', 'in_progress', 'passed'] }).notNull().default('not_started'), currentCode: text('current_code').notNull(), attempts: integer('attempts').notNull().default(0), lastRunJson: text('last_run_json'), lastSubmissionJson: text('last_submission_json'), passedTests: integer('passed_tests').notNull().default(0), totalTests: integer('total_tests').notNull().default(0), helpUsed: integer('help_used', { mode: 'boolean' }).notNull().default(false), firstTrySuccess: integer('first_try_success', { mode: 'boolean' }).notNull().default(false), helpCount: integer('help_count').notNull().default(0), passedAt: integer('passed_at'), updatedAt: integer('updated_at').notNull(),
}, (table) => [uniqueIndex('exercise_progress_workspace_exercise_unique').on(table.workspaceId, table.exerciseId), check('exercise_progress_status_check', sql`${table.status} in ('not_started','in_progress','passed')`)])

export const exerciseAttempts = sqliteTable('exercise_attempts', {
  id: text('id').primaryKey(), workspaceId: text('workspace_id').notNull().references(() => workspaces.id, { onDelete: 'cascade' }), exerciseId: text('exercise_id').notNull().references(() => exercises.id, { onDelete: 'cascade' }), idempotencyKey: text('idempotency_key').notNull(), sourceRevision: text('source_revision').notNull(), code: text('code').notNull(), prediction: text('prediction'), status: text('status', { enum: ['passed', 'failed', 'compile_error', 'runtime_error', 'timed_out'] }).notNull(), publicResultJson: text('public_result_json').notNull(), privateResultJson: text('private_result_json').notNull(), durationMs: integer('duration_ms').notNull(), createdAt: integer('created_at').notNull(),
}, (table) => [uniqueIndex('exercise_attempts_workspace_key_unique').on(table.workspaceId, table.idempotencyKey), index('exercise_attempts_exercise_created_idx').on(table.exerciseId, table.createdAt)])
