import { describe, expect, it } from 'vitest'
import { deriveDailyPlan, planActionLabel } from '../../src/application/study-workspaces/daily-plan'
import type { Roadmap } from '../../src/shared/contracts/roadmap-contract'
import type { StudyProgressState } from '../../src/shared/contracts/study-progress-contract'

const moduleId = '00000000-0000-4000-8000-000000000003'
const roadmap: Roadmap = { id: '00000000-0000-4000-8000-000000000002', workspaceId: '00000000-0000-4000-8000-000000000001', title: 'C', status: 'accepted', version: 1, providerId: null, modelId: null, createdAt: 1, updatedAt: 1, modules: [{ id: moduleId, title: 'Memória e dados', objective: 'Aplicar recursos de C', estimatedMinutes: 120, position: 1, status: 'active', topics: ['Ponteiros', 'Structs', 'Arquivos'], outcomes: [], practice: 'Programa C', completionCriteria: ['Executar'], resources: [] }] }
const progress: StudyProgressState = { workspaceId: roadmap.workspaceId, roadmapId: roadmap.id, moduleId, topicId: `${moduleId}:Ponteiros`, lessonId: 'lesson', checkpointId: null, topicStatuses: { [`${moduleId}:Ponteiros`]: 'IN_PROGRESS' }, lessonPositions: {}, currentPosition: null, updatedAt: 1 }

describe('daily Roadmap plan', () => {
  it('uses real topics and contains none of the generic checklist', () => { let id = 0; const plan = deriveDailyPlan({ workspaceId: roadmap.workspaceId, roadmap, progress, availableMinutes: 95, urgency: 'attention', difficultyTopicIds: new Set(), startMinutes: 18 * 60 }, [], () => `id-${++id}`); expect(plan.map((item) => item.title)).toEqual(['Ponteiros / revisão', 'Ponteiros / exercícios', 'Structs / introdução']); expect(plan.every((item) => item.moduleId === moduleId && item.topicId?.startsWith(moduleId))).toBe(true); expect(plan.map((item) => item.title).join(' ')).not.toMatch(/Revisar fundamentos|Praticar o conceito principal|Registrar dúvidas/) })
  it('assigns order, clock and activity-specific durations', () => { let id = 0; const plan = deriveDailyPlan({ workspaceId: roadmap.workspaceId, roadmap, progress, availableMinutes: 95, urgency: 'attention', difficultyTopicIds: new Set(), startMinutes: 1080 }, [], () => `id-${++id}`); expect(plan.map((item) => [item.scheduledStartMinutes, item.durationMinutes])).toEqual([[1080, 25], [1105, 40], [1145, 30]]) })
  it('preserves completed work when recalculated', () => { let id = 0; const first = deriveDailyPlan({ workspaceId: roadmap.workspaceId, roadmap, progress, availableMinutes: 65, urgency: 'stable', difficultyTopicIds: new Set(), startMinutes: 1080 }, [], () => `id-${++id}`); const completed = [{ ...first[0]!, status: 'completed' as const }]; const next = deriveDailyPlan({ workspaceId: roadmap.workspaceId, roadmap, progress, availableMinutes: 65, urgency: 'urgent', difficultyTopicIds: new Set(), startMinutes: 1080 }, completed, () => `id-${++id}`); expect(next[0]).toMatchObject({ id: first[0]!.id, status: 'completed' }) })
  it('creates an Overview action from the active plan item', () => { expect(planActionLabel({ id: '1', title: 'Ponteiros / revisão', durationMinutes: 25, position: 1, status: 'active', moduleId, topicId: `${moduleId}:Ponteiros`, activityType: 'review', scheduledStartMinutes: 1080 })).toBe('Responder revisão: Ponteiros') })
})
