import { describe, expect, it } from 'vitest'
import { EventWorkspaceLinkService } from '../../src/application/academic-life/event-workspace-link-service'

function event(overrides: Record<string, unknown> = {}) { return { id: '00000000-0000-4000-8000-000000000001', kind: 'event', status: 'active', title: 'Prova POO', details: JSON.stringify({ schema: 'academic-event/v1', subject: 'POO', eventKind: 'exam', sourceText: 'Tenho prova de POO dia 14' }), workspaceId: null, startsAt: null, endsAt: 1000, expiresAt: 1000, timezone: 'UTC', weekday: null, minutes: null, shareWithAi: false, provenance: { source: 'conversation', reference: null }, replacesId: null, replacedById: null, createdAt: 1, updatedAt: 1, resolvedAt: null, archivedAt: null, ...overrides } as any }
const activeWorkspace = { id: '00000000-0000-4000-8000-000000000002', name: 'Java', objective: '', status: 'active', createdAt: 1, updatedAt: 1, lastOpenedAt: null, archivedAt: null } as const

describe('EventWorkspaceLinkService', () => {
  it('links and unlinks only through the atomic repository operation', async () => { let current = event(); const replacements: any[] = []; const repository: any = { findEvent: (id: string) => id === current.id ? current : null, findReplacement: () => null, findWorkspace: async () => activeWorkspace, replaceAndConfirmAlias: (input: any) => { replacements.push(input); current = event({ ...input.event, id: crypto.randomUUID(), workspaceId: input.workspaceId, replacesId: input.event.id }); return current } }; const service = new EventWorkspaceLinkService(repository); const linked = await service.link(current.id, activeWorkspace.id, 'POO'); expect(linked.workspaceId).toBe(activeWorkspace.id); expect(replacements[0].event).toMatchObject({ details: expect.stringContaining('sourceText'), provenance: { source: 'conversation', reference: null } }); const unlinked = await service.link(linked.id, null); expect(unlinked.workspaceId).toBeNull(); expect(replacements).toHaveLength(2) })
  it.each([null, { ...activeWorkspace, status: 'archived' }])('rejects missing or archived workspace ownership', async (workspace) => { const repository: any = { findEvent: () => event(), findReplacement: () => null, findWorkspace: async () => workspace, replaceAndConfirmAlias: () => { throw new Error('must not save') } }; await expect(new EventWorkspaceLinkService(repository).link(event().id, activeWorkspace.id, 'POO')).rejects.toThrow('not found or archived') })
  it('rejects inactive events', async () => { const repository: any = { findEvent: () => event({ status: 'archived' }), findReplacement: () => null, findWorkspace: async () => null, replaceAndConfirmAlias: () => null }; await expect(new EventWorkspaceLinkService(repository).link(event().id, null)).rejects.toThrow('no longer active') })
  it('returns an already linked replacement on retry', async () => { const replacement = event({ id: '00000000-0000-4000-8000-000000000003', workspaceId: activeWorkspace.id, replacesId: event().id }); const repository: any = { findEvent: () => event({ replacedById: replacement.id, status: 'archived' }), findReplacement: () => replacement, findWorkspace: async () => activeWorkspace, replaceAndConfirmAlias: () => { throw new Error('must be idempotent') } }; await expect(new EventWorkspaceLinkService(repository).link(event().id, activeWorkspace.id, 'POO')).resolves.toBe(replacement) })
  it('does not expose a link if the atomic alias operation fails', async () => { const repository: any = { findEvent: () => event(), findReplacement: () => null, findWorkspace: async () => activeWorkspace, replaceAndConfirmAlias: () => { throw new Error('alias failed') } }; await expect(new EventWorkspaceLinkService(repository).link(event().id, activeWorkspace.id, 'POO')).rejects.toThrow('alias failed') })
})
