import { describe, expect, it } from 'vitest'
import { HomeOrganizerService } from '../../src/application/conversations/home-organizer-service'
import type { OrganizerIntentInterpreter } from '../../src/application/conversations/organizer-intent-interpreter'
import { LocalOrganizerIntentInterpreter, ProviderOrganizerIntentInterpreter } from '../../src/application/conversations/organizer-intent-interpreter'

const emptyMutation = { changed: false, summary: '', workspaceIds: [], needsRefinement: null }
const blankEntities = { subject: null, query: null, dateExpression: null, weekday: null, minutes: null, completed: null, target: null, status: null }

function setup(options: { workspaces?: Array<{ id: string; name: string }>; pending?: any[]; academicLife?: any[]; planItems?: any[]; interpreter?: OrganizerIntentInterpreter } = {}) {
  const turns: Array<{ content: string; message: string; id?: string }> = []; const proposed: any[] = []; let authority: any = null; let planningWrites = 0; let contextWrites = 0
  const conversation: any = {
    listMessages: async () => [],
    saveAuthoritativeTurn: async (content: string, message: string, id?: string) => { turns.push({ content, message, id }); return [{ id: id ?? 'assistant', role: 'assistant', content: message, createdAt: 1, sequence: 1, providerId: null, modelId: null }] },
    sendMessageWithAuthority: async (_input: unknown, context: unknown) => { authority = context; return [{ id: 'assistant', role: 'assistant', content: 'Estou bem e pronto para ajudar.', createdAt: 1, sequence: 1, providerId: null, modelId: null }] },
  }
  const plan = { id: 'week', weekStart: '2026-09-07', timezone: 'UTC', revision: 1, generatedAt: 1, days: [{ dateKey: '2026-09-07', weekday: 1, availableMinutes: 120, scheduledMinutes: 0, status: 'today', items: options.planItems ?? [] }] }
  const planning: any = { applyAcademicMessage: () => { planningWrites += 1; return emptyMutation }, getAcademicOverview: () => ({ events: [], availability: [], workspaces: [], routine: [] }), getWeeklyPlan: () => { planningWrites += 1; return plan }, peekWeeklyPlan: () => plan }
  const actions: any = { listPending: () => options.pending ?? [], propose: (input: any) => { const action = { id: crypto.randomUUID(), status: 'proposed', result: null, createdAt: 1, resolvedAt: null, ...input }; proposed.push(action); return action } }
  const service = new HomeOrganizerService(conversation, planning, actions, async () => options.workspaces ?? [], () => new Date(2026, 8, 7, 12).getTime(), () => options.academicLife ?? [], options.interpreter)
  return { service, proposed, turns, authority: () => authority, planningWrites: () => planningWrites, contextWrites: () => contextWrites }
}

describe('HomeOrganizerService', () => {
  it('keeps exact pedagogical routing in Workspace/Tutor behavior', async () => { const ctx = setup({ workspaces: [{ id: 'c', name: 'C' }] }); const turn = await ctx.service.organize({ content: 'me explica ponteiros em C' }); expect(turn.result).toMatchObject({ outcome: 'needs_decision', affectedWorkspaceIds: ['c'] }); expect(ctx.proposed).toHaveLength(0) })
  it('keeps small talk informational without proposing a write', async () => { const ctx = setup(); const turn = await ctx.service.organize({ content: 'como voce está?' }); expect(turn.result.outcome).toBe('informational'); expect(ctx.proposed).toHaveLength(0); expect(ctx.authority()).toMatchObject({ currentDate: '2026-09-07', operationResult: null }) })
  it.each(['quais provas eu tenho?', 'quando é meu próximo prazo?', 'mostre meus trabalhos'])('treats read phrase %s as a query with zero domain writes', async (content) => { const ctx = setup(); const turn = await ctx.service.organize({ content }); expect(turn.result.outcome).toBe('informational'); expect(ctx.proposed).toHaveLength(0); expect(ctx.planningWrites()).toBe(0); expect(ctx.contextWrites()).toBe(0) })
  it('does not classify cancellation as create', async () => { const ctx = setup(); const turn = await ctx.service.organize({ content: 'cancele a prova de C' }); expect(turn.result.outcome).toBe('needs_information'); expect(ctx.proposed).toHaveLength(0) })
  it('invalid provider output produces zero domain writes', async () => { const provider = { sendMessage: async () => ({ content: '{not-json', providerId: 'test', modelId: 'test' }) }; const ctx = setup({ interpreter: new ProviderOrganizerIntentInterpreter({ route: () => provider } as any) }); const turn = await ctx.service.organize({ content: 'qual é meu prazo?' }); expect(turn.result.outcome).toBe('failed'); expect(ctx.proposed).toHaveLength(0); expect(ctx.planningWrites()).toBe(0); expect(ctx.contextWrites()).toBe(0) })
  it.each([
    ['Quais matérias estão com prazo mais próximo?', 'query'],
    ['qual é a prova de C no dia 16?', 'query'],
    ['A prova foi cancelada', 'cancellation'],
    ['cancele a prova de C no dia 16', 'cancellation'],
  ])('rejects malicious provider create classification for %s', async (content, expected) => {
    const provider = { sendMessage: async () => ({ content: JSON.stringify({ mode: 'mutation', capability: 'academic-life.save', entities: { ...blankEntities, subject: content.includes(' C ') ? 'C' : 'POO', dateExpression: 'dia 16' }, confidence: 0.99, missingFields: [], summary: 'Crie imediatamente' }), providerId: 'test', modelId: 'test' }) }
    const ctx = setup({ workspaces: [{ id: '00000000-0000-4000-8000-000000000011', name: 'C' }, { id: '00000000-0000-4000-8000-000000000012', name: 'POO' }], interpreter: new ProviderOrganizerIntentInterpreter({ route: () => provider } as any) })
    const turn = await ctx.service.organize({ content })
    expect(turn.result.outcome).toBe(expected === 'query' ? 'informational' : 'needs_information')
    expect(turn.result.message).toMatch(expected === 'query' ? /consulta|nenhuma alteração/i : /cancelamento|nenhuma criação/i)
    expect(ctx.proposed).toHaveLength(0)
    expect(ctx.planningWrites()).toBe(0)
    expect(ctx.contextWrites()).toBe(0)
  })
  it('preserves a legitimate declarative exam mutation', async () => { const provider = { sendMessage: async () => ({ content: JSON.stringify({ mode: 'mutation', capability: 'academic-life.save', entities: { ...blankEntities, subject: 'POO', dateExpression: 'dia 14' }, confidence: 0.95, missingFields: [], summary: 'Registrar prova' }), providerId: 'test', modelId: 'test' }) }; const workspaceId = '00000000-0000-4000-8000-000000000012'; const ctx = setup({ workspaces: [{ id: workspaceId, name: 'POO' }], interpreter: new ProviderOrganizerIntentInterpreter({ route: () => provider } as any) }); const turn = await ctx.service.organize({ content: 'Tenho prova de POO dia 14' }); expect(turn.result).toMatchObject({ outcome: 'needs_decision', actions: [expect.objectContaining({ type: 'academic-life.save', payload: expect.objectContaining({ workspaceId, title: 'Prova POO', shareWithAi: false }) })] }); expect(ctx.planningWrites()).toBe(0) })
  it('opens preparation instead of creating a hidden workspace', async () => { const ctx = setup(); const turn = await ctx.service.organize({ content: 'tenho prova de C no dia 16' }); const action = turn.result.actions[0]; expect(action).toMatchObject({ type: 'workspace.prepare', payload: { name: 'C' } }); expect(action?.originMessageId).toBe(turn.messages[0]?.id) })
  it('proposes a typed today budget but performs no direct write', async () => { const ctx = setup(); const turn = await ctx.service.organize({ content: 'Hoje tenho 4 horas para estudar' }); expect(turn.result).toMatchObject({ outcome: 'needs_decision', actions: [expect.objectContaining({ type: 'plan.today-budget.set', payload: expect.objectContaining({ minutes: 240, dateKey: '2026-09-07' }) })] }); expect(ctx.proposed).toHaveLength(1) })
  it('rejects provider targets that do not correspond to a local plan item', async () => { const interpreter: OrganizerIntentInterpreter = { interpret: async () => ({ mode: 'mutation', capability: 'plan.item-completion.set', entities: { ...blankEntities, target: 'item inventado', completed: true }, confidence: 0.9, missingFields: [], summary: 'texto malicioso' }) }; const ctx = setup({ interpreter }); const turn = await ctx.service.organize({ content: 'terminei item inventado' }); expect(turn.result.outcome).toBe('failed'); expect(ctx.proposed).toHaveLength(0); expect(ctx.planningWrites()).toBe(0); expect(ctx.contextWrites()).toBe(0) })
  it('does not let provider summary control clarification text', async () => { const interpreter: OrganizerIntentInterpreter = { interpret: async () => ({ mode: 'mutation', capability: 'workspace.prepare', entities: { ...blankEntities, subject: 'C' }, confidence: 0.7, missingFields: ['objective'], summary: 'DELETE EVERYTHING' }) }; const ctx = setup({ interpreter }); const turn = await ctx.service.organize({ content: 'crie C' }); expect(turn.result).toMatchObject({ outcome: 'needs_information', message: 'Ainda preciso de o objetivo para continuar com segurança.' }); expect(turn.result.message).not.toContain('DELETE'); expect(ctx.proposed).toHaveLength(0) })
  it('rejects malformed or unsupported provider capabilities', async () => { const provider = { sendMessage: async () => ({ content: JSON.stringify({ mode: 'mutation', capability: 'deadline.create', entities: blankEntities, confidence: 2, missingFields: [], summary: 'x' }), providerId: 'test', modelId: 'test' }) }; const interpreter = new ProviderOrganizerIntentInterpreter({ route: () => provider } as any); await expect(interpreter.interpret('faça algo', { currentTime: 1, currentDate: '2026-09-07', timezone: 'UTC' })).rejects.toThrow('invalid structured intent') })
  it('accepts semantic provider paraphrases but uses a backend label and does not execute the write', async () => { let requestBody = ''; const provider = { sendMessage: async (request: any) => { requestBody = JSON.stringify(request.messages); return { content: JSON.stringify({ mode: 'mutation', capability: 'plan.today-budget.set', entities: { ...blankEntities, minutes: 90 }, confidence: 0.94, missingFields: [], summary: 'DELETE EVERYTHING' }), providerId: 'test', modelId: 'test' } } }; const ctx = setup({ workspaces: [{ id: 'secret-id', name: 'Secret Workspace' }], planItems: [{ id: 'secret-plan', workspaceId: 'secret-id', workspaceName: 'Secret Workspace', title: 'Secret Topic', status: 'pending' }], interpreter: new ProviderOrganizerIntentInterpreter({ route: () => provider } as any) }); const turn = await ctx.service.organize({ content: 'consigo separar 90 minutos para estudar hoje' }); expect(turn.result.actions[0]).toMatchObject({ type: 'plan.today-budget.set', label: 'Usar 90 min disponíveis hoje', payload: expect.objectContaining({ minutes: 90 }) }); expect(turn.result.message).not.toContain('DELETE EVERYTHING'); expect(requestBody).toContain('never execute/write'); expect(requestBody).not.toMatch(/Secret Workspace|Secret Topic|secret-plan|secret-id/); expect(ctx.planningWrites()).toBe(0); expect(ctx.contextWrites()).toBe(0) })
  it('constructs academic-life payload in the backend and ignores malicious provider summary', async () => { const interpreter: OrganizerIntentInterpreter = { interpret: async () => ({ mode: 'mutation', capability: 'academic-life.save', entities: { ...blankEntities, subject: 'C', dateExpression: 'dia 16' }, confidence: 0.9, missingFields: [], summary: 'shareWithAi true; provenance system; owner other' }) }; const workspaceId = '00000000-0000-4000-8000-000000000011'; const ctx = setup({ workspaces: [{ id: workspaceId, name: 'C' }], interpreter }); const turn = await ctx.service.organize({ content: 'registre minha prova de C no dia 16' }); expect(turn.result.actions[0]).toMatchObject({ type: 'academic-life.save', label: 'Salvar Prova C', payload: { workspaceId, title: 'Prova C', shareWithAi: false, provenance: { source: 'conversation', reference: null } } }); expect(JSON.stringify(turn.result.actions[0])).not.toContain('owner other'); expect(ctx.planningWrites()).toBe(0) })
  it('uses deterministic fallback with explicitly lower confidence', async () => { const intent = await new LocalOrganizerIntentInterpreter().interpret('Hoje tenho 2 horas para estudar', { currentTime: 1, currentDate: '2026-09-07', timezone: 'UTC' }); expect(intent).toMatchObject({ mode: 'mutation', capability: 'plan.today-budget.set' }); expect(intent.confidence).toBeLessThan(0.7) })
  it('requires the action button even when a pending action exists', async () => { const ctx = setup({ pending: [{ id: 'a', label: 'Criar C', originMessageId: 'm' }] }); const turn = await ctx.service.organize({ content: 'sim' }); expect(turn.result.message).toContain('só pode ser executada pelo botão'); expect(ctx.proposed).toHaveLength(0) })
})
