import { describe, expect, it } from 'vitest'
import { HomeOrganizerService } from '../../src/application/conversations/home-organizer-service'

function setup(mutation: any, options: { workspaces?: Array<{ id: string; name: string }>; pending?: any[]; recalculateFails?: boolean } = {}) {
  const turns: Array<{ content: string; message: string; id?: string }> = []; const proposed: any[] = []; const invalidations: number[] = []; let recalculations = 0; let authority: any = null
  const conversation: any = {
    listMessages: async () => [],
    saveAuthoritativeTurn: async (content: string, message: string, id?: string) => { turns.push({ content, message, id }); return [{ id: id ?? 'assistant', role: 'assistant', content: message, createdAt: 1, sequence: 1, providerId: null, modelId: null }] },
    sendMessageWithAuthority: async (_input: unknown, context: unknown) => { authority = context; return [{ id: 'assistant', role: 'assistant', content: 'Estou bem e pronto para ajudar.', createdAt: 1, sequence: 1, providerId: null, modelId: null }] },
  }
  const planning: any = { applyAcademicMessage: () => typeof mutation === 'function' ? mutation() : mutation }
  const actions: any = { listPending: () => options.pending ?? [], invalidateBefore: (version: number) => invalidations.push(version), propose: (input: any) => { const action = { id: crypto.randomUUID(), status: 'proposed', result: null, createdAt: 1, resolvedAt: null, ...input }; proposed.push(action); return action } }
  const declarations: string[] = []; const service = new HomeOrganizerService(conversation, planning, actions, async () => options.workspaces ?? [], async () => { recalculations += 1; if (options.recalculateFails) throw new Error('recalculate') }, () => new Date(2026, 8, 7, 12).getTime(), { recordMessage: (message: string) => { declarations.push(message); return null } } as any)
  return { service, proposed, turns, invalidations, recalculations: () => recalculations, authority: () => authority, declarations }
}

describe('HomeOrganizerService', () => {
  it('persists an academic declaration and keeps workspace creation out of teaching mode', async () => { const ctx = setup({ changed: false, summary: '', workspaceIds: [] }); await ctx.service.organize({ content: 'Sei bastante Python e uso bibliotecas' }); expect(ctx.declarations).toContain('Sei bastante Python e uso bibliotecas'); const turn = await ctx.service.organize({ content: 'quero criar um workspace' }); expect(turn.result).toMatchObject({ outcome: 'needs_information', message: 'Para criar um Workspace, me diga o tema, seu objetivo e seu nível atual.' }); expect(turn.result.message).not.toMatch(/lista|fila|ponteiro|aula/i) })
  it('keeps small talk informational without mutation or action', async () => { const ctx = setup({ changed: false, summary: '', workspaceIds: [], needsRefinement: null }); const turn = await ctx.service.organize({ content: 'como voce está?' }); expect(turn.result.outcome).toBe('informational'); expect(ctx.proposed).toHaveLength(0); expect(ctx.recalculations()).toBe(0); expect(ctx.authority()).toMatchObject({ currentDate: '2026-09-07', timezone: expect.any(String), operationResult: null }) })
  it('recognizes the real C exam and creates a preparation action tied to the assistant message', async () => { const dueAt = new Date(2026, 8, 16, 23, 59).getTime(); const ctx = setup({ changed: false, summary: '', workspaceIds: [], needsRefinement: 'A qual Workspace?', pendingEvent: { type: 'exam', subject: 'c', dueAt } }); const turn = await ctx.service.organize({ content: 'to bem, tenho prova de c no dia 16 e estou nervoso' }); expect(turn.result.outcome).toBe('needs_decision'); expect(turn.result.message).toContain('16 de setembro de 2026'); expect(turn.result.message).toContain('não tem um Workspace de c'); expect(turn.result.actions[0]).toMatchObject({ originMessageId: turn.messages[0]?.id, label: 'Preparar Workspace de c', type: 'workspace.prepare' }); expect(turn.result.message).not.toMatch(/25 minutos|ponteiros|vetores|atualizei/i) })
  it('applies before reporting success and recalculates once', async () => { const ctx = setup({ changed: true, summary: 'Prova de C reagendada para 16 de setembro.', workspaceIds: ['c'], needsRefinement: null }, { workspaces: [{ id: 'c', name: 'C' }] }); const turn = await ctx.service.organize({ content: 'na verdade é dia 16' }); expect(turn.result.outcome).toBe('applied'); expect(ctx.recalculations()).toBe(1); expect(ctx.turns[0]?.message).toContain('reagendada') })
  it('does not claim full success when replanning fails', async () => { const ctx = setup({ changed: true, summary: 'Prova de C reagendada.', workspaceIds: ['c'], needsRefinement: null }, { workspaces: [{ id: 'c', name: 'C' }], recalculateFails: true }); const turn = await ctx.service.organize({ content: 'na verdade é dia 16' }); expect(turn.result.outcome).toBe('failed'); expect(turn.result.message).toContain('não consegui recalcular') })
  it('rejects textual authorization without an action id', async () => { const ctx = setup({ changed: false, summary: '', workspaceIds: [], needsRefinement: null }); const turn = await ctx.service.organize({ content: 'autorizo' }); expect(turn.result.message).toContain('Não há nenhuma ação'); expect(ctx.proposed).toHaveLength(0) })
  it('requires the button even when a pending action exists', async () => { const ctx = setup({ changed: false, summary: '', workspaceIds: [], needsRefinement: null }, { pending: [{ id: 'a', label: 'Criar C', originMessageId: 'm' }] }); const turn = await ctx.service.organize({ content: 'sim' }); expect(turn.result.message).toContain('só pode ser executada pelo botão') })
  it('answers proposal questions from persisted state only', async () => { const absent = setup({ changed: false, summary: '', workspaceIds: [], needsRefinement: null }); expect((await absent.service.organize({ content: 'cadê a proposta?' })).result.message).toContain('Não há nenhuma proposta'); const pending = setup({}, { pending: [{ id: 'a', label: 'Criar C', originMessageId: 'm' }] }); expect((await pending.service.organize({ content: 'cadê a proposta?' })).result.message).toContain('mensagem que as originou') })
  it('turns database mutation failure into failed outcome', async () => { const ctx = setup(() => { throw new Error('db') }); const turn = await ctx.service.organize({ content: 'mude minha prova' }); expect(turn.result.outcome).toBe('failed'); expect(turn.result.message).toContain('Não consegui salvar') })
  it('keeps pending PlannerActions valid after generic follow-up messages', async () => { const ctx = setup({ changed: false, summary: '', workspaceIds: [], needsRefinement: null }, { pending: [{ id: 'old', label: 'Criar C', originMessageId: 'old-message' }] }); await ctx.service.organize({ content: 'mas não tenho nenhum workspace de C' }); expect(ctx.invalidations).toHaveLength(0) })
  it('opens preparation instead of creating a hidden workspace from HOME', async () => { const dueAt = new Date(2026, 8, 16, 23, 59).getTime(); const ctx = setup({ changed: false, summary: '', workspaceIds: [], needsRefinement: 'A qual Workspace?', pendingEvent: { type: 'exam', subject: 'C', dueAt } }); const turn = await ctx.service.organize({ content: 'tenho prova de C no dia 16' }); expect(turn.result.actions[0]).toMatchObject({ type: 'workspace.prepare', payload: { name: 'C' } }) })
})
