import { describe, expect, it } from 'vitest'
import { PlannerActionService, type PlannerActionRepository } from '../../src/application/planning/planner-action-service'
import { SubjectWorkspaceResolver } from '../../src/application/workspaces/subject-workspace-resolver'
import type { PlannerAction } from '../../src/shared/contracts/planner-action-contract'

class MemoryActions implements PlannerActionRepository {
  actions: PlannerAction[] = []
  keys = new Map<string, PlannerAction>()
  listPending() { return this.actions.filter((item) => item.status === 'proposed') }
  find(id: string) { return this.actions.find((item) => item.id === id) ?? null }
  create(action: PlannerAction, key: string) { const existing = this.keys.get(key); if (existing) return existing; this.actions.push(action); this.keys.set(key, action); return action }
  claim(id: string, now: number) { const action = this.find(id); if (!action || action.status !== 'proposed') throw new Error('not pending'); return this.replace(action, { ...action, status: 'applying', resolvedAt: now }) }
  complete(id: string, status: 'applied' | 'rejected', result: unknown, now: number) { const action = this.find(id); if (!action || action.status !== 'applying') throw new Error('not applying'); return this.replace(action, { ...action, status, result, resolvedAt: now }) }
  release(id: string) { const action = this.find(id); if (action?.status === 'applying') this.replace(action, { ...action, status: 'proposed', resolvedAt: null }) }
  invalidateSiblings(originMessageId: string, exceptId: string, now: number) { this.actions = this.actions.map((action) => action.originMessageId === originMessageId && action.id !== exceptId && action.status === 'proposed' ? { ...action, status: 'obsolete', resolvedAt: now } : action) }
  invalidatePending(contextVersion: number, now: number) { this.actions = this.actions.map((action) => action.status === 'proposed' && action.contextVersion < contextVersion ? { ...action, status: 'obsolete', resolvedAt: now } : action) }
  private replace(previous: PlannerAction, next: PlannerAction) { this.actions[this.actions.indexOf(previous)] = next; return next }
}

function service(repository: MemoryActions, createWorkspace = async (input: { name: string }) => ({ id: crypto.randomUUID(), name: input.name }), createDeadline: (input: { workspaceId: string; title: string; dueAt: number; estimatedMinutes: number; masteryPercent: number | null }) => void = () => {}) {
  return new PlannerActionService({ repository, createWorkspace, createProject: async () => {}, createDeadline, addRoutine: () => {}, now: () => 10 })
}

describe('PlannerActionService', () => {
  it('persists structured action metadata and applies its known payload', async () => { const repository = new MemoryActions(); const planner = service(repository); const action = planner.propose({ type: 'workspace.prepare', payload: { name: 'C', objective: 'Estudar C' }, label: 'Criar Workspace de C', originMessageId: crypto.randomUUID(), contextVersion: 1 }); expect(action).toMatchObject({ label: 'Criar Workspace de C', status: 'proposed' }); expect((await planner.resolve(action.id, 'apply')).status).toBe('applied') })
  it('claims before execution so a second click cannot execute twice', async () => { const repository = new MemoryActions(); let creates = 0; const planner = service(repository, async (input) => { creates += 1; return { id: crypto.randomUUID(), name: input.name } }); const action = planner.propose({ type: 'workspace.prepare', payload: { name: 'C', objective: 'Estudar C' }, label: 'Criar C', originMessageId: crypto.randomUUID(), contextVersion: 1 }); const results = await Promise.allSettled([planner.resolve(action.id, 'apply'), planner.resolve(action.id, 'apply')]); expect(results.filter((result) => result.status === 'fulfilled')).toHaveLength(1); expect(creates).toBe(0) })
  it('invalidates stale pending actions', () => { const repository = new MemoryActions(); const planner = service(repository); const action = planner.propose({ type: 'workspace.prepare', payload: { name: 'C', objective: 'Estudar C' }, label: 'Criar C', originMessageId: crypto.randomUUID(), contextVersion: 1 }); planner.invalidateBefore(2); expect(repository.find(action.id)?.status).toBe('obsolete') })
  it('invalidates alternative actions from the same message after one applies', async () => { const repository = new MemoryActions(); const planner = service(repository); const messageId = crypto.randomUUID(); const first = planner.propose({ type: 'routine.add', payload: { content: 'Usar C' }, label: 'Usar C', originMessageId: messageId, contextVersion: 1 }); const second = planner.propose({ type: 'routine.add', payload: { content: 'Usar ED' }, label: 'Usar ED', originMessageId: messageId, contextVersion: 1 }); await planner.resolve(first.id, 'apply'); expect(repository.find(second.id)?.status).toBe('obsolete') })
  it('rejects legacy workspace creation execution', async () => { const repository = new MemoryActions(); const planner = service(repository); const action = planner.propose({ type: 'workspace.create', payload: { name: 'C', objective: 'Estudar C' }, label: 'Legado', originMessageId: crypto.randomUUID(), contextVersion: 1 }); await expect(planner.resolve(action.id, 'apply')).rejects.toThrow('can no longer be executed') })
  it('only reports a planning action applied after authoritative execution succeeds', async () => { const repository = new MemoryActions(); let minutes = 0; const planner = new PlannerActionService({ repository, createWorkspace: async () => ({ id: 'w', name: 'W' }), createProject: async () => {}, createDeadline: () => {}, addRoutine: () => {}, setTodayBudget: (input) => { minutes = input.minutes; return { persisted: true } }, now: () => 10 }); const action = planner.propose({ type: 'plan.today-budget.set', payload: { dateKey: '2026-09-10', timezone: 'UTC', minutes: 240 }, label: '4h hoje', originMessageId: crypto.randomUUID(), contextVersion: 1 }); expect(await planner.resolve(action.id, 'apply')).toMatchObject({ status: 'applied', result: { persisted: true } }); expect(minutes).toBe(240) })
  it('keeps composite budget sequencing atomic inside the authoritative budget service', async () => { const repository = new MemoryActions(); const calls: string[] = []; const planner = new PlannerActionService({ repository, createWorkspace: async () => ({ id: 'w', name: 'W' }), createProject: async () => {}, createDeadline: () => {}, addRoutine: () => {}, setTodayBudget: (input) => { calls.push(`budget:${input.minutes}`); calls.push('replan'); return { revision: 2 } }, recalculatePlan: () => { calls.push('separate-replan') }, now: () => 10 }); const action = planner.propose({ type: 'plan.today-budget.set', payload: { dateKey: '2026-09-10', timezone: 'UTC', minutes: 30 }, label: '30 min e replan', originMessageId: crypto.randomUUID(), contextVersion: 1 }); expect(calls).toEqual([]); await planner.resolve(action.id, 'apply'); expect(calls).toEqual(['budget:30', 'replan']) })
  it('releases a failed planning action for retry and never confirms it', async () => { const repository = new MemoryActions(); const planner = new PlannerActionService({ repository, createWorkspace: async () => ({ id: 'w', name: 'W' }), createProject: async () => {}, createDeadline: () => {}, addRoutine: () => {}, recalculatePlan: () => { throw new Error('persist failed') }, now: () => 10 }); const action = planner.propose({ type: 'plan.recalculate', payload: { timezone: 'UTC' }, label: 'Recalcular', originMessageId: crypto.randomUUID(), contextVersion: 1 }); await expect(planner.resolve(action.id, 'apply')).rejects.toThrow('persist failed'); expect(repository.find(action.id)?.status).toBe('proposed') })
  it('executes academic event creation only through the applied PlannerAction', async () => { const repository = new MemoryActions(); const saved: any[] = []; const planner = new PlannerActionService({ repository, createWorkspace: async () => ({ id: 'w', name: 'W' }), createProject: async () => {}, createDeadline: () => {}, addRoutine: () => {}, saveAcademicLife: (input) => { saved.push(input); return { ...input, id: crypto.randomUUID(), status: 'active' } as any }, now: () => 10 }); const payload = { kind: 'event' as const, title: 'Prova C', details: '', workspaceId: null, startsAt: null, endsAt: 1000, expiresAt: 1000, timezone: 'UTC', weekday: null, minutes: null, shareWithAi: false, provenance: { source: 'conversation' as const, reference: null } }; const action = planner.propose({ type: 'academic-life.save', payload, label: 'Salvar Prova C', originMessageId: crypto.randomUUID(), contextVersion: 1 }); expect(saved).toHaveLength(0); await planner.resolve(action.id, 'apply'); expect(saved).toEqual([expect.objectContaining({ workspaceId: null, title: 'Prova C' })]) })
  it('notifies conversation focus only after authoritative application succeeds', async () => { const repository = new MemoryActions(); const resolved: PlannerAction[] = []; const planner = new PlannerActionService({ repository, createWorkspace: async () => ({ id: 'w', name: 'W' }), createProject: async () => {}, createDeadline: () => {}, addRoutine: () => {}, saveAcademicLife: (input) => ({ ...input, id: crypto.randomUUID(), status: 'active' }) as any, onResolved: (action) => { resolved.push(action) }, now: () => 10 }); const action = planner.propose({ type: 'academic-life.save', payload: { kind: 'event', title: 'Prova POO', details: '{}', workspaceId: null, startsAt: null, endsAt: 1000, expiresAt: 1000, timezone: 'UTC', weekday: null, minutes: null, shareWithAi: false, provenance: { source: 'conversation', reference: null } }, label: 'Salvar', originMessageId: crypto.randomUUID(), contextVersion: 1 }); expect(resolved).toEqual([]); await planner.resolve(action.id, 'apply'); expect(resolved).toHaveLength(1); expect(resolved[0]?.status).toBe('applied') })
  it('keeps event creation unlinked then exposes optional suggestions', async () => { const repository = new MemoryActions(); let linked = 0; const planner = new PlannerActionService({ repository, createWorkspace: async () => ({ id: 'w', name: 'W' }), createProject: async () => {}, createDeadline: () => {}, addRoutine: () => {}, saveAcademicLife: (input) => ({ ...input, id: crypto.randomUUID(), status: 'active' }) as any, suggestAcademicEventWorkspaces: () => ({ status: 'suggested', candidate: { workspaceId: 'java' } }), linkAcademicEventWorkspace: async () => { linked += 1; return {} as any }, now: () => 10 }); const action = planner.propose({ type: 'academic-life.save', payload: { kind: 'event', title: 'Prova POO', details: '{}', workspaceId: null, startsAt: null, endsAt: 1000, expiresAt: 1000, timezone: 'UTC', weekday: null, minutes: null, shareWithAi: false, provenance: { source: 'conversation', reference: null } }, label: 'Salvar prova', originMessageId: crypto.randomUUID(), contextVersion: 1 }); const applied = await planner.resolve(action.id, 'apply'); expect(applied.result).toMatchObject({ item: { workspaceId: null }, suggestions: { status: 'suggested' } }); expect(linked).toBe(0) })
  it('does not roll back a confirmed event creation when optional resolution is unavailable', async () => { const repository = new MemoryActions(); const planner = new PlannerActionService({ repository, createWorkspace: async () => ({ id: 'w', name: 'W' }), createProject: async () => {}, createDeadline: () => {}, addRoutine: () => {}, saveAcademicLife: (input) => ({ ...input, id: crypto.randomUUID(), status: 'active' }) as any, suggestAcademicEventWorkspaces: () => { throw new Error('provider unavailable') }, now: () => 10 }); const action = planner.propose({ type: 'academic-life.save', payload: { kind: 'event', title: 'Prova POO', details: '{}', workspaceId: null, startsAt: null, endsAt: 1000, expiresAt: 1000, timezone: 'UTC', weekday: null, minutes: null, shareWithAi: false, provenance: { source: 'conversation', reference: null } }, label: 'Salvar prova', originMessageId: crypto.randomUUID(), contextVersion: 1 }); expect(await planner.resolve(action.id, 'apply')).toMatchObject({ status: 'applied', result: { item: { workspaceId: null }, suggestions: { status: 'unavailable' } } }) })
  it('applies keep-unlinked as an explicit decision and dismisses sibling suggestions', async () => { const repository = new MemoryActions(); const event = { id: crypto.randomUUID(), status: 'active', replacedById: null, workspaceId: null, kind: 'event' } as any; const planner = new PlannerActionService({ repository, createWorkspace: async () => ({ id: 'w', name: 'W' }), createProject: async () => {}, createDeadline: () => {}, addRoutine: () => {}, keepAcademicEventUnlinked: () => event, now: () => 10 }); const originMessageId = crypto.randomUUID(); const keep = planner.propose({ type: 'academic.event.keepUnlinked', payload: { eventId: event.id }, label: 'Manter sem Workspace', originMessageId, contextVersion: 1 }); const link = planner.propose({ type: 'academic.event.linkWorkspace', payload: { eventId: event.id, workspaceId: crypto.randomUUID(), subject: 'POO' }, label: 'Vincular Java', originMessageId, contextVersion: 1 }); expect(await planner.resolve(keep.id, 'apply')).toMatchObject({ status: 'applied', result: { keptUnlinked: true } }); expect(repository.find(link.id)?.status).toBe('obsolete') })
  it.each([{ status: 'archived', replacedById: null, workspaceId: null }, { status: 'active', replacedById: crypto.randomUUID(), workspaceId: null }, { status: 'active', replacedById: null, workspaceId: crypto.randomUUID() }])('fails stale keep-unlinked without dismissing siblings', async (state) => { const repository = new MemoryActions(); const eventId = crypto.randomUUID(); const planner = new PlannerActionService({ repository, createWorkspace: async () => ({ id: 'w', name: 'W' }), createProject: async () => {}, createDeadline: () => {}, addRoutine: () => {}, keepAcademicEventUnlinked: () => { throw new Error(`invalid ${JSON.stringify(state)}`) }, now: () => 10 }); const originMessageId = crypto.randomUUID(); const keep = planner.propose({ type: 'academic.event.keepUnlinked', payload: { eventId }, label: 'Manter', originMessageId, contextVersion: 1 }); const link = planner.propose({ type: 'academic.event.linkWorkspace', payload: { eventId, workspaceId: crypto.randomUUID(), subject: 'POO' }, label: 'Vincular', originMessageId, contextVersion: 1 }); await expect(planner.resolve(keep.id, 'apply')).rejects.toThrow('invalid'); expect(repository.find(keep.id)?.status).toBe('proposed'); expect(repository.find(link.id)?.status).toBe('proposed') })
  it('reuses a stable discovery proposal across changing scan revisions', () => { const repository = new MemoryActions(); const planner = service(repository); const first = planner.propose({ type: 'academic.event.keepUnlinked', payload: { eventId: crypto.randomUUID() }, label: 'Manter', originMessageId: 'scan', contextVersion: 1, idempotencyScope: 'event:one:keep' }); const second = planner.propose({ type: 'academic.event.keepUnlinked', payload: first.payload, label: 'Manter', originMessageId: 'scan', contextVersion: 2, idempotencyScope: 'event:one:keep' }); expect(second.id).toBe(first.id); expect(repository.actions).toHaveLength(1) })
  it('offers two ambiguous candidates without applying either, then selects one and dismisses every sibling option', async () => { const repository = new MemoryActions(); const eventId = crypto.randomUUID(); const javaId = crypto.randomUUID(); const pythonId = crypto.randomUUID(); const linked: string[] = []; const planner = new PlannerActionService({ repository, createWorkspace: async () => ({ id: 'w', name: 'W' }), createProject: async () => {}, createDeadline: () => {}, addRoutine: () => {}, linkAcademicEventWorkspace: async (_event, workspaceId) => { linked.push(workspaceId!); return { id: eventId } as any }, now: () => 10 }); const originMessageId = `academic-event-options:${eventId}`; const java = planner.propose({ type: 'academic.event.linkWorkspace', payload: { eventId, workspaceId: javaId, subject: 'POO' }, label: 'Vincular Prova POO a Java', originMessageId, contextVersion: 1 }); const python = planner.propose({ type: 'academic.event.linkWorkspace', payload: { eventId, workspaceId: pythonId, subject: 'POO' }, label: 'Vincular Prova POO a Python', originMessageId, contextVersion: 1 }); const keep = planner.propose({ type: 'academic.event.keepUnlinked', payload: { eventId }, label: 'Manter sem Workspace', originMessageId, contextVersion: 1 }); const prepare = planner.propose({ type: 'workspace.prepare', payload: { name: 'POO', objective: 'Preparação acadêmica' }, label: 'Preparar Workspace de POO', originMessageId, contextVersion: 1 }); expect(linked).toEqual([]); expect(repository.listPending()).toHaveLength(4); await planner.resolve(python.id, 'apply'); expect(linked).toEqual([pythonId]); expect(repository.find(java.id)?.status).toBe('obsolete'); expect(repository.find(keep.id)?.status).toBe('obsolete'); expect(repository.find(prepare.id)?.status).toBe('obsolete') })
  it('rediscovers an independent event after Workspace creation and replans only after confirmed link', async () => { const repository = new MemoryActions(); const eventId = crypto.randomUUID(); const workspaceId = crypto.randomUUID(); const providerInputs: unknown[] = []; const resolver = new SubjectWorkspaceResolver({ listWorkspaces: async () => [{ id: workspaceId, name: 'Java', objective: 'POO', status: 'active', createdAt: 1, updatedAt: 1, lastOpenedAt: null, archivedAt: null }], listAcademicRelations: () => [], suggestSemantic: async (input) => { providerInputs.push(input); return [{ workspaceId, confidence: 0.9, reason: 'POO em Java' }] } }); const resolution = await resolver.resolve('POO', { allowSemantic: true, semanticWorkspaceIds: [workspaceId], semanticContext: 'titles-only' }); if (resolution.status !== 'suggested') throw new Error('expected semantic suggestion'); let linked = false; const followups: PlannerAction[] = []; const planner = new PlannerActionService({ repository, createWorkspace: async () => ({ id: workspaceId, name: 'Java' }), createProject: async () => {}, createDeadline: () => {}, addRoutine: () => {}, linkAcademicEventWorkspace: async () => { linked = true; return { id: eventId, kind: 'event', status: 'active', workspaceId, timezone: 'UTC' } as any }, onResolved: (action) => { followups.push(action) }, now: () => 10 }); const action = planner.propose({ type: 'academic.event.linkWorkspace', payload: { eventId, workspaceId: resolution.candidate.workspaceId, subject: 'POO' }, label: 'Vincular Prova POO a Java', originMessageId: `academic-event-options:${eventId}`, contextVersion: 1 }); expect(linked).toBe(false); expect(followups).toEqual([]); expect(providerInputs).toEqual([{ subject: 'POO', workspaces: [{ id: workspaceId, name: 'Java', contextSubjects: [] }] }]); const applied = await planner.resolve(action.id, 'apply'); expect(linked).toBe(true); expect(followups).toEqual([expect.objectContaining({ id: applied.id, status: 'applied', result: expect.objectContaining({ workspaceId }) })]) })
})
