import { describe, expect, it } from 'vitest'
import { AIProviderManager } from '../../src/application/ai/ai-provider-manager'
import { RoadmapService, fallback, hasGenericModules, type RoadmapRepository } from '../../src/application/roadmaps/roadmap-service'
import type { LearningPathState, Roadmap } from '../../src/shared/contracts/roadmap-contract'

class MemoryRoadmaps implements RoadmapRepository {
  roadmap: Roadmap | null = null; state: LearningPathState | null = null; activations = 0
  findCurrent() { return this.roadmap?.status === 'accepted' ? this.roadmap : null }
  nextVersion() { return (this.roadmap?.version ?? 0) + 1 }
  create(value: Roadmap) { this.roadmap = value; return value }
  activate(value: Roadmap) { this.activations += 1; this.roadmap = { ...value, status: 'accepted' }; return this.roadmap }
  accept(_workspaceId: string, _roadmapId: string, now: number) { this.roadmap = { ...this.roadmap!, status: 'accepted', updatedAt: now }; return this.roadmap }
  getLearningPathState() { return this.state }
  setLearningPathState(value: LearningPathState) { this.state = value; return value }
  recoverInterrupted(_workspaceId: string, now: number, staleBefore: number, retryAfter: number) { if (this.state?.status === 'generating' && this.state.updatedAt <= staleBefore) this.state = { ...this.state, status: 'failed_retryable', retryAfter, lastErrorCode: 'INTERRUPTED', updatedAt: now }; return this.state }
  tryStartGeneration(workspaceId: string, activeRoadmapId: string | null, now: number) { if (this.state?.status === 'generating') return false; this.state = { workspaceId, status: 'generating', activeRoadmapId, lastAttemptAt: now, retryAfter: null, lastErrorCode: null, updatedAt: now }; return true }
  listWaitingForProvider() { return this.state?.status === 'waiting_for_provider' ? [this.state.workspaceId] : [] }
}

const workspace = { id: crypto.randomUUID(), name: 'C', objective: 'Aprender programação em C', status: 'active' as const, createdAt: 1, updatedAt: 1, lastOpenedAt: null, archivedAt: null }
const generated = JSON.stringify({ title: 'Trilha de C', modules: [
  { title: 'Compilação, tipos e expressões', objective: 'Compilar programas C', estimatedMinutes: 120, topics: ['gcc e tradução', 'tipos escalares'], outcomes: ['Compilar sem erros'], practice: 'Criar conversor de unidades', completionCriteria: ['Compila com warnings ativos'], sourceIds: ['cppreference-c'] },
  { title: 'Memória, arrays e ponteiros', objective: 'Manipular memória com segurança', estimatedMinutes: 180, topics: ['arrays', 'ponteiros'], outcomes: ['Explicar endereços'], practice: 'Implementar vetor dinâmico', completionCriteria: ['Sem acesso inválido'], sourceIds: ['invented-source'] },
] })
function providerManager(send = async () => ({ content: generated, providerId: 'test', modelId: 'test' })) { const manager = new AIProviderManager(); manager.register({ id: 'test', name: 'Test', testConnection: async () => {}, getCapabilities: () => ({ streaming: false, usageInformation: false, supportedInput: ['text'] }), sendMessage: send }); manager.select('test'); return manager }
const context = () => ({ difficulties: [], deadline: null, availability: [], knownContext: [] })
const sources: any = { sourcesFor: async () => [{ id: 'cppreference-c', title: 'C reference', url: 'https://en.cppreference.com/w/c', type: 'reference', authority: 'cppreference', retrieved: true, retrievedAt: 1, excerpt: 'C language syntax and semantics.' }] }

describe('RoadmapService learning path lifecycle', () => {
  it('waits for provider without creating a generic roadmap', async () => { const repository = new MemoryRoadmaps(); const result = await new RoadmapService(repository, new AIProviderManager(), async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id); expect(result.status).toBe('waiting_for_provider'); expect(repository.roadmap).toBeNull() })
  it('deduplicates simultaneous ensure calls and activates generated C path', async () => { const repository = new MemoryRoadmaps(); let calls = 0; const manager = providerManager(async () => { calls += 1; await new Promise((resolve) => setTimeout(resolve, 10)); return { content: generated, providerId: 'test', modelId: 'test' } }); const service = new RoadmapService(repository, manager, async () => workspace, context, sources, () => 10); const [first, second] = await Promise.all([service.ensureLearningPath(workspace.id), service.ensureLearningPath(workspace.id)]); expect(calls).toBe(1); expect(first).toEqual(second); expect(repository.roadmap).toMatchObject({ status: 'accepted', generationKind: 'ai_generated' }); expect(JSON.stringify(repository.roadmap)).not.toContain('mapa de 10 conceitos') })
  it('reuses an active valid path without provider work', async () => { const repository = new MemoryRoadmaps(); repository.roadmap = { id: 'r', workspaceId: workspace.id, title: 'C', status: 'accepted', generationKind: 'ai_generated', version: 1, providerId: 'p', modelId: 'm', modules: [], createdAt: 1, updatedAt: 1 }; const result = await new RoadmapService(repository, new AIProviderManager(), async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id); expect(result).toMatchObject({ status: 'ready', activeRoadmapId: 'r' }); expect(repository.activations).toBe(0) })
  it('respects cooldown and retries once after explicit provider reconnect', async () => { const repository = new MemoryRoadmaps(); const service = new RoadmapService(repository, new AIProviderManager(), async () => workspace, context, sources, () => 10); await service.ensureLearningPath(workspace.id); expect((await service.ensureLearningPath(workspace.id)).status).toBe('waiting_for_provider'); const connected = new RoadmapService(repository, providerManager(), async () => workspace, context, sources, () => 11); expect((await connected.ensureLearningPath(workspace.id)).status).toBe('waiting_for_provider'); expect((await connected.ensureLearningPath(workspace.id, { forceProviderRetry: true })).status).toBe('ready') })
  it('preserves active path when upgrade generation fails', async () => { const repository = new MemoryRoadmaps(); repository.roadmap = { id: 'old', workspaceId: workspace.id, title: 'Existing C', status: 'accepted', generationKind: 'provisional_fallback', version: 1, providerId: null, modelId: null, modules: [], createdAt: 1, updatedAt: 1 }; const manager = providerManager(async () => { throw new Error('invalid response') }); const result = await new RoadmapService(repository, manager, async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id); expect(result).toMatchObject({ status: 'failed_retryable', activeRoadmapId: 'old', lastErrorCode: 'GENERATION_FAILED' }); expect(repository.roadmap.id).toBe('old') })
  it('ignores source ids invented by the model', async () => { const repository = new MemoryRoadmaps(); await new RoadmapService(repository, providerManager(), async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id); expect(repository.roadmap?.modules[0]?.resources).toHaveLength(1); expect(repository.roadmap?.modules[1]?.resources).toHaveLength(0) })
  it('keeps generic guards and does not add a universal C fallback', () => { expect(fallback(workspace)).toBeNull(); expect(hasGenericModules({ title: 'x', modules: [{ title: 'Fundamentos', objective: 'x', estimatedMinutes: 10, topics: ['conceitos básicos', 'x'], outcomes: ['x'], practice: 'x', completionCriteria: ['x'], resources: [] }, { title: 'Projeto', objective: 'x', estimatedMinutes: 10, topics: ['x', 'y'], outcomes: ['x'], practice: 'x', completionCriteria: ['x'], resources: [] }] })).toBe(true) })
  it('recovers durable generating state as retryable after restart', async () => { const repository = new MemoryRoadmaps(); repository.state = { workspaceId: workspace.id, status: 'generating', activeRoadmapId: null, lastAttemptAt: 1, retryAfter: null, lastErrorCode: null, updatedAt: -300001 }; const state = await new RoadmapService(repository, new AIProviderManager(), async () => workspace, context, sources, () => 10).getLearningPathState(workspace.id); expect(state).toMatchObject({ status: 'failed_retryable', retryAfter: 300010, lastErrorCode: 'INTERRUPTED' }) })

  it('keeps a provisional path usable while waiting for provider upgrade', async () => { const repository = new MemoryRoadmaps(); repository.roadmap = { id: 'old', workspaceId: workspace.id, title: 'Existing C', status: 'accepted', generationKind: 'provisional_fallback', version: 1, providerId: null, modelId: null, modules: [], createdAt: 1, updatedAt: 1 }; const state = await new RoadmapService(repository, new AIProviderManager(), async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id); expect(state).toMatchObject({ status: 'waiting_for_provider', activeRoadmapId: 'old' }); expect(repository.findCurrent()?.id).toBe('old') })

  it('classifies a provider network failure as waiting and reconnect creates one version', async () => { const repository = new MemoryRoadmaps(); const offline = providerManager(async () => { const error = new Error('Could not connect'); Object.assign(error, { code: 'NETWORK_UNAVAILABLE' }); throw error }); expect((await new RoadmapService(repository, offline, async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id)).status).toBe('waiting_for_provider'); const online = new RoadmapService(repository, providerManager(), async () => workspace, context, sources, () => 11); online.retryWaitingForProvider(); await new Promise((resolve) => setTimeout(resolve, 10)); expect(repository.state?.status).toBe('ready'); expect(repository.activations).toBe(1) })

})
