import { describe, expect, it } from 'vitest'
import { AIProviderManager } from '../../src/application/ai/ai-provider-manager'
import { RoadmapService, type RoadmapRepository } from '../../src/application/roadmaps/roadmap-service'
import type { Roadmap } from '../../src/shared/contracts/roadmap-contract'

class MemoryRoadmaps implements RoadmapRepository { roadmap: Roadmap | null = null; findCurrent() { return this.roadmap } nextVersion() { return 1 } create(value: Roadmap) { this.roadmap = value; return value } accept(_workspaceId: string, _roadmapId: string, now: number) { this.roadmap = { ...this.roadmap!, status: 'accepted', updatedAt: now }; return this.roadmap } }
const workspace = { id: crypto.randomUUID(), name: 'POO com Java', objective: 'Aprender orientação a objetos', status: 'active' as const, createdAt: 1, updatedAt: 1, lastOpenedAt: null, archivedAt: null }

describe('RoadmapService', () => {
  it('builds and accepts a detailed offline Java roadmap', async () => { const repository = new MemoryRoadmaps(); const service = new RoadmapService(repository, new AIProviderManager(), async () => workspace, () => ({ difficulties: [], deadline: null, availability: [], knownContext: [] }), () => 10); const roadmap = await service.generate(workspace.id); expect(roadmap.modules.map((item) => item.title)).toContain('Classes, objetos e encapsulamento'); expect(roadmap.generationKind).toBe('provisional_fallback'); expect((await service.accept(workspace.id, roadmap.id)).status).toBe('accepted') })
  it('creates semantically different Python tracks by level', async () => { const basic = { ...workspace, id: crypto.randomUUID(), name: 'Python Básico', objective: 'Sou iniciante' }; const advanced = { ...workspace, id: crypto.randomUUID(), name: 'Python Avançado', objective: 'Já domino funções e classes' }; const basicRoadmap = await new RoadmapService(new MemoryRoadmaps(), new AIProviderManager(), async () => basic).generate(basic.id); const advancedRoadmap = await new RoadmapService(new MemoryRoadmaps(), new AIProviderManager(), async () => advanced).generate(advanced.id); expect(basicRoadmap.modules.flatMap((item) => item.topics)).toContain('print'); expect(advancedRoadmap.modules.flatMap((item) => item.topics)).toContain('async/await') })
  it('does not persist generic content without an adequate fallback', async () => { const repository = new MemoryRoadmaps(); const unknown = { ...workspace, id: crypto.randomUUID(), name: 'Assunto Especial', objective: 'Contexto detalhado' }; await expect(new RoadmapService(repository, new AIProviderManager(), async () => unknown).generate(unknown.id)).rejects.toThrow('Não foi possível preparar este Roadmap agora'); expect(repository.roadmap).toBeNull() })
  it('passes academic context to AI for a real C roadmap', async () => { const manager = new AIProviderManager(); let prompt = ''; manager.register({ id: 'test', name: 'Test', testConnection: async () => {}, getCapabilities: () => ({ streaming: false, usageInformation: false, supportedInput: ['text'] as const }), sendMessage: async (request) => { prompt = request.messages.at(-1)?.content ?? ''; return { content: JSON.stringify({ title: 'Preparação para prova de C', modules: [{ title: 'Ponteiros e memória', objective: 'Dominar endereços', estimatedMinutes: 240, topics: ['endereço e desreferência', 'malloc e free'], outcomes: ['usar ponteiros'], practice: 'Implementar alocação', completionCriteria: ['sem vazamentos'], resources: [] }, { title: 'Listas encadeadas', objective: 'Manipular nós', estimatedMinutes: 240, topics: ['nós e ponteiro inicial', 'inserção e remoção'], outcomes: ['implementar lista'], practice: 'Criar lista', completionCriteria: ['liberar memória'], resources: [] }] }), providerId: 'test', modelId: 'test-model' } } }); manager.select('test'); const c = { ...workspace, id: crypto.randomUUID(), name: 'C', objective: 'Preparação para prova' }; const roadmap = await new RoadmapService(new MemoryRoadmaps(), manager, async () => c, () => ({ difficulties: ['ponteiros', 'lista estática', 'lista encadeada'], deadline: new Date('2026-09-16').getTime(), availability: [{ weekday: 2, minutes: 240 }], knownContext: [] })).generate(c.id); expect(roadmap.generationKind).toBe('ai_generated'); expect(JSON.parse(prompt)).toMatchObject({ subject: 'C', difficulties: ['ponteiros', 'lista estática', 'lista encadeada'] }); expect(JSON.stringify(roadmap)).not.toContain('Vocabulário e mapa') })
})
