import { describe, expect, it } from 'vitest'
import { AIProviderManager } from '../../src/application/ai/ai-provider-manager'
import { RoadmapService, hasGenericModules, hasSetupAsPrimaryCurriculum, type RoadmapRepository } from '../../src/application/roadmaps/roadmap-service'
import type { LearningPathState, Roadmap } from '../../src/shared/contracts/roadmap-contract'

class MemoryRoadmaps implements RoadmapRepository {
  roadmap: Roadmap | null = null; state: LearningPathState | null = null; activations = 0
  findCurrent() { return this.roadmap?.status === 'accepted' ? this.roadmap : null }
  nextVersion() { return (this.roadmap?.version ?? 0) + 1 }
  create(value: Roadmap) { this.roadmap = value; return value }
  activate(value: Roadmap) { this.activations += 1; this.roadmap = { ...value, status: 'accepted' }; return this.roadmap }
  accept(_workspaceId: string, _roadmapId: string, now: number) { this.roadmap = { ...this.roadmap!, status: 'accepted', updatedAt: now }; return this.roadmap }
  getLearningPathState() { return this.state }
  setLearningPathState(value: LearningPathState) { this.state = value; return value }
  recoverInterrupted(_workspaceId: string, now: number, staleBefore: number, retryAfter: number) { if (this.state?.status === 'generating' && this.state.updatedAt <= staleBefore) this.state = { ...this.state, status: 'failed_retryable', retryAfter, lastErrorCode: 'INTERRUPTED', updatedAt: now }; return this.state }
  tryStartGeneration(workspaceId: string, activeRoadmapId: string | null, now: number) { if (this.state?.status === 'generating') return false; this.state = { workspaceId, status: 'generating', activeRoadmapId, lastAttemptAt: now, retryAfter: null, lastErrorCode: null, updatedAt: now }; return true }
  listWaitingForProvider() { return this.state?.status === 'waiting_for_provider' ? [this.state.workspaceId] : [] }
  progressedTopicIds() { return this.progressed }
  progressed: string[] = []
  preview: import('../../src/shared/contracts/roadmap-contract').RoadmapRebuildPreview | null = null
  saveRebuildPreview(value: import('../../src/shared/contracts/roadmap-contract').RoadmapRebuildPreview) { this.preview = value; return value }
  findRebuildPreview(_workspaceId: string, id: string) { return this.preview?.id === id ? this.preview : null }
  applyRebuildPreview(value: import('../../src/shared/contracts/roadmap-contract').RoadmapRebuildPreview, now: number) { this.roadmap = { ...this.roadmap!, id: crypto.randomUUID(), title: value.title, modules: value.modules, version: this.roadmap!.version + 1, updatedAt: now }; return this.roadmap }
}

const workspace = { id: crypto.randomUUID(), name: 'C', objective: 'Aprender programação em C', status: 'active' as const, createdAt: 1, updatedAt: 1, lastOpenedAt: null, archivedAt: null }
const generated = JSON.stringify({ title: 'Trilha de C', modules: [
  { title: 'Compilação, tipos e expressões', objective: 'Compilar programas C', estimatedMinutes: 120, topics: ['gcc e tradução', 'tipos escalares'], outcomes: ['Compilar sem erros'], practice: 'Criar conversor de unidades', completionCriteria: ['Compila com warnings ativos'], sourceIds: ['cppreference-c'] },
  { title: 'Memória, arrays e ponteiros', objective: 'Manipular memória com segurança', estimatedMinutes: 180, topics: ['arrays', 'ponteiros'], outcomes: ['Explicar endereços'], practice: 'Implementar vetor dinâmico', completionCriteria: ['Sem acesso inválido'], sourceIds: ['invented-source'] },
] })
function providerManager(send: (request: import('../../src/application/ai/ai-provider').AIRequest) => Promise<import('../../src/application/ai/ai-provider').AIResponse> = async () => ({ content: generated, providerId: 'test', modelId: 'test' })) { const manager = new AIProviderManager(); manager.register({ id: 'test', name: 'Test', testConnection: async () => {}, getCapabilities: () => ({ streaming: false, usageInformation: false, supportedInput: ['text'] }), sendMessage: send }); manager.select('test'); return manager }
const context = () => ({ difficulties: [], deadline: null, availability: [], knownContext: [] })
const sources: any = { sourcesFor: async () => [{ id: 'cppreference-c', title: 'C reference', url: 'https://en.cppreference.com/w/c', type: 'reference', authority: 'cppreference', retrieved: true, retrievedAt: 1, excerpt: 'C language syntax and semantics.' }] }

describe('RoadmapService learning path lifecycle', () => {
  it('labels declared context separately from observed evidence', async () => { const repository = new MemoryRoadmaps(); let request = ''; const manager = providerManager(async (input) => { request = JSON.stringify(input); return { content: generated, providerId: 'p', modelId: 'm' } }); await new RoadmapService(repository, manager, async () => workspace, () => ({ difficulties: ['ponteiros'], deadline: null, availability: [], knownContext: ['Nível declarado: advanced', 'Uso bibliotecas'] }), sources, () => 10).ensureLearningPath(workspace.id); expect(request).toContain('declaredContext'); expect(request).toContain('observedLearning'); expect(request).toContain('auto-relato'); expect(request).not.toContain('"knownContext"') })
  it('waits for provider without creating a generic roadmap', async () => { const repository = new MemoryRoadmaps(); const result = await new RoadmapService(repository, new AIProviderManager(), async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id); expect(result.status).toBe('waiting_for_provider'); expect(repository.roadmap).toBeNull() })
  it('reads a missing roadmap without starting generation', async () => { const repository = new MemoryRoadmaps(); let calls = 0; const manager = providerManager(async () => { calls += 1; return { content: generated, providerId: 'test', modelId: 'test' } }); const service = new RoadmapService(repository, manager, async () => workspace, context, sources, () => 10); await expect(service.get(workspace.id)).resolves.toBeNull(); expect(calls).toBe(0); expect(repository.state).toBeNull() })
  it('deduplicates simultaneous ensure calls and activates generated C path', async () => { const repository = new MemoryRoadmaps(); let calls = 0; const manager = providerManager(async () => { calls += 1; await new Promise((resolve) => setTimeout(resolve, 10)); return { content: generated, providerId: 'test', modelId: 'test' } }); const service = new RoadmapService(repository, manager, async () => workspace, context, sources, () => 10); const [first, second] = await Promise.all([service.ensureLearningPath(workspace.id), service.ensureLearningPath(workspace.id)]); expect(calls).toBe(1); expect(first).toEqual(second); expect(repository.roadmap).toMatchObject({ status: 'accepted', generationKind: 'ai_generated' }); expect(JSON.stringify(repository.roadmap)).not.toContain('mapa de 10 conceitos') })
  it('reuses an active valid path without provider work', async () => { const repository = new MemoryRoadmaps(); repository.roadmap = { id: 'r', workspaceId: workspace.id, title: 'C', status: 'accepted', generationKind: 'ai_generated', version: 1, providerId: 'p', modelId: 'm', modules: [{ id: 'm', title: 'Memória em C', objective: 'Usar memória', estimatedMinutes: 90, position: 1, status: 'active', topics: ['arrays', 'ponteiros'], outcomes: ['Usar ponteiros'], practice: 'Criar vetor dinâmico', completionCriteria: ['Sem vazamentos'], resources: [] }], createdAt: 1, updatedAt: 1 }; const result = await new RoadmapService(repository, new AIProviderManager(), async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id); expect(result).toMatchObject({ status: 'ready', activeRoadmapId: 'r' }); expect(repository.activations).toBe(0) })
  it('respects cooldown and retries once after explicit provider reconnect', async () => { const repository = new MemoryRoadmaps(); const service = new RoadmapService(repository, new AIProviderManager(), async () => workspace, context, sources, () => 10); await service.ensureLearningPath(workspace.id); expect((await service.ensureLearningPath(workspace.id)).status).toBe('waiting_for_provider'); const connected = new RoadmapService(repository, providerManager(), async () => workspace, context, sources, () => 11); expect((await connected.ensureLearningPath(workspace.id)).status).toBe('waiting_for_provider'); expect((await connected.ensureLearningPath(workspace.id, { forceProviderRetry: true })).status).toBe('ready') })
  it('preserves active path when upgrade generation fails', async () => { const repository = new MemoryRoadmaps(); repository.roadmap = { id: 'old', workspaceId: workspace.id, title: 'Existing C', status: 'accepted', generationKind: 'provisional_fallback', version: 1, providerId: null, modelId: null, modules: [{ id: 'old-module', title: 'C', objective: 'Estudar C', estimatedMinutes: 60, position: 1, status: 'active', topics: ['arrays'], outcomes: ['Usar arrays'], practice: 'Criar vetor', completionCriteria: ['Compila'], resources: [] }], createdAt: 1, updatedAt: 1 }; const manager = providerManager(async () => { throw new Error('invalid response') }); const result = await new RoadmapService(repository, manager, async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id); expect(result).toMatchObject({ status: 'failed_retryable', activeRoadmapId: 'old', lastErrorCode: 'UNKNOWN_GENERATION_ERROR' }); expect(repository.roadmap.id).toBe('old') })
  it('repairs an invalid OmniRoute-shaped response exactly once', async () => { const repository = new MemoryRoadmaps(); const requests: unknown[] = []; const manager = providerManager(async (request) => { requests.push(request); return { content: requests.length === 1 ? JSON.stringify({ title: 'Trilha de C', modules: [{ title: 'Tipos em C', objective: 'Usar tipos', estimatedMinutes: 60, topics: ['int', 'char'], outcomes: ['Escolher tipos'], practice: ['Criar conversor'], completionCriteria: ['Compila'], sourceIds: [] }] }) : generated, providerId: 'test', modelId: 'test' } }); const result = await new RoadmapService(repository, manager, async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id); expect(result.status).toBe('ready'); expect(requests).toHaveLength(2); expect(JSON.stringify(requests[1])).toContain('Corrija apenas a estrutura JSON') })
  it('does not loop when the repair response is also invalid', async () => { const repository = new MemoryRoadmaps(); let calls = 0; const manager = providerManager(async () => { calls += 1; return { content: '{"title":"C"}', providerId: 'test', modelId: 'test' } }); const result = await new RoadmapService(repository, manager, async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id); expect(result).toMatchObject({ status: 'failed_retryable', lastErrorCode: 'ROADMAP_SCHEMA_INVALID' }); expect(calls).toBe(2) })
  it('continues without curriculum sources when enrichment fails', async () => { const repository = new MemoryRoadmaps(); const result = await new RoadmapService(repository, providerManager(), async () => workspace, context, { sourcesFor: async () => { throw new Error('source offline') } } as any, () => 10).ensureLearningPath(workspace.id); expect(result.status).toBe('ready'); expect(repository.roadmap?.modules).toHaveLength(2) })
  it('repairs ready when the persisted roadmap is missing', async () => { const repository = new MemoryRoadmaps(); repository.state = { workspaceId: workspace.id, status: 'ready', activeRoadmapId: 'missing', lastAttemptAt: 1, retryAfter: null, lastErrorCode: null, updatedAt: 1 }; const result = await new RoadmapService(repository, new AIProviderManager(), async () => workspace, context, sources, () => 10).getLearningPathState(workspace.id); expect(result).toMatchObject({ status: 'failed_retryable', activeRoadmapId: null, lastErrorCode: 'ROADMAP_PERSISTENCE_FAILED' }) })
  it('ignores source ids invented by the model', async () => { const repository = new MemoryRoadmaps(); await new RoadmapService(repository, providerManager(), async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id); expect(repository.roadmap?.modules[0]?.resources).toHaveLength(1); expect(repository.roadmap?.modules[1]?.resources).toHaveLength(0) })
  it('keeps generic guards without a universal fallback', () => { expect(hasGenericModules({ title: 'x', modules: [{ title: 'Fundamentos', objective: 'x', estimatedMinutes: 10, topics: ['conceitos básicos', 'x'], outcomes: ['x'], practice: 'x', completionCriteria: ['x'], resources: [] }, { title: 'Projeto', objective: 'x', estimatedMinutes: 10, topics: ['x', 'y'], outcomes: ['x'], practice: 'x', completionCriteria: ['x'], resources: [] }] })).toBe(true) })
  it('rejects setup as the primary programming curriculum', () => { expect(hasSetupAsPrimaryCurriculum({ title: 'Python', modules: [{ title: 'Instalação da IDE', objective: 'Configurar PATH e versão', estimatedMinutes: 60, topics: ['download', 'setup'], outcomes: ['Instalar'], practice: 'Instalar', completionCriteria: ['IDE aberta'], resources: [] }, { title: 'Código', objective: 'Programar', estimatedMinutes: 60, topics: ['print', 'variáveis'], outcomes: ['Programar'], practice: 'Código', completionCriteria: ['Executa'], resources: [] }] })).toBe(true) })
  it('recovers durable generating state as retryable after restart', async () => { const repository = new MemoryRoadmaps(); repository.state = { workspaceId: workspace.id, status: 'generating', activeRoadmapId: null, lastAttemptAt: 1, retryAfter: null, lastErrorCode: null, updatedAt: -300001 }; const state = await new RoadmapService(repository, new AIProviderManager(), async () => workspace, context, sources, () => 10).getLearningPathState(workspace.id); expect(state).toMatchObject({ status: 'failed_retryable', retryAfter: 30010, lastErrorCode: 'INTERRUPTED' }) })

  it('keeps a provisional path usable while waiting for provider upgrade', async () => { const repository = new MemoryRoadmaps(); repository.roadmap = { id: 'old', workspaceId: workspace.id, title: 'Existing C', status: 'accepted', generationKind: 'provisional_fallback', version: 1, providerId: null, modelId: null, modules: [{ id: 'old-module', title: 'C', objective: 'Estudar C', estimatedMinutes: 60, position: 1, status: 'active', topics: ['arrays'], outcomes: ['Usar arrays'], practice: 'Criar vetor', completionCriteria: ['Compila'], resources: [] }], createdAt: 1, updatedAt: 1 }; const state = await new RoadmapService(repository, new AIProviderManager(), async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id); expect(state).toMatchObject({ status: 'waiting_for_provider', activeRoadmapId: 'old' }); expect(repository.findCurrent()?.id).toBe('old') })

  it('classifies provider timeout as request failure rather than provider unavailable', async () => { const repository = new MemoryRoadmaps(); const manager = providerManager(async () => { throw new DOMException('This operation was aborted', 'AbortError') }); const result = await new RoadmapService(repository, manager, async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id); expect(result).toMatchObject({ status: 'failed_retryable', lastErrorCode: 'PROVIDER_REQUEST_FAILED', retryAfter: 30010 }) })
  it('classifies a provider network failure as waiting and reconnect creates one version', async () => { const repository = new MemoryRoadmaps(); const offline = providerManager(async () => { const error = new Error('Could not connect'); Object.assign(error, { code: 'NETWORK_UNAVAILABLE' }); throw error }); expect((await new RoadmapService(repository, offline, async () => workspace, context, sources, () => 10).ensureLearningPath(workspace.id)).status).toBe('waiting_for_provider'); const online = new RoadmapService(repository, providerManager(), async () => workspace, context, sources, () => 11); online.retryWaitingForProvider(); await new Promise((resolve) => setTimeout(resolve, 10)); expect(repository.state?.status).toBe('ready'); expect(repository.activations).toBe(1) })

  it('previews approved material rebuild, preserves semantic IDs, and requires acknowledgement only for progressed removals', async () => { const repository = new MemoryRoadmaps(); repository.roadmap = { id: crypto.randomUUID(), workspaceId: workspace.id, title: 'C antigo', status: 'accepted', generationKind: 'ai_generated', version: 1, providerId: 'p', modelId: 'm', createdAt: 1, updatedAt: 1, modules: [{ id: crypto.randomUUID(), title: 'Compilação, tipos e expressões', objective: 'Anterior', estimatedMinutes: 60, position: 1, status: 'active', topics: ['gcc e tradução', 'tópico removido'], outcomes: ['Anterior'], practice: 'Anterior', completionCriteria: ['Anterior'], resources: [] }] }; repository.progressed = [`${repository.roadmap.modules[0]!.id}:tópico removido`]; const materialId = crypto.randomUUID(); const materials = { list: () => [{ id: materialId, name: 'aula.pdf', pageCount: 1, status: 'ready' as const, relevance: 90, role: 'priority' as const, semanticAnalysis: null, sourceUrl: null, errorMessage: null, createdAt: 1 }], search: () => [], overview: () => ({ material: materials.list()[0]!, content: 'gcc', offset: 0, nextOffset: null, pageNumbers: [1] }), readPage: () => ({ material: materials.list()[0]!, content: 'gcc e tradução', offset: 0, nextOffset: null, pageNumbers: [1] }) }; const service = new RoadmapService(repository, providerManager(), async () => workspace, context, sources, () => 10, () => crypto.randomUUID(), materials); const preview = await service.previewRebuild({ workspaceId: workspace.id, materialIds: [materialId] }); expect(preview.modules[0]?.id).toBe(repository.roadmap.modules[0]?.id); expect(preview.impact).toMatchObject({ preservedTopicIds: [`${repository.roadmap.modules[0]!.id}:gcc e tradução`], unsafeProgressTopicIds: repository.progressed, requiresAcknowledgement: true }); await expect(service.applyRebuild({ workspaceId: workspace.id, previewId: preview.id, acknowledgeUnsafeChanges: false })).rejects.toThrow('acknowledgement'); await expect(service.applyRebuild({ workspaceId: workspace.id, previewId: preview.id, acknowledgeUnsafeChanges: true })).resolves.toMatchObject({ title: 'Trilha de C' }) })

  it('keeps the active roadmap when material rebuild provider is offline', async () => { const repository = new MemoryRoadmaps(); repository.roadmap = { id: crypto.randomUUID(), workspaceId: workspace.id, title: 'Preservada', status: 'accepted', generationKind: 'ai_generated', version: 1, providerId: 'p', modelId: 'm', createdAt: 1, updatedAt: 1, modules: [{ id: crypto.randomUUID(), title: 'M', objective: 'O', estimatedMinutes: 60, position: 1, status: 'active', topics: ['a', 'b'], outcomes: ['o'], practice: 'p', completionCriteria: ['c'], resources: [] }] }; const materialId = crypto.randomUUID(); const materials = { list: () => [{ id: materialId, name: 'a.pdf', pageCount: 1, status: 'ready' as const, relevance: 80, role: 'base' as const, semanticAnalysis: null, sourceUrl: null, errorMessage: null, createdAt: 1 }], search: () => [], overview: () => { throw new Error('offline') }, readPage: () => { throw new Error('offline') } }; await expect(new RoadmapService(repository, new AIProviderManager(), async () => workspace, context, sources, () => 10, () => crypto.randomUUID(), materials).previewRebuild({ workspaceId: workspace.id, materialIds: [materialId] })).rejects.toThrow('unavailable'); expect(repository.roadmap.title).toBe('Preservada') })

})
