import { describe, expect, it } from 'vitest'
import { AIProviderManager } from '../../src/application/ai/ai-provider-manager'
import { StudyLessonService, localLesson, type StudyLessonRepository } from '../../src/application/study-lessons/study-lesson-service'
import type { PersistedStudyLesson } from '../../src/shared/contracts/study-lesson-contract'
import type { RoadmapModule } from '../../src/shared/contracts/roadmap-contract'

const module = (topics: string[]): RoadmapModule => ({ id: crypto.randomUUID(), title: 'Python', objective: 'Programar com Python', estimatedMinutes: 90, position: 1, status: 'active', topics, outcomes: ['Produzir programas corretos'], practice: 'Criar um programa executável', completionCriteria: ['Explicar e executar'], resources: [] })
const workspace = (name: string) => ({ id: crypto.randomUUID(), name, objective: name.includes('Avançado') ? 'Aprofundamento avançado' : 'Sou iniciante', status: 'active' as const, createdAt: 1, updatedAt: 1, lastOpenedAt: null, archivedAt: null })

class MemoryLessons implements StudyLessonRepository { values = new Map<string, PersistedStudyLesson>(); creates = 0; find(roadmapId: string, topicId: string) { return this.values.get(`${roadmapId}:${topicId}`) ?? null } create(value: PersistedStudyLesson) { this.creates++; this.values.set(`${value.roadmapId}:${value.topicId}`, value); return value } }

describe('StudyLessonService', () => {
  it('creates a real basic print lesson', () => { const item = module(['print()']); const lesson = localLesson(workspace('Python Básico'), item, 'print()', `${item.id}:print()`); expect(lesson.title).toContain('print()'); expect(JSON.stringify(lesson.blocks)).toContain('strings'); expect(lesson.blocks.find((block) => block.type === 'codeExample')).toMatchObject({ expectedOutput: 'Olá, mundo!\nOlá Ana' }); expect(lesson.blocks.some((block) => block.type === 'commonError')).toBe(true) })
  it('creates semantically advanced decorator content', () => { const item = module(['decorators']); const lesson = localLesson(workspace('Python Avançado'), item, 'decorators', `${item.id}:decorators`); expect(lesson.level).toBe('advanced'); expect(JSON.stringify(lesson.blocks)).toContain('functools'); expect(JSON.stringify(lesson.blocks)).toContain('ParamSpec'); expect(JSON.stringify(lesson.blocks)).not.toContain('saída padrão') })
  it('does not reuse print text for decorators', () => { const item = module(['print()', 'decorators']); const print = localLesson(workspace('Python Básico'), item, 'print()', `${item.id}:print()`); const decorators = localLesson(workspace('Python Avançado'), item, 'decorators', `${item.id}:decorators`); expect(print.blocks.map((block) => block.type)).not.toEqual(decorators.blocks.map((block) => block.type)); expect(print.objective).not.toBe(decorators.objective) })
  it('diagnoses an incorrect checkpoint and adds reinforcement on repetition', async () => { const item = module(['print()']); const ws = workspace('Python Básico'); const roadmap = { id: crypto.randomUUID(), workspaceId: ws.id, title: 'Python', status: 'accepted' as const, version: 1, providerId: null, modelId: null, modules: [item], createdAt: 1, updatedAt: 1 }; const service = new StudyLessonService(new MemoryLessons(), new AIProviderManager(), async () => ws, () => roadmap); const lesson = await service.getOrCreate({ workspaceId: ws.id, roadmapId: roadmap.id, moduleId: item.id, topicId: `${item.id}:print()` }); const checkpoint = lesson.blocks.find((block) => block.type === 'checkpoint')!; const result = service.evaluate(lesson, checkpoint.id, 0, 2); expect(result.correct).toBe(false); expect(result.difficulty).toContain('vírgula'); expect(result.hint).toBeTruthy(); expect(result.reinforcement).toContain('strings') })
  it('reuses the persisted lesson without regeneration', async () => { const item = module(['print()']); const ws = workspace('Python Básico'); const roadmap = { id: crypto.randomUUID(), workspaceId: ws.id, title: 'Python', status: 'accepted' as const, version: 1, providerId: null, modelId: null, modules: [item], createdAt: 1, updatedAt: 1 }; const repository = new MemoryLessons(); const service = new StudyLessonService(repository, new AIProviderManager(), async () => ws, () => roadmap, () => 10); const input = { workspaceId: ws.id, roadmapId: roadmap.id, moduleId: item.id, topicId: `${item.id}:print()` }; const first = await service.getOrCreate(input); const second = await service.getOrCreate(input); expect(second).toEqual(first); expect(repository.creates).toBe(1) })
})
