import { describe, expect, it } from 'vitest'
import { SubjectWorkspaceResolver } from '../../src/application/workspaces/subject-workspace-resolver'

const workspace = (id: string, name: string, status: 'active' | 'archived' = 'active') => ({ id, name, objective: '', status, createdAt: 1, updatedAt: 1, lastOpenedAt: null, archivedAt: status === 'archived' ? 2 : null })

describe('SubjectWorkspaceResolver', () => {
  it('returns POO to Java only as a semantic suggestion', async () => { const resolver = new SubjectWorkspaceResolver({ listWorkspaces: async () => [workspace('java', 'Java')], listAcademicRelations: () => [], suggestSemantic: async () => [{ workspaceId: 'java', confidence: 0.9, reason: 'POO é estudada no Workspace Java.' }] }); expect(await resolver.resolve('POO')).toMatchObject({ status: 'suggested', candidate: { workspaceId: 'java', tier: 'semantic', confidence: 0.9 } }) })
  it('asks when two semantic candidates are plausible', async () => { const resolver = new SubjectWorkspaceResolver({ listWorkspaces: async () => [workspace('java', 'Java'), workspace('python', 'Python')], listAcademicRelations: () => [], suggestSemantic: async () => [{ workspaceId: 'java', confidence: 0.9, reason: 'POO em Java' }, { workspaceId: 'python', confidence: 0.8, reason: 'POO em Python' }] }); expect(await resolver.resolve('POO')).toMatchObject({ status: 'ambiguous', candidates: [{ workspaceId: 'java' }, { workspaceId: 'python' }] }) })
  it('reuses a confirmed alias deterministically and ignores archived workspaces', async () => { const resolver = new SubjectWorkspaceResolver({ listWorkspaces: async () => [workspace('java', 'Java'), workspace('old', 'POO', 'archived')], listAcademicRelations: () => [{ workspaceId: 'java', subject: 'POO', relation: 'user_selected' }], suggestSemantic: async () => { throw new Error('semantic tier must not run') } }); expect(await resolver.resolve('POO')).toMatchObject({ status: 'resolved', candidate: { workspaceId: 'java', tier: 'confirmed_context' } }) })
  it('performs zero provider calls when semantic sharing is forbidden', async () => { let calls = 0; const resolver = new SubjectWorkspaceResolver({ listWorkspaces: async () => [workspace('java', 'Java')], listAcademicRelations: () => [], suggestSemantic: async () => { calls += 1; return [] } }); expect(await resolver.resolve('POO', { allowSemantic: false })).toEqual({ status: 'none', candidates: [] }); expect(calls).toBe(0) })
  it('sends only bounded allowed Workspace context to semantic resolution', async () => { let sent: any; const resolver = new SubjectWorkspaceResolver({ listWorkspaces: async () => [workspace('java', 'Java'), workspace('private', 'Privado')], listAcademicRelations: () => [{ workspaceId: 'java', subject: 'Orientação a objetos', relation: 'primary' }, { workspaceId: 'private', subject: 'Segredo', relation: 'primary' }], suggestSemantic: async (input) => { sent = input; return [{ workspaceId: 'java', confidence: 0.9, reason: 'POO em Java' }] } }); await resolver.resolve('POO', { allowSemantic: true, semanticWorkspaceIds: ['java'] }); expect(sent).toEqual({ subject: 'POO', workspaces: [{ id: 'java', name: 'Java', contextSubjects: ['Orientação a objetos'] }] }) })
  it('uses only the explicit subject and Workspace titles for private independent-event matching', async () => { let sent: any; const resolver = new SubjectWorkspaceResolver({ listWorkspaces: async () => [workspace('java', 'Java')], listAcademicRelations: () => [{ workspaceId: 'java', subject: 'private notes and goals', relation: 'primary' }], suggestSemantic: async (input) => { sent = input; return [{ workspaceId: 'java', confidence: 0.9, reason: 'POO em Java' }] } }); const resolution = await resolver.resolve('POO', { allowSemantic: true, semanticWorkspaceIds: ['java'], semanticContext: 'titles-only' }); expect(resolution).toMatchObject({ status: 'suggested', candidate: { workspaceId: 'java', tier: 'semantic' } }); expect(sent).toEqual({ subject: 'POO', workspaces: [{ id: 'java', name: 'Java', contextSubjects: [] }] }); expect(JSON.stringify(sent)).not.toMatch(/private notes|goals|prova|sourceText|details/i) })
})
