import { describe, expect, it } from 'vitest'
import { distributeWeeklyPlan, weekStartKey, zonedDateKey, type WeeklyPlanningTopic } from '../../src/application/planning/weekly-planner'

const now = Date.parse('2026-09-09T14:00:00Z')
const base = (input: Partial<WeeklyPlanningTopic> & Pick<WeeklyPlanningTopic, 'workspaceId' | 'topicId' | 'topic'>): WeeklyPlanningTopic => ({ workspaceName: input.workspaceId, moduleId: 'm', modulePosition: 1, progress: 'NOT_STARTED', evidenceCount: 0, masteryEstimate: null, confidence: 'low', needsReview: false, difficultyLevel: 'low', conceptMemory: null, dueAt: null, deadlineTitle: null, ...input })
const run = (topics: WeeklyPlanningTopic[], existing: Parameters<typeof distributeWeeklyPlan>[0]['existing'] = [], availability = new Map([[3, 60], [4, 60], [5, 60]])) => { let id = 0; return distributeWeeklyPlan({ weekStart: '2026-09-07', today: '2026-09-09', timezone: 'UTC', now, availability, topics, existing, createId: () => `new-${++id}` }) }

describe('authoritative weekly planner', () => {
  it('preserves a pending logical item id when availability moves and resizes it', () => { const topic = base({ workspaceId: 'w', topicId: 'm:a', topic: 'A' }); const existing = [{ id: 'stable', sourceKey: 'w:m:a:introduction', workspaceId: 'w', dateKey: '2026-09-10', title: 'old', durationMinutes: 45, position: 1, status: 'pending' as const, moduleId: 'm', topicId: 'm:a', activityType: 'introduction' as const, scheduledStartMinutes: 1080, reason: 'old' }]; const result = run([topic], existing, new Map([[3, 15]])); expect(result.find((item) => item.sourceKey === existing[0]!.sourceKey)).toMatchObject({ id: 'stable', dateKey: '2026-09-09', durationMinutes: 15 }) })
  it('prioritizes the nearest deadline and never exceeds availability', () => { const result = run([base({ workspaceId: 'later', topicId: 'm:b', topic: 'B', dueAt: now + 5 * 86_400_000, deadlineTitle: 'Prova B' }), base({ workspaceId: 'soon', topicId: 'm:a', topic: 'A', dueAt: now + 86_400_000, deadlineTitle: 'Prova A' })]); expect(result[0]?.workspaceId).toBe('soon'); for (const dateKey of new Set(result.map((item) => item.dateKey))) expect(result.filter((item) => item.dateKey === dateKey).reduce((sum, item) => sum + item.durationMinutes, 0)).toBeLessThanOrEqual(60) })
  it('uses evidence and progress for reinforcement without inventing a review', () => { const result = run([base({ workspaceId: 'weak', topicId: 'm:weak', topic: 'Weak', progress: 'IN_PROGRESS', evidenceCount: 4, masteryEstimate: 20, needsReview: true, difficultyLevel: 'high' })]); expect(result.map((item) => item.activityType)).toEqual(['exercise']); expect(result[0]?.reason).toContain('evidência') })
  it('preserves history and stable IDs while replacing only changed future work', () => { const completed = { id: 'done', sourceKey: 'weak:m:weak:review', workspaceId: 'weak', dateKey: '2026-09-09', title: 'Weak / revisão', durationMinutes: 25, position: 1, status: 'completed' as const, moduleId: 'm', topicId: 'm:weak', activityType: 'review' as const, scheduledStartMinutes: 1080, reason: 'old' }; const pending = { ...completed, id: 'same', sourceKey: 'weak:m:weak:exercise', activityType: 'exercise' as const, title: 'Weak / exercícios', status: 'pending' as const, position: 2, durationMinutes: 35, scheduledStartMinutes: 1105 }; const result = run([base({ workspaceId: 'weak', topicId: 'm:weak', topic: 'Weak', progress: 'IN_PROGRESS', needsReview: true })], [completed, pending]); expect(result.find((item) => item.sourceKey === completed.sourceKey)).toMatchObject({ id: 'done', status: 'completed' }); expect(result.find((item) => item.sourceKey === pending.sourceKey)?.id).toBe('same'); expect(new Set(result.map((item) => item.sourceKey)).size).toBe(result.length) })
  it('respects zero availability and timezone week boundaries', () => { expect(run([base({ workspaceId: 'w', topicId: 'm:t', topic: 'T' })], [], new Map([[3, 0], [4, 0], [5, 0], [6, 0], [0, 0]])).length).toBe(0); const instant = Date.parse('2026-09-07T01:00:00Z'); expect(zonedDateKey(instant, 'America/Los_Angeles')).toBe('2026-09-06'); expect(weekStartKey(instant, 'America/Los_Angeles')).toBe('2026-08-31') })
  it('uses an explicit date budget ahead of recurring availability', () => { let id = 0; const topics = Array.from({ length: 8 }, (_, index) => base({ workspaceId: `w${index}`, topicId: `m:${index}`, topic: `T${index}` })); const result = distributeWeeklyPlan({ weekStart: '2026-09-07', today: '2026-09-09', timezone: 'UTC', now, availability: new Map([[3, 120], [4, 120]]), dayBudgets: new Map([['2026-09-09', 240]]), topics, existing: [], createId: () => `id-${++id}` }); expect(result.filter((item) => item.dateKey === '2026-09-09').reduce((sum, item) => sum + item.durationMinutes, 0)).toBeGreaterThan(120); expect(result.filter((item) => item.dateKey === '2026-09-09').reduce((sum, item) => sum + item.durationMinutes, 0)).toBeLessThanOrEqual(240) })
  it('drops orphan projections without fabricating a Workspace label', () => { const orphan = { id: 'orphan', sourceKey: 'gone:m:t:review', workspaceId: 'gone', dateKey: '2026-09-08', title: 'Old', durationMinutes: 20, position: 1, status: 'completed' as const, moduleId: 'm', topicId: 'm:t', activityType: 'review' as const, scheduledStartMinutes: 1080, reason: 'old' }; expect(run([base({ workspaceId: 'active', workspaceName: 'Active', topicId: 'm:a', topic: 'A' })], [orphan]).some((item) => item.workspaceId === 'gone')).toBe(false) })
  it('adds only an explicitly due concept review without using a roadmap topic as authority', () => { let id = 0; const dueAt = now - 1; const result = distributeWeeklyPlan({ weekStart: '2026-09-07', today: '2026-09-09', timezone: 'UTC', now, availability: new Map([[3, 60]]), topics: [], reviews: [{ workspaceId: 'w', workspaceName: 'Python', conceptId: 'loops', conceptName: 'Laços', nextReviewAt: dueAt, retention: 'fragile', performance: 'developing', dueAt: null }, { workspaceId: 'w', workspaceName: 'Python', conceptId: 'arrays', conceptName: 'Vetores', nextReviewAt: now + 1, retention: 'fragile', performance: 'struggling', dueAt: null }], existing: [], createId: () => `id-${++id}` }); expect(result).toHaveLength(1); expect(result[0]).toMatchObject({ sourceKey: `w:concept:loops:review:${dueAt}`, title: 'Laços / REVIEW_DUE', topicId: null, moduleId: null, activityType: 'review' }) })
  it('moves past pending curriculum and REVIEW_DUE work without duplicating either source', () => { let id = 0; const dueAt = now - 1000; const oldTopic = { id: 'old-topic', sourceKey: 'w:m:a:introduction', workspaceId: 'w', workspaceName: 'W', dateKey: '2026-09-08', title: 'old', durationMinutes: 30, position: 1, status: 'pending' as const, moduleId: 'm', topicId: 'm:a', activityType: 'introduction' as const, scheduledStartMinutes: 1080, reason: 'old' }; const oldReview = { ...oldTopic, id: 'old-review', sourceKey: `w:concept:c:review:${dueAt}`, topicId: null, moduleId: null, activityType: 'review' as const }; const result = distributeWeeklyPlan({ weekStart: '2026-09-07', today: '2026-09-09', timezone: 'UTC', now, availability: new Map([[3, 120]]), topics: [base({ workspaceId: 'w', topicId: 'm:a', topic: 'A' })], reviews: [{ workspaceId: 'w', workspaceName: 'W', conceptId: 'c', conceptName: 'C', nextReviewAt: dueAt, retention: 'fragile', performance: 'developing', dueAt: null }], existing: [oldTopic, oldReview], createId: () => `new-${++id}` }); expect(result.filter((item) => item.sourceKey === oldTopic.sourceKey)).toEqual([expect.objectContaining({ id: 'old-topic', dateKey: '2026-09-09' })]); expect(result.filter((item) => item.sourceKey === oldReview.sourceKey)).toEqual([expect.objectContaining({ id: 'old-review', dateKey: '2026-09-09' })]) })
  it('does not repeat a topic activity already planned in another week', () => { const topic = base({ workspaceId: 'w', topicId: 'm:a', topic: 'A' }); let id = 0; const result = distributeWeeklyPlan({ weekStart: '2026-09-14', today: '2026-09-14', timezone: 'UTC', now, availability: new Map([[1, 120]]), topics: [topic], existing: [], blockedSourceKeys: new Set(['w:m:a:introduction', 'w:m:a:exercise']), createId: () => `id-${++id}` }); expect(result).toEqual([]) })
  it('drops pending work from archived workspaces but keeps completed history', () => { const pending = { id: 'pending', sourceKey: 'old:m:a:exercise', workspaceId: 'old', workspaceName: 'Old', workspaceArchived: true, dateKey: '2026-09-09', title: 'A', durationMinutes: 30, position: 1, status: 'pending' as const, moduleId: 'm', topicId: 'm:a', activityType: 'exercise' as const, scheduledStartMinutes: 1080, reason: 'old' }; const completed = { ...pending, id: 'completed', sourceKey: 'old:m:a:introduction', dateKey: '2026-09-08', status: 'completed' as const }; const result = run([], [pending, completed]); expect(result).toEqual([expect.objectContaining({ id: 'completed', status: 'completed' })]) })
  it('uses mapped ConceptMemory instead of a contradictory legacy mastery estimate', () => { const result = run([base({ workspaceId: 'w', topicId: 'm:t', topic: 'T', evidenceCount: 2, masteryEstimate: 95, confidence: 'high', needsReview: false, difficultyLevel: 'low', conceptMemory: { performance: 'struggling', retention: 'fragile', confidence: 'low', nextReviewAt: now - 1 } })]); expect(result[0]).toMatchObject({ durationMinutes: 49, reason: 'Reforço priorizado pela memória qualitativa do conceito.' }); expect(result.map((item) => item.activityType)).toEqual(['exercise']) })
})
