import { describe, expect, it, vi } from 'vitest'
import { AIProviderManager } from '../../src/application/ai/ai-provider-manager'
import { WorkspaceOnboardingService, type WorkspaceOnboardingContextCandidate } from '../../src/application/workspaces/workspace-onboarding-service'
import type { ConversationRepository } from '../../src/application/conversations/conversation-repository'
import type { ConversationMessage } from '../../src/shared/contracts/conversation-contract'
import { AcademicSubjectContextService, type AcademicSubjectContextRepository } from '../../src/application/workspaces/academic-subject-context'
import type { AcademicSubjectContext } from '../../src/shared/contracts/academic-subject-context-contract'

function repository(messages: ConversationMessage[] = []): ConversationRepository { return { ensureHomeThread: async () => {}, ensureWorkspaceThread: async () => {}, listMessages: async () => messages, addTurn: async () => [] } }
const observedDefaults = { observedStrengths: [], observedDifficulties: [], misconceptions: [], masteredConcepts: [], reviewConcepts: [], lastConsolidatedAt: null } as const
function service(input: { messages?: ConversationMessage[]; contexts?: AcademicSubjectContext[]; candidates?: WorkspaceOnboardingContextCandidate[]; observed?: string[]; providerContent?: string; sendMessage?: import('../../src/application/ai/ai-provider').AIProvider['sendMessage']; providerTimeoutMs?: number } = {}) {
  const contexts = input.contexts ?? []
  const academicContext = contexts.length ? new AcademicSubjectContextService({ find: (subject) => contexts.find((item) => item.subject === subject) ?? null, list: () => contexts, upsert: (value, now) => ({ ...value, ...observedDefaults, declaredLevel: value.declaredLevel ?? null, createdAt: now, updatedAt: now }) }) : undefined
  const manager = new AIProviderManager()
  if (input.providerContent !== undefined || input.sendMessage) { manager.register({ id: 'test', name: 'test', testConnection: async () => {}, getCapabilities: () => ({ streaming: false, usageInformation: false, supportedInput: ['text'] }), sendMessage: input.sendMessage ?? (async () => ({ content: input.providerContent!, providerId: 'test', modelId: 'test' })) }); manager.select('test') }
  return new WorkspaceOnboardingService({ repository: repository(input.messages), providerManager: manager, academicContext, listObservedLearning: () => input.observed ?? [], listContextCandidates: () => input.candidates ?? [], providerTimeoutMs: input.providerTimeoutMs })
}

describe('WorkspaceOnboardingService contextual analysis', () => {
  it.each([
    ['POO', 'NEEDS_CLARIFICATION', 'Programação Orientada a Objetos', true],
    ['Estrutura de Dados', 'VALID', 'Estrutura de Dados', true],
    ['Inglês', 'VALID', 'Inglês', false],
    ['Matemática', 'VALID', 'Matemática', false],
  ])('interprets %s with a contextual, non-indiscriminate question policy', async (topic, status, canonicalSubject, hasQuestion) => { const result = await service().analyze(topic); expect(result).toMatchObject({ status, canonicalSubject, questionOptional: hasQuestion }); expect(Boolean(result.question)).toBe(hasQuestion) })

  it('confirms the exact prior displayed interpretation without rerunning the provider', async () => { const sendMessage = vi.fn(async () => ({ content: '{}', providerId: 'test', modelId: 'test' })); const sut = service({ sendMessage }); const first = await sut.analyze('C'); expect(first).toMatchObject({ status: 'NEEDS_CONFIRMATION', canonicalSubject: 'Linguagem C', needsDiagnostic: true }); expect(sut.validate(first.analysisToken, first.revision, first.topic, first.canonicalFocus, first.canonicalContext)).toBe(false); const confirmation = { analysisToken: first.analysisToken, revision: first.revision, canonicalSubject: first.canonicalSubject, canonicalFocus: first.canonicalFocus }; const confirmed = await sut.analyze(first.topic, undefined, { confirmation }); expect(confirmed).toMatchObject({ status: 'VALID', canonicalSubject: first.canonicalSubject, canonicalFocus: first.canonicalFocus }); expect(sendMessage).toHaveBeenCalledTimes(1); expect(sut.validate(confirmed.analysisToken, confirmed.revision, confirmed.topic, confirmed.canonicalFocus, confirmed.canonicalContext)).toBe(true) })

  it('rejects stale, replayed, or mismatched interpretation confirmations', async () => { const sut = service(); const first = await sut.analyze('C'); const confirmation = { analysisToken: first.analysisToken, revision: first.revision, canonicalSubject: first.canonicalSubject, canonicalFocus: first.canonicalFocus }; await expect(sut.analyze(first.topic, undefined, { confirmation: { ...confirmation, revision: confirmation.revision + 1 } })).rejects.toThrow('stale or mismatched'); await expect(sut.analyze(first.topic, undefined, { confirmation: { ...confirmation, canonicalSubject: 'Java' } })).rejects.toThrow('stale or mismatched'); await expect(sut.analyze('Java', undefined, { confirmation })).rejects.toThrow('stale or mismatched'); await sut.analyze(first.topic, undefined, { confirmation }); await expect(sut.analyze(first.topic, undefined, { confirmation })).rejects.toThrow('stale or mismatched') })

  it('corrects a recognizable typo with confirmation', async () => { expect(await service().analyze('matematca')).toMatchObject({ status: 'NEEDS_CONFIRMATION', canonicalSubject: 'Matemática', explanation: expect.stringContaining('Corrigi') }) })

  it('rejects nonsense without inventing subject, focus, objective, question or relations', async () => { const result = await service().analyze('asdfgh'); expect(result).toMatchObject({ status: 'INVALID', canonicalSubject: '', canonicalFocus: '', objective: '', question: null, relatedContexts: [], evidence: [] }); expect(service().validate(result.analysisToken, result.revision, '', '', '')).toBe(false) })

  it('accepts known C but requires semantic context for another one-character topic', async () => { expect(await service().analyze('C')).toMatchObject({ status: 'NEEDS_CONFIRMATION', canonicalSubject: 'Linguagem C' }); expect(await service().analyze('X')).toMatchObject({ status: 'REQUIRED_DESCRIPTION', canonicalSubject: '', providerAnalysisState: 'unavailable' }) })

  it('uses the strongest existing C workspace/context when the optional question is ignored', async () => { const result = await service({ candidates: [{ subject: 'Python', source: 'workspace', strength: 70, explanation: 'Workspace Python' }, { subject: 'C', source: 'concept-memory', strength: 90, explanation: 'Experiência observada em C' }] }).analyze('POO'); expect(result).toMatchObject({ contextSource: 'workspace-context', canonicalFocus: expect.stringContaining('C'), relatedContexts: [{ subject: 'C', relation: 'implementation_language', explanation: expect.stringContaining('observada') }] }); expect(result.evidence).toEqual([]) })

  it('uses a plausible nonblocking fallback when no related workspace exists and the question is ignored', async () => { const result = await service().analyze('Estrutura de Dados'); expect(result).toMatchObject({ status: 'VALID', canonicalFocus: 'Estrutura de Dados em C', contextSource: 'workspace-context', relatedContexts: [{ subject: 'C' }] }); expect(result.question).not.toBeNull() })

  it('lets an answered free-text question drive canonical context and automatic relation', async () => { const result = await service().analyze('POO', 'Quero praticar usando Java'); expect(result).toMatchObject({ status: 'NEEDS_CLARIFICATION', canonicalFocus: expect.stringContaining('Java'), canonicalContext: expect.stringContaining('declaração:'), contextSource: 'diagnostic', question: null, relatedContexts: [{ subject: 'Java', relation: 'implementation_language' }] }); expect(result.declarations).toContain('Quero praticar usando Java'); expect(result.evidence).toEqual([]) })

  it('persists HOME declarations as declarations and never promotes them to evidence', async () => { let value: AcademicSubjectContext | null = null; const contextRepository: AcademicSubjectContextRepository = { find: () => value, list: () => value ? [value] : [], upsert: (input, now) => value = { ...input, ...observedDefaults, declaredLevel: input.declaredLevel ?? null, createdAt: now, updatedAt: now } }; const academicContext = new AcademicSubjectContextService(contextRepository, () => 10); const messages: ConversationMessage[] = [{ id: 'm', role: 'user', content: 'Em C eu sei arrays', createdAt: 1, sequence: 1, providerId: null, modelId: null }]; const sut = new WorkspaceOnboardingService({ repository: repository(messages), providerManager: new AIProviderManager(), academicContext }); const first = await sut.analyze('C'); const result = await sut.analyze(first.topic, undefined, { confirmation: { analysisToken: first.analysisToken, revision: first.revision, canonicalSubject: first.canonicalSubject, canonicalFocus: first.canonicalFocus } }); expect(result.declarations).toContain('Em C eu sei arrays'); expect(result.evidence).toEqual([]); expect(JSON.stringify(result)).not.toContain('mastery') })

  it('accepts strict semantic provider output', async () => { const result = await service({ providerContent: JSON.stringify({ status: 'VALID', canonicalSubject: 'Física Quântica', canonicalFocus: 'Fundamentos de Física Quântica', explanation: 'Tema acadêmico reconhecido.', question: null }) }).analyze('quântica'); expect(result).toMatchObject({ status: 'VALID', canonicalSubject: 'Física Quântica', canonicalFocus: 'Fundamentos de Física Quântica' }) })

  it('allows a provider to ground a recognizable typo without changing the subject', async () => { const result = await service({ providerContent: JSON.stringify({ status: 'NEEDS_CONFIRMATION', canonicalSubject: 'Algoritmo', canonicalFocus: 'Algoritmo', explanation: 'Corrigi a grafia provável.', question: null }) }).analyze('algoritimo'); expect(result).toMatchObject({ status: 'NEEDS_CONFIRMATION', canonicalSubject: 'Algoritmo' }) })

  it('rejects an unrelated provider canonical subject and uses the grounded fallback', async () => { const result = await service({ providerContent: JSON.stringify({ status: 'VALID', canonicalSubject: 'História', canonicalFocus: 'Império Romano', explanation: 'Substituição arbitrária.', question: null }) }).analyze('quântica'); expect(result).toMatchObject({ status: 'NEEDS_CLARIFICATION', canonicalSubject: 'quântica', canonicalFocus: 'quântica' }); expect(result.canonicalSubject).not.toBe('História') })

  it('rejects an unrelated subject appended to an otherwise grounded provider answer', async () => { const result = await service({ providerContent: JSON.stringify({ status: 'VALID', canonicalSubject: 'História Quântica', canonicalFocus: 'História Quântica', explanation: 'Tentativa parcialmente sobreposta.', question: null }) }).analyze('quântica'); expect(result).toMatchObject({ status: 'NEEDS_CLARIFICATION', canonicalSubject: 'quântica' }) })

  it.each([
    ['INVALID', null],
    ['VALID', 'Qual recorte?'],
    ['NEEDS_CLARIFICATION', null],
    ['NEEDS_CONFIRMATION', null],
  ] as const)('rejects grounded but incoherent provider status %s for a plausible known topic', async (status, question) => { const result = await service({ providerContent: JSON.stringify({ status, canonicalSubject: 'Algoritmos', canonicalFocus: 'Algoritmos', explanation: 'Status arbitrário.', question }) }).analyze('Algoritmos'); expect(result).toMatchObject({ status: 'NEEDS_CLARIFICATION', canonicalSubject: 'Algoritmos', question: expect.any(String) }) })

  it('accepts coherent grounded provider clarification', async () => { const result = await service({ providerContent: JSON.stringify({ status: 'NEEDS_CLARIFICATION', canonicalSubject: 'Algoritmos', canonicalFocus: 'Algoritmos', explanation: 'Tema amplo.', question: 'Qual família de algoritmos você quer estudar?' }) }).analyze('Algoritmos'); expect(result).toMatchObject({ status: 'NEEDS_CLARIFICATION', explanation: 'Tema amplo.', question: 'Qual família de algoritmos você quer estudar?' }) })

  it.each(['{bad-json', JSON.stringify({ status: 'VALID', canonicalSubject: 'Algoritmos', canonicalFocus: 'Algoritmos', explanation: 'x', question: null, extra: true }), JSON.stringify({ status: 'BOGUS', canonicalSubject: 'Algoritmos', canonicalFocus: 'Algoritmos', explanation: 'x', question: null })])('parses the actual malformed provider response and falls back safely', async (providerContent) => { let requestedTopic = ''; const sendMessage: import('../../src/application/ai/ai-provider').AIProvider['sendMessage'] = vi.fn(async (request) => { requestedTopic = request.messages.at(-1)?.content ?? ''; return { content: providerContent, providerId: 'test', modelId: 'test' } }); const sut = service({ sendMessage }); const result = await sut.analyze('Algoritmos'); expect(sendMessage).toHaveBeenCalledOnce(); expect(requestedTopic).toContain('Algoritmos'); expect(result).toMatchObject({ status: 'NEEDS_CLARIFICATION', canonicalSubject: 'Algoritmos', explanation: expect.stringContaining('Interpretei') }); expect(sut.validate(result.analysisToken, result.revision, result.topic, result.canonicalFocus, result.canonicalContext)).toBe(true) })

  it('aborts a stalled provider and resolves the deterministic fallback promptly', async () => { const sendMessage = vi.fn((request: import('../../src/application/ai/ai-provider').AIRequest) => new Promise<never>((_resolve, reject) => request.signal?.addEventListener('abort', () => reject(new Error('aborted')), { once: true }))); const started = Date.now(); const result = await service({ sendMessage, providerTimeoutMs: 20 }).analyze('quântica'); expect(Date.now() - started).toBeLessThan(500); expect(result).toMatchObject({ status: 'NEEDS_CLARIFICATION', canonicalSubject: 'quântica' }); expect(sendMessage.mock.calls[0]![0].signal?.aborted).toBe(true) })

  it.each(['Nunca usei Java', 'Não quero C', 'Java não', 'evite Java', 'sem Java', "I don't want Python", 'never Java', 'no Java', 'avoid Java', 'without Java', 'Não tenho experiência, quero Java', 'Posso usar Java ou Python'])('does not infer an implementation relation from any negation scope or multiple languages: %s', async (answer) => { const result = await service().analyze('POO', answer); expect(result.relatedContexts).toEqual([]); expect(result.canonicalFocus).toBe('Programação Orientada a Objetos') })

  it('does not call the provider and issues a non-creatable token for locally invalid input', async () => { const sendMessage = vi.fn(); const sut = service({ sendMessage }); const result = await sut.analyze('asdfgh'); expect(result.status).toBe('INVALID'); expect(sendMessage).not.toHaveBeenCalled(); expect(sut.validate(result.analysisToken, result.revision, result.topic, result.canonicalFocus, result.canonicalContext)).toBe(false) })
  it.each(['xy', 'abcq'])('requires a grounded description before creating unknown shorthand %s', async (topic) => { const sut = service(); const result = await sut.analyze(topic); expect(result).toMatchObject({ status: 'REQUIRED_DESCRIPTION', canonicalSubject: '', canonicalFocus: '', questionOptional: false }); expect(sut.validate(result.analysisToken, result.revision, result.topic, result.canonicalFocus, result.canonicalContext)).toBe(false) })
  it.each([['C', 'Linguagem C'], ['JS', 'JavaScript'], ['ED', 'Estrutura de Dados']])('interprets known short topic %s but requires exact confirmation', async (topic, canonicalSubject) => { const sut = service(); const result = await sut.analyze(topic); expect(result).toMatchObject({ status: 'NEEDS_CONFIRMATION', canonicalSubject, question: null }); expect(sut.validate(result.analysisToken, result.revision, result.topic, result.canonicalFocus, result.canonicalContext)).toBe(false) })
  it('makes a known shorthand creatable only after confirming the displayed interpretation', async () => { const sut = service(); const first = await sut.analyze('ed'); const result = await sut.analyze(first.topic, undefined, { confirmation: { analysisToken: first.analysisToken, revision: first.revision, canonicalSubject: first.canonicalSubject, canonicalFocus: first.canonicalFocus } }); expect(result).toMatchObject({ status: 'VALID', canonicalSubject: 'Estrutura de Dados' }); expect(sut.validate(result.analysisToken, result.revision, result.topic, result.canonicalFocus, result.canonicalContext)).toBe(true) })
  it('extracts curricular scope as declarations without producing learning evidence', async () => { const result = await service().analyze('POO', 'Já estudei até classes; quero começar a partir de herança, sem revisar fundamentos. Prefiro exemplos em Java.'); expect(result.curricularScope).toMatchObject({ requestedStart: 'herança', coveredThrough: 'classes', skipFundamentals: true }); expect(result.curricularScope.preferences).toContain('começar a partir de herança, sem revisar fundamentos'); expect(result.evidence).toEqual([]); expect(JSON.stringify(result.curricularScope)).not.toMatch(/mastery|conceptMemory|evidence/i) })
  it('extracts both boundaries from the exact runtime preference', async () => {
    const result = await service().analyze('POO', 'Quero começar a partir de Herança e cobrir Polimorfismo, sem revisar fundamentos.')
    expect(result.curricularScope).toMatchObject({ requestedStart: 'Herança', coveredThrough: 'Polimorfismo', skipFundamentals: true })
    expect(result.curricularScope.preferences).toContain('começar a partir de Herança e cobrir Polimorfismo, sem revisar fundamentos')
    expect(result.evidence).toEqual([])
  })
  it.each([
    ['Desejo iniciar em matrizes e cobrir determinantes, sem revisar fundamentos.', 'matrizes', 'determinantes'],
    ['Quero partir de limites e ir até derivadas; pular fundamentos.', 'limites', 'derivadas'],
    ['Começar a partir de listas e abranger árvores, sem fundamentos.', 'listas', 'árvores'],
  ])('extracts generic Portuguese start and end boundaries from %s', async (answer, requestedStart, coveredThrough) => {
    const result = await service().analyze('Tema acadêmico amplo', answer)
    expect(result.curricularScope).toMatchObject({ requestedStart, coveredThrough, skipFundamentals: true })
  })
  it('does not split a conjunctive topic name without an explicit coverage verb', async () => {
    const result = await service().analyze('Direito', 'Quero começar a partir de direitos e garantias fundamentais, sem revisar fundamentos.')
    expect(result.curricularScope).toMatchObject({ requestedStart: 'direitos e garantias fundamentais', coveredThrough: null, skipFundamentals: true })
  })
})
