import { describe, expect, it } from 'vitest'
import { AIProviderManager } from '../../src/application/ai/ai-provider-manager'
import { WorkspaceOnboardingService } from '../../src/application/workspaces/workspace-onboarding-service'
import type { ConversationRepository } from '../../src/application/conversations/conversation-repository'
import type { ConversationMessage } from '../../src/shared/contracts/conversation-contract'
import { AcademicSubjectContextService, type AcademicSubjectContextRepository } from '../../src/application/workspaces/academic-subject-context'
import type { AcademicSubjectContext } from '../../src/shared/contracts/academic-subject-context-contract'

function repository(messages: ConversationMessage[]): ConversationRepository { return { ensureHomeThread: async () => {}, ensureWorkspaceThread: async () => {}, listMessages: async () => messages, addTurn: async () => [] } }

describe('WorkspaceOnboardingService', () => {
  it('prefers persisted academic context over raw HOME history without creating mastery', async () => { let value: AcademicSubjectContext | null = null; const contextRepository: AcademicSubjectContextRepository = { find: () => value, upsert: (input, now) => value = { ...input, declaredLevel: input.declaredLevel ?? null, createdAt: now, updatedAt: now } }; const academicContext = new AcademicSubjectContextService(contextRepository, () => 10); academicContext.record({ subject: 'Python', declaredLevel: 'advanced', declaredKnowledge: ['Uso bibliotecas'], declaredDifficulties: [], goals: ['Automação'], sourceEvidence: ['Sei bastante Python'] }); const service = new WorkspaceOnboardingService({ repository: repository([{ id: 'm', role: 'user', content: 'Sou iniciante em Java', createdAt: 1, sequence: 1, providerId: null, modelId: null }]), providerManager: new AIProviderManager(), academicContext }); expect(await service.analyze('Python')).toMatchObject({ contextSource: 'academic-context', declaredLevel: 'advanced', declaredKnowledge: ['Uso bibliotecas'], needsDiagnostic: false }); expect(JSON.stringify(await service.analyze('Python'))).not.toContain('mastery') })
  it('asks for a diagnostic when the general memory has no knowledge of the topic', async () => { const service = new WorkspaceOnboardingService({ repository: repository([]), providerManager: new AIProviderManager() }); expect((await service.analyze('Cálculo')).needsDiagnostic).toBe(true) })
  it('does not repeat the diagnostic after the user answers', async () => { const service = new WorkspaceOnboardingService({ repository: repository([]), providerManager: new AIProviderManager() }); expect(await service.analyze('Cálculo', 'Já domino limites, mas não derivadas')).toMatchObject({ needsDiagnostic: false, contextSource: 'diagnostic' }) })
  it('reuses concrete declared knowledge for the same subject', async () => { const messages: ConversationMessage[] = [{ id: 'm', role: 'user', content: 'Em C eu sei arrays, mas tenho dificuldade com ponteiros', createdAt: 1, sequence: 1, providerId: null, modelId: null }]; const service = new WorkspaceOnboardingService({ repository: repository(messages), providerManager: new AIProviderManager() }); expect(await service.analyze('C')).toMatchObject({ needsDiagnostic: false, contextSource: 'general-memory' }) })
  it('keeps declared knowledge separate from observed evidence', async () => { const messages: ConversationMessage[] = [{ id: 'm', role: 'user', content: 'Em C eu sei arrays', createdAt: 1, sequence: 1, providerId: null, modelId: null }]; const service = new WorkspaceOnboardingService({ repository: repository(messages), providerManager: new AIProviderManager(), listObservedLearning: () => ['Errou desreferência três vezes'] }); expect(await service.getSubjectLearningContext('C')).toEqual({ subject: 'C', declared: ['Em C eu sei arrays'], observed: ['Errou desreferência três vezes'] }) })
  it('does not reuse declarations from another subject', async () => { const messages: ConversationMessage[] = [{ id: 'm', role: 'user', content: 'Em Java eu domino classes', createdAt: 1, sequence: 1, providerId: null, modelId: null }]; const service = new WorkspaceOnboardingService({ repository: repository(messages), providerManager: new AIProviderManager() }); expect((await service.analyze('C')).needsDiagnostic).toBe(true) })
  it('persists a HOME-history backfill and reuses it on the next analysis', async () => { let value: AcademicSubjectContext | null = null; const contextRepository: AcademicSubjectContextRepository = { find: () => value, list: () => value ? [value] : [], upsert: (input, now) => value = { ...input, declaredLevel: input.declaredLevel ?? null, createdAt: now, updatedAt: now } }; const academicContext = new AcademicSubjectContextService(contextRepository, () => 10); let reads = 0; const source = repository([{ id: 'm', role: 'user', content: 'Em C eu sei arrays', createdAt: 1, sequence: 1, providerId: null, modelId: null }]); const service = new WorkspaceOnboardingService({ repository: { ...source, listMessages: async (...args) => { reads += 1; return source.listMessages(...args) } }, providerManager: new AIProviderManager(), academicContext }); await service.analyze('C'); expect(academicContext.get('C')?.declaredKnowledge).toEqual(['Em C eu sei arrays']); await service.analyze('C'); expect(reads).toBe(1) })
  it('returns other persisted subjects as optional related contexts', async () => { const values: AcademicSubjectContext[] = [{ subject: 'Java', declaredLevel: null, declaredKnowledge: [], declaredDifficulties: [], goals: [], sourceEvidence: [], createdAt: 1, updatedAt: 1 }, { subject: 'Python', declaredLevel: 'advanced', declaredKnowledge: ['Uso pandas'], declaredDifficulties: [], goals: [], sourceEvidence: [], createdAt: 1, updatedAt: 1 }]; const academicContext = new AcademicSubjectContextService({ find: (subject) => values.find((item) => item.subject === subject) ?? null, list: () => values, upsert: () => values[0]! }); const service = new WorkspaceOnboardingService({ repository: repository([]), providerManager: new AIProviderManager(), academicContext }); expect((await service.analyze('Java')).relatedContexts?.map((item) => item.subject)).toEqual(['Python']) })
})
