import type { AIProviderManager } from '../ai/ai-provider-manager'
import { studyLessonContentSchema, type PersistedStudyLesson, type StudyCheckpointEvaluation, type StudyLessonBlock } from '../../shared/contracts/study-lesson-contract'
import type { Roadmap, RoadmapModule } from '../../shared/contracts/roadmap-contract'
import type { Workspace } from '../../shared/contracts/workspace-contract'

export interface StudyLessonRepository { find(roadmapId: string, topicId: string): PersistedStudyLesson | null; create(lesson: PersistedStudyLesson): PersistedStudyLesson }

function extractJson(content: string): unknown { const fenced = /```(?:json)?\s*([\s\S]*?)```/i.exec(content)?.[1]; const candidate = fenced ?? content.slice(content.indexOf('{'), content.lastIndexOf('}') + 1); return JSON.parse(candidate) }
function levelFor(workspace: Workspace): 'basic' | 'intermediate' | 'advanced' { const value = `${workspace.name} ${workspace.objective}`; return /avançad|avancad|advanced|especialista/i.test(value) ? 'advanced' : /intermedi/i.test(value) ? 'intermediate' : 'basic' }
function idFor(topicId: string, suffix: string): string { return `${topicId}:${suffix}` }

export function localLesson(workspace: Workspace, module: RoadmapModule, topic: string, topicId: string): { title: string; level: 'basic' | 'intermediate' | 'advanced'; objective: string; blocks: StudyLessonBlock[] } {
  const level = levelFor(workspace)
  if (/\bprint\s*\(?.*\)?/i.test(topic)) return { title: 'Produzindo saída com print()', level, objective: 'Usar print() para exibir textos e valores e prever exatamente a saída do programa.', blocks: [
    { id: idFor(topicId, 'purpose'), type: 'explanation' as const, title: 'Para que serve print()', content: 'print() envia valores para a saída padrão. No terminal, isso permite observar resultados, mensagens e o estado do programa.' },
    { id: idFor(topicId, 'syntax'), type: 'codeExample' as const, title: 'Sintaxe e strings', language: 'python', code: 'print("Olá, mundo!")\nnome = "Ana"\nprint("Olá", nome)', expectedOutput: 'Olá, mundo!\nOlá Ana', walkthrough: ['Os parênteses delimitam os argumentos.', 'Aspas criam uma string literal.', 'A vírgula envia dois valores e print adiciona um espaço entre eles.'] },
    { id: idFor(topicId, 'warning'), type: 'commonError' as const, title: 'Erro comum: texto sem aspas', content: 'print(Olá) tenta localizar uma variável chamada Olá. Para texto literal, use print("Olá").' },
    { id: idFor(topicId, 'check'), type: 'checkpoint' as const, title: 'Preveja a saída', question: 'Qual é a saída de print("idade:", 20)?', options: ['idade:20', 'idade: 20', '"idade:", 20'], correctIndex: 1, difficultyByOption: ['efeito da vírgula sobre o separador', 'nenhuma', 'diferença entre código e saída'], hint: 'A vírgula usa o separador padrão de print().', reinforcement: 'Vamos revisar strings e separadores: as aspas não aparecem na saída e a vírgula adiciona um espaço entre valores.' },
    { id: idFor(topicId, 'exercise'), type: 'miniExercise' as const, title: 'Mostre uma ficha curta', instruction: 'Crie variáveis nome e curso e produza uma linha como: Ana estuda Python.', nextAction: 'NEXT_TOPIC' as const },
  ] }
  if (/decorator|decorador/i.test(topic)) return { title: 'Decorators e composição de comportamento', level: 'advanced' as const, objective: 'Implementar decorators que preservam metadados, recebem argumentos e envolvem funções síncronas com responsabilidade clara.', blocks: [
    { id: idFor(topicId, 'model'), type: 'explanation' as const, title: 'Funções que transformam funções', content: 'Um decorator recebe um callable e devolve outro callable. A sintaxe @decorator é açúcar para func = decorator(func), permitindo adicionar comportamento sem alterar o corpo original.' },
    { id: idFor(topicId, 'closure'), type: 'comparison' as const, title: 'Closure, decorator e decorator factory', content: 'Uma closure captura estado léxico; um decorator transforma uma função; uma factory recebe configuração e devolve o decorator. Esses papéis podem aparecer aninhados, mas não são equivalentes.' },
    { id: idFor(topicId, 'code'), type: 'codeExample' as const, title: 'Decorator parametrizado com metadados', language: 'python', code: 'from functools import wraps\n\ndef repeat(times: int):\n    def decorate(fn):\n        @wraps(fn)\n        def wrapper(*args, **kwargs):\n            return [fn(*args, **kwargs) for _ in range(times)]\n        return wrapper\n    return decorate', expectedOutput: null, walkthrough: ['repeat captura times.', 'decorate recebe a função original.', 'wrapper encaminha qualquer assinatura em tempo de execução.', '@wraps preserva __name__, __doc__ e __wrapped__.'] },
    { id: idFor(topicId, 'warning'), type: 'warning' as const, title: 'Cuidado com contratos e async', content: 'Um wrapper síncrono não deve envolver coroutine sem await. Tipagem com ParamSpec e TypeVar ajuda a preservar o contrato estático da função decorada.' },
    { id: idFor(topicId, 'check'), type: 'checkpoint' as const, title: 'Metadados e introspecção', question: 'Por que aplicar functools.wraps ao wrapper?', options: ['Para executar a função mais rápido', 'Para preservar metadados e a ligação __wrapped__', 'Para transformar qualquer função em async'], correctIndex: 1, difficultyByOption: ['finalidade de wraps', 'nenhuma', 'diferença entre wrapper e coroutine'], hint: 'Pense em ferramentas que inspecionam __name__, assinatura e documentação.', reinforcement: 'Sem wraps, introspecção enxerga o wrapper genérico. wraps copia metadados relevantes e registra __wrapped__, permitindo chegar à função original.' },
    { id: idFor(topicId, 'exercise'), type: 'miniExercise' as const, title: 'Instrumente sem quebrar o contrato', instruction: 'Crie um decorator @timed que preserve metadados e retorne, além do valor, o tempo decorrido. Depois explique quando esse retorno alteraria indevidamente o contrato.', nextAction: 'REVIEW' as const },
  ] }
  return { title: `Aula aplicada: ${topic}`, level, objective: module.objective, blocks: [
    { id: idFor(topicId, 'context'), type: 'explanation' as const, title: module.title, content: `${module.objective} Nesta aula, o foco concreto é ${topic}, conectado aos resultados: ${module.outcomes.join('; ')}.` },
    { id: idFor(topicId, 'example'), type: 'codeExample' as const, title: module.practice, language: /python/i.test(workspace.name) ? 'python' : /java/i.test(workspace.name) ? 'java' : 'text', code: module.practice, expectedOutput: null, walkthrough: module.completionCriteria },
    { id: idFor(topicId, 'check'), type: 'checkpoint' as const, title: 'Decisão aplicada', question: `Qual ação demonstra o critério “${module.completionCriteria[0]}”?`, options: [module.practice, `Apenas ler ${topic}`, 'Ignorar o resultado produzido'], correctIndex: 0, difficultyByOption: ['nenhuma', 'diferença entre leitura e evidência', 'necessidade de verificar resultado'], hint: `Procure uma ação observável ligada a ${module.practice}.`, reinforcement: `Volte ao resultado verificável: ${module.completionCriteria.join('; ')}.` },
    { id: idFor(topicId, 'exercise'), type: 'miniExercise' as const, title: 'Produza a evidência', instruction: module.practice, nextAction: module.resources.some((item) => item.type === 'video') ? 'WATCH_VIDEO' as const : 'PRACTICE' as const },
  ] }
}

export class StudyLessonService {
  constructor(private readonly repository: StudyLessonRepository, private readonly providers: AIProviderManager, private readonly getWorkspace: (id: string) => Promise<Workspace | null>, private readonly getRoadmap: (workspaceId: string) => Roadmap | null, private readonly now = Date.now) {}
  async getOrCreate(input: { workspaceId: string; roadmapId: string; moduleId: string; topicId: string }): Promise<PersistedStudyLesson> {
    const cached = this.repository.find(input.roadmapId, input.topicId)
    if (cached) return cached
    const workspace = await this.getWorkspace(input.workspaceId); const roadmap = this.getRoadmap(input.workspaceId); const module = roadmap?.modules.find((item) => item.id === input.moduleId); const topic = module?.topics.find((item) => `${module.id}:${item}` === input.topicId)
    if (!workspace || !roadmap || roadmap.id !== input.roadmapId || !module || !topic) throw new Error('Study topic not found in current roadmap')
    let content: { title: string; level: 'basic' | 'intermediate' | 'advanced'; objective: string; blocks: StudyLessonBlock[] } = localLesson(workspace, module, topic, input.topicId); let providerId: string | null = null; let modelId: string | null = null
    const provider = this.providers.route('lesson')
    if (provider) try { const response = await provider.sendMessage({ messages: [{ role: 'system', content: 'Crie uma aula específica, sem headings genéricos, para o tópico real fornecido. Retorne somente JSON: {"title":string,"level":"basic|intermediate|advanced","objective":string,"blocks":[blocos]}. Tipos: explanation/analogy/warning/commonError/comparison com id,title,content; codeExample com id,title,code,language,expectedOutput,walkthrough; checkpoint com id,title,question,options,correctIndex,difficultyByOption,hint,reinforcement; miniExercise com id,title,instruction,nextAction (NEXT_TOPIC|RETRY|REVIEW|PRACTICE|WATCH_VIDEO|CONTINUE). Inclua ao menos explicação específica, exemplo, checkpoint durante a aula e exercício. IDs devem começar pelo topicId. Não use perguntas universais nem troque apenas o nome do tópico.' }, { role: 'user', content: JSON.stringify({ workspace: workspace.name, objective: workspace.objective, level: levelFor(workspace), roadmap: roadmap.title, module: { title: module.title, objective: module.objective, outcomes: module.outcomes, practice: module.practice }, topic, topicId: input.topicId }) }], maxOutputTokens: 3200, signal: AbortSignal.timeout(45_000) }); const parsed = studyLessonContentSchema.parse(extractJson(response.content)); if (parsed.blocks.some((block) => block.type === 'checkpoint') && parsed.blocks.some((block) => block.type === 'codeExample')) { content = parsed; providerId = response.providerId; modelId = response.modelId } } catch { /* local topic-specific lesson remains available */ }
    const now = this.now(); return this.repository.create({ ...content, id: `${input.topicId}:lesson`, workspaceId: input.workspaceId, roadmapId: input.roadmapId, moduleId: input.moduleId, topicId: input.topicId, providerId, modelId, createdAt: now })
  }
  evaluate(lesson: PersistedStudyLesson, checkpointId: string, selectedIndex: number, attempt: number): StudyCheckpointEvaluation { const block = lesson.blocks.find((item): item is Extract<StudyLessonBlock, { type: 'checkpoint' }> => item.type === 'checkpoint' && item.id === checkpointId); if (!block) throw new Error('Checkpoint not found'); const correct = selectedIndex === block.correctIndex; return correct ? { correct: true, difficulty: null, feedback: 'A resposta demonstra compreensão do ponto verificado. Use-a agora no próximo bloco da aula.', hint: null, reinforcement: null } : { correct: false, difficulty: block.difficultyByOption[selectedIndex] ?? 'conceito relacionado ao checkpoint', feedback: `A tentativa ${attempt} indica dificuldade em ${block.difficultyByOption[selectedIndex] ?? 'uma distinção importante'}.`, hint: block.hint, reinforcement: attempt > 1 ? block.reinforcement : null } }
}
