import type { CurrentWorkspaceContext } from './current-workspace-context'

export type WorkspaceContextResource = 'workspace' | 'academic' | 'roadmap' | 'progress' | 'lesson' | 'materials' | 'plan' | 'notes' | 'project' | 'practice' | 'execution'
export interface WorkspaceImmediateContext { workspaceId: string; subject: string; objective: string; declaredLevel: string | null; activePage: string; activeRoadmapId: string | null; moduleId: string | null; topicId: string | null; lessonId: string | null; currentBlockId: string | null; currentExcerpt: string | null; activePlanItemId: string | null; timerStatus: string }
export interface WorkspaceContextHubDependencies { getCurrent(workspaceId: string): Promise<CurrentWorkspaceContext>; read(workspaceId: string, resource: WorkspaceContextResource, options?: { id?: string; offset?: number; limit?: number }): Promise<unknown> }
export class WorkspaceContextHub {
  constructor(private readonly dependencies: WorkspaceContextHubDependencies) {}
  async immediate(workspaceId: string, view: { activePage: string; currentBlockId?: string | null; currentExcerpt?: string | null } = { activePage: 'coach' }): Promise<WorkspaceImmediateContext> { const current = await this.dependencies.getCurrent(workspaceId); return { workspaceId, subject: current.workspace.name, objective: current.workspace.objective, declaredLevel: current.academicSubject?.declaredLevel ?? null, activePage: view.activePage, activeRoadmapId: null, moduleId: null, topicId: null, lessonId: null, currentBlockId: view.currentBlockId ?? null, currentExcerpt: view.currentExcerpt?.slice(0, 2000) ?? null, activePlanItemId: current.study.plan.find((item) => item.status === 'active')?.id ?? null, timerStatus: current.study.timerStatus } }
  read(workspaceId: string, resource: WorkspaceContextResource, options?: { id?: string; offset?: number; limit?: number }): Promise<unknown> { return this.dependencies.read(workspaceId, resource, { ...options, limit: Math.min(100, Math.max(1, options?.limit ?? 20)), offset: Math.max(0, options?.offset ?? 0) }) }
}
