import type { CurrentWorkspaceContext } from './current-workspace-context'
import type { AcademicLifeItem } from '../../shared/contracts/academic-life-contract'

export type WorkspaceContextResource = 'workspace' | 'academic' | 'roadmap' | 'progress' | 'lesson' | 'materials' | 'plan' | 'notes'
export interface WorkspaceImmediateContext { workspaceId: string; subject: string; objective: string; declaredLevel: string | null; activePage: string; activeRoadmapId: string | null; moduleId: string | null; topicId: string | null; lessonId: string | null; currentBlockId: string | null; currentExcerpt: string | null; activePlanItemId: string | null; timerStatus: string; academicLife: Array<Pick<AcademicLifeItem, 'id' | 'kind' | 'title' | 'details' | 'startsAt' | 'endsAt' | 'expiresAt' | 'timezone' | 'weekday' | 'minutes' | 'workspaceId' | 'provenance'>> }
export interface WorkspaceContextReadOptions { id?: string; offset?: number; limit?: number; pageNumber?: number; query?: string }
export interface WorkspaceContextHubDependencies { getCurrent(workspaceId: string): Promise<CurrentWorkspaceContext>; read(workspaceId: string, resource: WorkspaceContextResource, options?: WorkspaceContextReadOptions): Promise<unknown>; getAcademicLifeContext?(workspaceId: string, limit: number): AcademicLifeItem[] }
export class WorkspaceContextHub {
  constructor(private readonly dependencies: WorkspaceContextHubDependencies) {}
  async immediate(workspaceId: string, view: { activePage: string; activeStudy?: { roadmapId: string; moduleId: string; topicId: string; lessonId: string } | null; currentBlockId?: string | null; currentExcerpt?: string | null } = { activePage: 'coach' }): Promise<WorkspaceImmediateContext> { const current = await this.dependencies.getCurrent(workspaceId); const academicLife = (this.dependencies.getAcademicLifeContext?.(workspaceId, 12) ?? []).map(({ id, kind, title, details, startsAt, endsAt, expiresAt, timezone, weekday, minutes, workspaceId: scope, provenance }) => ({ id, kind, title, details: details.slice(0, 500), startsAt, endsAt, expiresAt, timezone, weekday, minutes, workspaceId: scope, provenance })); return { workspaceId, subject: current.workspace.name, objective: current.workspace.objective, declaredLevel: current.academicSubject?.declaredLevel ?? null, activePage: view.activePage, activeRoadmapId: view.activeStudy?.roadmapId ?? null, moduleId: view.activeStudy?.moduleId ?? null, topicId: view.activeStudy?.topicId ?? null, lessonId: view.activeStudy?.lessonId ?? null, currentBlockId: view.currentBlockId ?? null, currentExcerpt: view.currentExcerpt?.slice(0, 2000) ?? null, activePlanItemId: current.study.plan.find((item) => item.status === 'active')?.id ?? null, timerStatus: current.study.timerStatus, academicLife } }
  read(workspaceId: string, resource: WorkspaceContextResource, options?: WorkspaceContextReadOptions): Promise<unknown> { return this.dependencies.read(workspaceId, resource, { ...options, limit: Math.min(resource === 'materials' ? 6000 : 100, Math.max(1, options?.limit ?? 20)), offset: Math.max(0, options?.offset ?? 0) }) }
}
