import type { AIProviderManager } from '../ai/ai-provider-manager'
import { generatedRoadmapProposalSchema, roadmapProposalSchema, type CurriculumSource, type LearningPathState, type Roadmap, type RoadmapResource } from '../../shared/contracts/roadmap-contract'
import type { Workspace } from '../../shared/contracts/workspace-contract'
import type { CurriculumSourceService } from './curriculum-source-service'

export interface RoadmapRepository { findCurrent(workspaceId: string): Roadmap | null; nextVersion(workspaceId: string): number; create(roadmap: Roadmap): Roadmap; activate(roadmap: Roadmap): Roadmap; accept(workspaceId: string, roadmapId: string, now: number): Roadmap; getLearningPathState(workspaceId: string): LearningPathState | null; setLearningPathState(state: LearningPathState): LearningPathState; recoverInterrupted(workspaceId: string, now: number, staleBefore: number, retryAfter: number): LearningPathState | null; tryStartGeneration(workspaceId: string, activeRoadmapId: string | null, now: number, staleBefore: number): boolean; listWaitingForProvider(): string[] }
export interface RoadmapAcademicContext { difficulties: string[]; deadline: number | null; availability: Array<{ weekday: number; minutes: number }>; knownContext: string[] }

function module(title: string, objective: string, topics: string[], outcomes: string[], practice: string, completionCriteria: string[], resource: RoadmapResource | null, estimatedMinutes = 150) { return { title, objective, estimatedMinutes, topics, outcomes, practice, completionCriteria, resources: resource ? [resource] : [] } }
export function fallback(workspace: Workspace) {
  const source: RoadmapResource | null = null; const subject = workspace.name
  const python = /python/i.test(`${subject} ${workspace.objective}`); const advanced = /avançad|avancad|experiente|intermediário|intermediario|já domino|ja domino/i.test(`${subject} ${workspace.objective}`)
  if (/javafx/i.test(subject)) return { title: `Trilha prática: ${subject}`, modules: [
    module('Application, Stage e Scene', 'Compreender o ciclo visual do JavaFX', ['Application lifecycle', 'Stage', 'Scene', 'scene graph'], ['Inicializar uma aplicação'], 'Criar uma janela com cenas substituíveis.', ['Janela inicia sem erros'], source),
    module('Layouts e composição responsiva', 'Organizar componentes sem coordenadas rígidas', ['VBox e HBox', 'BorderPane', 'GridPane', 'constraints e grow'], ['Escolher layouts adequados'], 'Reproduzir um formulário responsivo com layouts aninhados.', ['Redimensionamento preserva hierarquia'], source),
    module('Controles, eventos e bindings', 'Construir interação orientada a estado', ['controls', 'event handlers', 'properties', 'binding'], ['Conectar estado e interface'], 'Criar formulário validado com bindings.', ['Eventos e validação cobertos'], source),
    module('FXML, controllers e CSS', 'Separar estrutura visual e comportamento', ['FXML', 'FXMLLoader', 'controllers', 'injeção @FXML', 'JavaFX CSS'], ['Estruturar telas reutilizáveis'], 'Criar duas telas FXML com navegação e tema CSS.', ['Controllers sem estado global'], source),
  ] }
  if (python) return { title: `Trilha ${advanced ? 'avançada' : 'essencial'}: ${subject}`, modules: (advanced ? [
    module('Iteradores, generators e avaliação lazy', 'Controlar iteração e memória em pipelines extensos', ['protocolo iterator', 'yield e generators', 'itertools', 'expressões geradoras'], ['Implementar iteradores próprios', 'Medir consumo lazy'], 'Construir um pipeline lazy para processar um arquivo grande sem carregá-lo inteiro.', ['Memória permanece limitada', 'Testes cobrem fim da iteração'], source),
    module('Decorators e context managers', 'Compor comportamento e controlar recursos com segurança', ['funções de alta ordem', 'functools.wraps', 'decorators parametrizados', '__enter__ e __exit__', 'contextlib'], ['Criar decorators transparentes', 'Garantir liberação de recursos'], 'Implementar medição de tempo por decorator e uma transação por context manager.', ['Metadados preservados', 'Recurso fecha mesmo com exceção'], source),
    module('Typing, protocolos e dataclasses', 'Expressar contratos verificáveis em domínios maiores', ['type hints', 'generics', 'Protocol', 'dataclasses', 'mypy/pyright'], ['Modelar contratos estruturais', 'Reduzir estados inválidos'], 'Modelar um domínio com dataclasses imutáveis e portas definidas por Protocol.', ['Verificador estático sem erros', 'Domínio não depende da infraestrutura'], source),
    module('Asyncio e concorrência', 'Escolher concorrência adequada para I/O e CPU', ['event loop', 'async/await', 'TaskGroup', 'threads e processos', 'cancelamento'], ['Executar I/O concorrente', 'Cancelar tarefas sem vazamento'], 'Criar um coletor concorrente com timeout, cancelamento e limite de paralelismo.', ['Falhas não deixam tarefas pendentes', 'Limite de concorrência testado'], source, 210),
    module('Testes, profiling e arquitetura', 'Entregar software Python observável e sustentável', ['pytest e fixtures', 'mocks nas fronteiras', 'cProfile', 'logging estruturado', 'arquitetura em camadas'], ['Localizar gargalos', 'Testar comportamento isoladamente'], 'Perfilar e refatorar uma aplicação em camadas, mantendo uma suíte automatizada.', ['Gargalo medido antes/depois', 'Casos críticos testados', 'Dependências apontam para o domínio'], source, 240),
  ] : [
    module('Executar Python e produzir saída', 'Entender como um programa Python é salvo e executado', ['interpretador e arquivo .py', 'print', 'comentários', 'erros de sintaxe'], ['Executar pelo terminal', 'Ler a linha indicada em SyntaxError'], 'Criar e executar um programa que imprime três informações em linhas separadas.', ['Executa sem erro', 'Saída corresponde ao esperado'], source, 60),
    module('Variáveis, tipos e entrada', 'Receber, guardar e transformar valores', ['variáveis', 'str, int, float e bool', 'input', 'conversão de tipos', 'f-strings'], ['Converter entrada corretamente', 'Inspecionar tipos'], 'Criar um calculador de idade futura que valida e converte a entrada.', ['Usa input e conversão', 'Mensagem usa f-string', 'Entrada inválida é tratada'], source, 90),
    module('Condições e decisões', 'Representar regras com caminhos claros', ['comparações', 'and/or/not', 'if/elif/else', 'truthiness'], ['Traduzir regra para condição', 'Cobrir caminhos alternativos'], 'Criar um classificador de notas com limites e mensagens para entradas inválidas.', ['Todos os limites testados', 'Sem condições redundantes'], source, 90),
    module('Loops e coleções', 'Processar sequências sem repetição manual', ['for e range', 'while', 'listas', 'append', 'break e continue'], ['Percorrer e acumular', 'Escolher condição de parada'], 'Ler várias notas, armazená-las e calcular menor, maior e média.', ['Loop termina corretamente', 'Lista contém entradas', 'Cálculos conferidos'], source, 120),
    module('Funções e tratamento de erros', 'Separar responsabilidades reutilizáveis', ['def e return', 'parâmetros', 'escopo', 'ValueError', 'try/except'], ['Decompor programa', 'Tratar erro esperado'], 'Refatorar o exercício de notas em funções pequenas e testáveis.', ['Funções retornam valores', 'Interface separada da lógica', 'Casos inválidos testados'], source, 150),
  ]) }
  if (/java|poo|orienta.+objeto/i.test(`${subject} ${workspace.objective}`)) return { title: `Trilha prática: ${subject}`, modules: [
    module('Sintaxe, tipos e fluxo de controle', 'Escrever programas Java pequenos e previsíveis', ['JDK, javac e execução', 'variáveis e tipos', 'condicionais', 'laços', 'métodos'], ['Compilar e executar sem ajuda', 'Explicar escopo e fluxo'], 'Criar um programa de console que valida entradas e calcula um resultado usando métodos separados.', ['Compila sem erros', 'Trata entrada inválida', 'Não repete lógica'], source),
    module('Classes, objetos e encapsulamento', 'Modelar entidades protegendo suas regras', ['classes e instâncias', 'construtores', 'campos privados', 'métodos', 'imutabilidade'], ['Transformar requisitos em classes', 'Manter invariantes'], 'Modelar uma conta bancária que impeça saldo inválido e registre depósitos e saques.', ['Campos privados', 'Construtor valida estado', 'Casos válidos e inválidos demonstrados'], source),
    module('Coleções, generics e exceções', 'Manipular conjuntos tipados e falhas esperadas', ['List, Set e Map', 'generics', 'equals/hashCode', 'exceções'], ['Escolher coleção adequada', 'Tratar falhas na fronteira'], 'Construir um catálogo pesquisável sem itens duplicados e com erros de domínio explícitos.', ['Usa coleção coerente', 'Sem casts inseguros', 'Falhas possuem mensagem útil'], source),
    module('Interfaces, composição e polimorfismo', 'Separar contratos de implementações substituíveis', ['interfaces', 'composição', 'polimorfismo', 'injeção de dependência'], ['Trocar implementação sem mudar cliente', 'Evitar herança desnecessária'], 'Criar duas formas de persistir tarefas por uma interface e testar a troca entre elas.', ['Cliente depende da interface', 'Duas implementações funcionam', 'Decisão de composição explicada'], source),
    module('Projeto integrador testável', 'Consolidar a trilha em uma aplicação multi-arquivo', ['pacotes', 'separação de responsabilidades', 'testes unitários', 'refatoração'], ['Organizar projeto real', 'Validar comportamento automaticamente'], 'Entregar um gerenciador de estudos com domínio, persistência substituível e testes dos casos críticos.', ['Projeto compila do zero', 'Casos críticos têm testes', 'README explica decisões'], source, 240),
  ] }
  return null

}

function extractJson(content: string): unknown { const fenced = /```(?:json)?\s*([\s\S]*?)```/i.exec(content)?.[1]; const candidate = fenced ?? content.slice(content.indexOf('{'), content.lastIndexOf('}') + 1); return JSON.parse(candidate) }
export function hasGenericModules(proposal: ReturnType<typeof roadmapProposalSchema.parse>): boolean { const vague = /^(fundamentos|introdução|introducao|revisar conceitos?|prática guiada|pratica guiada|prática independente|projeto integrador)$/i; const rendered = JSON.stringify(proposal).toLocaleLowerCase(); return /vocabulário e mapa|mapa de 10 conceitos|mecanismos centrais|aplicação guiada|projeto independente/.test(rendered) || proposal.modules.some((item) => vague.test(item.title.trim()) || item.topics.some((topic) => /^(conceitos? (básicos|essenciais)|revisar conceitos?)$/i.test(topic))) }

const RETRY_COOLDOWN = 5 * 60_000
function resourceType(source: CurriculumSource): RoadmapResource['type'] { return source.type === 'outline' ? 'roadmap' : source.type === 'documentation' || source.type === 'reference' ? 'documentation' : source.type === 'educational' ? 'course' : 'article' }

export class RoadmapService {
  private readonly generating = new Map<string, Promise<LearningPathState>>()
  constructor(private readonly repository: RoadmapRepository, private readonly providers: AIProviderManager, private readonly getWorkspace: (id: string) => Promise<Workspace | null>, private readonly getAcademicContext: (workspaceId: string) => RoadmapAcademicContext = () => ({ difficulties: [], deadline: null, availability: [], knownContext: [] }), private readonly curriculumSources?: CurriculumSourceService, private readonly now = Date.now, private readonly createId = () => crypto.randomUUID()) {}
  retryWaitingForProvider(): void { for (const workspaceId of this.repository.listWaitingForProvider()) void this.ensureLearningPath(workspaceId, { forceProviderRetry: true }).catch(() => {}) }
  async get(workspaceId: string): Promise<Roadmap | null> { await this.requireWorkspace(workspaceId); const roadmap = this.repository.findCurrent(workspaceId); if (!roadmap) void this.ensureLearningPath(workspaceId).catch(() => {}); return roadmap }
  async getLearningPathState(workspaceId: string): Promise<LearningPathState> { await this.requireWorkspace(workspaceId); const now = this.now(); return this.repository.recoverInterrupted(workspaceId, now, now - RETRY_COOLDOWN, now + RETRY_COOLDOWN) ?? this.repository.setLearningPathState({ workspaceId, status: 'idle', activeRoadmapId: null, lastAttemptAt: null, retryAfter: null, lastErrorCode: null, updatedAt: now }) }
  ensureLearningPath(workspaceId: string, options: { forceProviderRetry?: boolean } = {}): Promise<LearningPathState> {
    const running = this.generating.get(workspaceId); if (running) return running
    const task = this.ensureOnce(workspaceId, options).finally(() => this.generating.delete(workspaceId)); this.generating.set(workspaceId, task); return task
  }
  private async ensureOnce(workspaceId: string, options: { forceProviderRetry?: boolean }): Promise<LearningPathState> {
    await this.requireWorkspace(workspaceId); const now = this.now(); const current = this.repository.findCurrent(workspaceId); let state = this.repository.recoverInterrupted(workspaceId, now, now - RETRY_COOLDOWN, now + RETRY_COOLDOWN)
    if (current && current.generationKind === 'ai_generated') return this.repository.setLearningPathState({ workspaceId, status: 'ready', activeRoadmapId: current.id, lastAttemptAt: state?.lastAttemptAt ?? null, retryAfter: null, lastErrorCode: null, updatedAt: now })
    if (!options.forceProviderRetry && state?.retryAfter && state.retryAfter > now) return state
    const provider = this.providers.route('roadmap')
    if (!provider) return this.repository.setLearningPathState({ workspaceId, status: 'waiting_for_provider', activeRoadmapId: current?.id ?? null, lastAttemptAt: now, retryAfter: now + RETRY_COOLDOWN, lastErrorCode: 'PROVIDER_UNAVAILABLE', updatedAt: now })
    if (!this.repository.tryStartGeneration(workspaceId, current?.id ?? null, now, now - RETRY_COOLDOWN)) return this.repository.getLearningPathState(workspaceId)!
    state = this.repository.getLearningPathState(workspaceId)!
    try { const roadmap = await this.generateWithProvider(workspaceId, provider); return this.repository.setLearningPathState({ workspaceId, status: 'ready', activeRoadmapId: roadmap.id, lastAttemptAt: now, retryAfter: null, lastErrorCode: null, updatedAt: this.now() }) }
    catch (error) { const unavailable = error instanceof Error && ('code' in error ? (error as { code?: string }).code === 'NETWORK_UNAVAILABLE' : /network|fetch|offline|unavailable|connect|timeout|timed out|aborted|cancel/i.test(`${error.name} ${error.message}`)); return this.repository.setLearningPathState({ workspaceId, status: unavailable ? 'waiting_for_provider' : 'failed_retryable', activeRoadmapId: current?.id ?? null, lastAttemptAt: now, retryAfter: now + RETRY_COOLDOWN, lastErrorCode: unavailable ? 'PROVIDER_UNAVAILABLE' : 'GENERATION_FAILED', updatedAt: this.now() }) }
  }
  generate(workspaceId: string, instruction?: string): Promise<Roadmap> { return this.generateWithProvider(workspaceId, this.providers.route('roadmap'), instruction) }
  private async generateWithProvider(workspaceId: string, provider: ReturnType<AIProviderManager['route']>, instruction?: string): Promise<Roadmap> {
    if (!provider) throw new Error('Provider unavailable')
    const workspace = await this.requireWorkspace(workspaceId); const academic = this.getAcademicContext(workspaceId); const sources = await this.curriculumSources?.sourcesFor(workspace) ?? []; const retrieved = sources.filter((source) => source.retrieved && source.excerpt); const allowed = new Map(retrieved.map((source) => [source.id, source]))
    const response = await provider.sendMessage({ messages: [{ role: 'system', content: `Gere somente a estrutura curricular progressiva da Trilha de Aprendizado. Não gere aula completa. Proibido usar módulos vagos ou os padrões "Vocabulário e mapa", "Mecanismos centrais", "Mapa de 10 conceitos", "Fundamentos genéricos" e "Projeto independente genérico". Use apenas sourceIds fornecidos; não retorne URLs. JSON: {"title":string,"modules":[{"title":string,"objective":string,"estimatedMinutes":number,"topics":[string,string],"outcomes":[string],"practice":string,"completionCriteria":[string],"sourceIds":[string]}]}.` }, { role: 'user', content: JSON.stringify({ subject: workspace.name, objective: workspace.objective || null, difficulties: academic.difficulties, deadline: academic.deadline, availability: academic.availability, knownContext: academic.knownContext, topicLearningState: [], sources: sources.map(({ excerpt, ...metadata }) => metadata), retrievedCurriculumExcerpts: retrieved.map(({ id, excerpt }) => ({ sourceId: id, content: excerpt })), requestedChange: instruction || null }) }], maxOutputTokens: 3200, signal: AbortSignal.timeout(45_000) })
    const generated = generatedRoadmapProposalSchema.parse(extractJson(response.content)); const proposal = roadmapProposalSchema.parse({ title: generated.title, modules: generated.modules.map(({ sourceIds, ...item }) => ({ ...item, resources: sourceIds.map((id) => allowed.get(id)).filter((source): source is CurriculumSource => Boolean(source)).map((source) => ({ title: source.title, url: source.url, type: resourceType(source) })) })) })
    if (hasGenericModules(proposal)) throw new Error('GENERIC_ROADMAP')
    const now = this.now(); return this.repository.activate({ id: this.createId(), workspaceId, title: proposal.title, status: 'accepted', generationKind: 'ai_generated', version: this.repository.nextVersion(workspaceId), providerId: response.providerId, modelId: response.modelId, modules: proposal.modules.map((item, index) => ({ id: this.createId(), ...item, position: index + 1, status: index === 0 ? 'active' : 'locked' })), createdAt: now, updatedAt: now })
  }
  async accept(workspaceId: string, roadmapId: string): Promise<Roadmap> { await this.requireWorkspace(workspaceId); return this.repository.accept(workspaceId, roadmapId, this.now()) }
  private async requireWorkspace(id: string): Promise<Workspace> { const workspace = await this.getWorkspace(id); if (!workspace || workspace.status !== 'active') throw new Error('Workspace not found'); return workspace }
}
